textbook:
  'Wave Motions in the Ocean and Atmosphere Textbook":':
    chapters:
    - '- Chapter 1: Basics:':
        sections:
        - '- Section: 1.1 Introduction to Wave Motions:':
            subsections:
            - 1.1a Definition of Wave Motions
            - 1.1b Types of Wave Motions
            - 1.1c Importance of Wave Motions
        - '- Section: 1.2 Wave Equations:':
            subsections:
            - 1.2a Derivation of Wave Equations
            - 1.2b Solutions to Wave Equations
            - 1.2c Applications of Wave Equations
        - '- Section: 1.3 Linear and Nonlinear Waves:':
            subsections:
            - 1.3a Definition of Linear and Nonlinear Waves
            - 1.3b Differences between Linear and Nonlinear Waves
            - 1.3c Applications of Linear and Nonlinear Waves
        - '- Section: 1.4 Dispersion and Group Velocity:':
            subsections:
            - 1.4a Definition of Dispersion and Group Velocity
            - 1.4b Relationship between Dispersion and Group Velocity
            - 1.4c Effects of Dispersion and Group Velocity on Wave Propagation
    - '- Chapter 2: Boussinesq Approximation:':
        sections:
        - '- Section: 2.1 Derivation of Boussinesq Equations:':
            subsections:
            - 2.1a Process of Deriving Boussinesq Equations
            - 2.1b Assumptions in Boussinesq Equations
            - 2.1c Applications of Boussinesq Equations
        - '- Section: 2.2 Assumptions and Limitations:':
            subsections:
            - 2.2a Assumptions in Boussinesq Approximation
            - 2.2b Limitations of Boussinesq Approximation
            - 2.2c Overcoming Limitations of Boussinesq Approximation
        - '- Section: 2.3 Applications in Ocean and Atmosphere:':
            subsections:
            - 2.3a Use of Boussinesq Approximation in Ocean Studies
            - 2.3b Use of Boussinesq Approximation in Atmospheric Studies
            - 2.3c Recent Developments in Boussinesq Approximation
    - '- Chapter 3: Available Potential Energy:':
        sections:
        - '- Section: 3.1 Introduction to Available Potential Energy:':
            subsections:
            - 3.1a Definition of Available Potential Energy
            - 3.1b Importance of Available Potential Energy
            - 3.1c Calculation of Available Potential Energy
        - '- Section: 3.2 Calculation Methods:':
            subsections:
            - 3.2a Traditional Calculation Methods
            - 3.2b Modern Calculation Methods
            - 3.2c Comparison of Calculation Methods
        - '- Section: 3.3 Interpretation and Significance:':
            subsections:
            - 3.3a Interpretation of Available Potential Energy
            - 3.3b Significance of Available Potential Energy
            - 3.3c Recent Studies on Available Potential Energy
        - '- Section: 3.4 Relationship with Wave Motions:':
            subsections:
            - 3.4a How Available Potential Energy Affects Wave Motions
            - 3.4b Studies on the Relationship between Available Potential Energy
              and Wave Motions
            - 3.4c Future Research Directions
    - '- Chapter 4: Internal Gravity Waves:':
        sections:
        - '- Section: 4.1 Characteristics of Internal Gravity Waves:':
            subsections:
            - 4.1a Definition of Internal Gravity Waves
            - 4.1b Properties of Internal Gravity Waves
            - 4.1c Importance of Internal Gravity Waves
        - '- Section: 4.2 Propagation and Dispersion:':
            subsections:
            - 4.2a How Internal Gravity Waves Propagate
            - 4.2b Dispersion of Internal Gravity Waves
            - 4.2c Factors Affecting Propagation and Dispersion
        - '- Section: 4.3 Generation Mechanisms:':
            subsections:
            - 4.3a How Internal Gravity Waves are Generated
            - 4.3b Factors Affecting Generation of Internal Gravity Waves
            - 4.3c Recent Studies on Generation Mechanisms
        - '- Section: 4.4 Reflection and Refraction:':
            subsections:
            - 4.4a Reflection of Internal Gravity Waves
            - 4.4b Refraction of Internal Gravity Waves
            - 4.4c Effects of Reflection and Refraction on Wave Propagation
    - "- Chapter 5: Surface Forced IGW\u2019s:":
        sections:
        - '- Section: 5.1 Wind-Driven Surface Waves:':
            subsections:
            - 5.1a How Wind Drives Surface Waves
            - 5.1b Characteristics of Wind-Driven Surface Waves
            - 5.1c Effects of Wind-Driven Surface Waves on Ocean Dynamics
        - '- Section: 5.2 Wave-Current Interactions:':
            subsections:
            - 5.2a How Waves Interact with Currents
            - 5.2b Effects of Wave-Current Interactions on Wave Propagation
            - 5.2c Studies on Wave-Current Interactions
        - '- Section: 5.3 Wave Breaking and Dissipation:':
            subsections:
            - 5.3a How Waves Break and Dissipate
            - 5.3b Effects of Wave Breaking and Dissipation on Ocean Dynamics
            - 5.3c Recent Studies on Wave Breaking and Dissipation
    - '- Chapter 6: Curvilinear Coordinates:':
        sections:
        - '- Section: 6.1 Coordinate Systems in Ocean and Atmosphere:':
            subsections:
            - 6.1a Different Coordinate Systems Used in Ocean and Atmospheric Studies
            - 6.1b Importance of Choosing Appropriate Coordinate Systems
            - 6.1c Recent Developments in Coordinate Systems
        - '- Section: 6.2 Transformations and Jacobians:':
            subsections:
            - 6.2a How to Transform Between Different Coordinate Systems
            - 6.2b Role of Jacobians in Coordinate Transformations
            - 6.2c Applications of Coordinate Transformations in Ocean and Atmospheric
              Studies
        - '- Section: 6.3 Wave Equations in Curvilinear Coordinates:':
            subsections:
            - 6.3a How to Derive Wave Equations in Curvilinear Coordinates
            - 6.3b Solutions to Wave Equations in Curvilinear Coordinates
            - 6.3c Applications of Wave Equations in Curvilinear Coordinates
    - '- Chapter 7: Pressure-like Coordinates:':
        sections:
        - '- Section: 7.1 Definition and Applications of Pressure-like Coordinates:':
            subsections:
            - 7.1a Definition of Pressure-like Coordinates
            - 7.1b Importance of Pressure-like Coordinates
            - 7.1c Applications of Pressure-like Coordinates in Ocean and Atmospheric
              Studies
        - '- Section: 7.2 Vertical Coordinate Systems:':
            subsections:
            - 7.2a Different Vertical Coordinate Systems Used in Ocean and Atmospheric
              Studies
            - 7.2b Importance of Choosing Appropriate Vertical Coordinate Systems
            - 7.2c Recent Developments in Vertical Coordinate Systems
        - '- Section: 7.3 Stacked Baroclinic Modes:':
            subsections:
            - 7.3a Definition of Stacked Baroclinic Modes
            - 7.3b Importance of Stacked Baroclinic Modes
            - 7.3c Applications of Stacked Baroclinic Modes in Ocean and Atmospheric
              Studies
    - '- Chapter 8: Surface Waves:':
        sections:
        - '- Section: 8.1 Characteristics of Surface Waves:':
            subsections:
            - 8.1a Definition of Surface Waves
            - 8.1b Properties of Surface Waves
            - 8.1c Importance of Surface Waves
        - '- Section: 8.2 Gravity Waves and Capillary Waves:':
            subsections:
            - 8.2a Definition of Gravity Waves and Capillary Waves
            - 8.2b Differences between Gravity Waves and Capillary Waves
            - 8.2c Applications of Gravity Waves and Capillary Waves
        - '- Section: 8.3 Wind Waves and Swell:':
            subsections:
            - 8.3a How Wind Generates Waves and Swell
            - 8.3b Characteristics of Wind Waves and Swell
            - 8.3c Effects of Wind Waves and Swell on Ocean Dynamics
    - '- Chapter 9: Shallow Water Equations:':
        sections:
        - '- Section: 9.1 Derivation and Assumptions of Shallow Water Equations:':
            subsections:
            - 9.1a How to Derive Shallow Water Equations
            - 9.1b Assumptions in Shallow Water Equations
            - 9.1c Applications of Shallow Water Equations
        - '- Section: 9.2 Solving Shallow Water Equations:':
            subsections:
            - 9.2a Methods to Solve Shallow Water Equations
            - 9.2b Challenges in Solving Shallow Water Equations
            - 9.2c Recent Developments in Solving Shallow Water Equations
        - '- Section: 9.3 Applications in Ocean and Atmospheric Dynamics:':
            subsections:
            - 9.3a Use of Shallow Water Equations in Ocean Dynamics
            - 9.3b Use of Shallow Water Equations in Atmospheric Dynamics
            - 9.3c Future Research Directions
    - '- Chapter 10: Thermodynamics:':
        sections:
        - '- Section: 10.1 Basic Concepts of Thermodynamics:':
            subsections:
            - 10.1a Definition of Thermodynamics
            - 10.1b Basic Laws of Thermodynamics
            - 10.1c Importance of Thermodynamics in Ocean and Atmospheric Studies
        - '- Section: 10.2 Thermodynamic Equilibrium and Stability:':
            subsections:
            - 10.2a Definition of Thermodynamic Equilibrium and Stability
            - 10.2b Factors Affecting Thermodynamic Equilibrium and Stability
            - 10.2c Effects of Thermodynamic Equilibrium and Stability on Ocean and
              Atmospheric Dynamics
        - '- Section: 10.3 Heat Flux and Energy Balance:':
            subsections:
            - 10.3a How Heat Flux and Energy Balance are Calculated
            - 10.3b Importance of Heat Flux and Energy Balance
            - 10.3c Effects of Heat Flux and Energy Balance on Ocean and Atmospheric
              Dynamics
    - '- Chapter 11: Laplace Tidal Equations:':
        sections:
        - '- Section: 11.1 Introduction to Tidal Equations:':
            subsections:
            - 11.1a Definition of Tidal Equations
            - 11.1b Importance of Tidal Equations
            - 11.1c Applications of Tidal Equations
        - '- Section: 11.2 Laplace''s Tidal Equations:':
            subsections:
            - 11.2a How to Derive Laplace's Tidal Equations
            - 11.2b Solutions to Laplace's Tidal Equations
            - 11.2c Applications of Laplace's Tidal Equations
        - '- Section: 11.3 Tidal Analysis and Prediction:':
            subsections:
            - 11.3a How to Analyze and Predict Tides
            - 11.3b Importance of Tidal Analysis and Prediction
            - 11.3c Recent Developments in Tidal Analysis and Prediction
    - '- Chapter 12: Hough Functions:':
        sections:
        - '- Section: 12.1 Definition and Properties of Hough Functions:':
            subsections:
            - 12.1a Definition of Hough Functions
            - 12.1b Properties of Hough Functions
            - 12.1c Importance of Hough Functions
        - '- Section: 12.2 Applications in Geophysical Fluid Dynamics:':
            subsections:
            - 12.2a Use of Hough Functions in Geophysical Fluid Dynamics
            - 12.2b Importance of Hough Functions in Geophysical Fluid Dynamics
            - 12.2c Recent Developments in the Use of Hough Functions
        - '- Section: 12.3 Hough Modes and Wave Dynamics:':
            subsections:
            - 12.3a Definition of Hough Modes
            - 12.3b Relationship between Hough Modes and Wave Dynamics
            - 12.3c Studies on Hough Modes and Wave Dynamics
    - '- Chapter 13: Equatorial Beta Plane:':
        sections:
        - '- Section: 13.1 Equatorial Dynamics and Beta Plane Approximation:':
            subsections:
            - 13.1a Definition of Equatorial Dynamics and Beta Plane Approximation
            - 13.1b Importance of Equatorial Dynamics and Beta Plane Approximation
            - 13.1c Applications of Equatorial Dynamics and Beta Plane Approximation
        - '- Section: 13.2 Equatorial Waves and Kelvin Waves:':
            subsections:
            - 13.2a Definition of Equatorial Waves and Kelvin Waves
            - 13.2b Differences between Equatorial Waves and Kelvin Waves
            - 13.2c Applications of Equatorial Waves and Kelvin Waves
        - '- Section: 13.3 Rossby Waves and Equatorial Rossby Waves:':
            subsections:
            - 13.3a Definition of Rossby Waves and Equatorial Rossby Waves
            - 13.3b Differences between Rossby Waves and Equatorial Rossby Waves
            - 13.3c Applications of Rossby Waves and Equatorial Rossby Waves
    - '- Chapter 14: Rotating Waves in a Channel:':
        sections:
        - '- Section: 14.1 Rotating Shallow Water Equations:':
            subsections:
            - 14.1a How to Derive Rotating Shallow Water Equations
            - 14.1b Solutions to Rotating Shallow Water Equations
            - 14.1c Applications of Rotating Shallow Water Equations
        - '- Section: 14.2 Beta Effect and Channel Waves:':
            subsections:
            - 14.2a Definition of Beta Effect and Channel Waves
            - 14.2b Importance of Beta Effect and Channel Waves
            - 14.2c Applications of Beta Effect and Channel Waves
        - '- Section: 14.3 Eddy-Mean Flow Interactions:':
            subsections:
            - 14.3a How Eddies Interact with Mean Flow
            - 14.3b Effects of Eddy-Mean Flow Interactions on Wave Propagation
            - 14.3c Studies on Eddy-Mean Flow Interactions
    - '- Chapter 15: Leewaves in Compressible Fluid:':
        sections:
        - '- Section: 15.1 Introduction to Compressible Fluid Dynamics:':
            subsections:
            - 15.1a Definition of Compressible Fluid Dynamics
            - 15.1b Importance of Compressible Fluid Dynamics
            - 15.1c Applications of Compressible Fluid Dynamics
        - '- Section: 15.2 Mountain Lee Waves and Atmospheric Blocking:':
            subsections:
            - 15.2a How Mountain Lee Waves and Atmospheric Blocking Occur
            - 15.2b Effects of Mountain Lee Waves and Atmospheric Blocking on Weather
              Patterns
            - 15.2c Studies on Mountain Lee Waves and Atmospheric Blocking
        - '- Section: 15.3 Wave Breaking and Wave-Induced Turbulence:':
            subsections:
            - 15.3a How Wave Breaking and Wave-Induced Turbulence Occur
            - 15.3b Effects of Wave Breaking and Wave-Induced Turbulence on Ocean
              and Atmospheric Dynamics
            - 15.3c Recent Studies on Wave Breaking and Wave-Induced Turbulence
    - '- Chapter 16: Quasigeostrophy:':
        sections:
        - '- Section: 16.1 Quasigeostrophic Approximation:':
            subsections:
            - 16.1a Definition of Quasigeostrophic Approximation
            - 16.1b Importance of Quasigeostrophic Approximation
            - 16.1c Applications of Quasigeostrophic Approximation
        - '- Section: 16.2 Quasigeostrophic Equations and Conservation Laws:':
            subsections:
            - 16.2a How to Derive Quasigeostrophic Equations
            - 16.2b Conservation Laws in Quasigeostrophic Dynamics
            - 16.2c Applications of Quasigeostrophic Equations and Conservation Laws
        - '- Section: 16.3 Geostrophic Adjustment and Rossby Waves:':
            subsections:
            - 16.3a Definition of Geostrophic Adjustment and Rossby Waves
            - 16.3b Importance of Geostrophic Adjustment and Rossby Waves
            - 16.3c Applications of Geostrophic Adjustment and Rossby Waves
    - '- Chapter 17: WKB Approx. and Atmospheric Modes:':
        sections:
        - '- Section: 17.1 WKB Approximation and Its Applications:':
            subsections:
            - 17.1a Definition of WKB Approximation
            - 17.1b Importance of WKB Approximation
            - 17.1c Applications of WKB Approximation in Ocean and Atmospheric Studies
        - '- Section: 17.2 Atmospheric Modes and Wave Propagation:':
            subsections:
            - 17.2a Definition of Atmospheric Modes
            - 17.2b How Atmospheric Modes Affect Wave Propagation
            - 17.2c Studies on Atmospheric Modes and Wave Propagation
        - '- Section: 17.3 Wave-CISK (Convective Instability of the Second Kind):':
            subsections:
            - 17.3a Definition of Wave-CISK
            - 17.3b Importance of Wave-CISK in Atmospheric Dynamics
            - 17.3c Studies on Wave-CISK and Its Effects on Weather Patterns
    - '- Chapter 18: Eady Problem:':
        sections:
        - '- Section: 18.1 Introduction to the Eady Problem:':
            subsections:
            - 18.1a Definition of the Eady Problem
            - 18.1b Importance of the Eady Problem
            - 18.1c Applications of the Eady Problem in Ocean and Atmospheric Studies
        - '- Section: 18.2 Baroclinic Instability and Eady Waves:':
            subsections:
            - 18.2a Definition of Baroclinic Instability and Eady Waves
            - 18.2b How Baroclinic Instability and Eady Waves Affect Ocean and Atmospheric
              Dynamics
            - 18.2c Studies on Baroclinic Instability and Eady Waves
        - '- Section: 18.3 Eady Model and Storm Track Formation:':
            subsections:
            - 18.3a How the Eady Model Predicts Storm Track Formation
            - 18.3b Importance of the Eady Model in Weather Forecasting
            - 18.3c Recent Developments in the Eady Model and Storm Track Formation
    - '- Chapter 19: Pressure-like Coordinates:':
        sections:
        - '- Section: 19.1 Definition and Applications of Pressure-like Coordinates:':
            subsections:
            - 19.1a Definition of Pressure-like Coordinates
            - 19.1b Importance of Pressure-like Coordinates
            - 19.1c Applications of Pressure-like Coordinates in Ocean and Atmospheric
              Studies
        - '- Section: 19.2 Vertical Coordinate Systems:':
            subsections:
            - 19.2a Different Vertical Coordinate Systems Used in Ocean and Atmospheric
              Studies
            - 19.2b Importance of Choosing Appropriate Vertical Coordinate Systems
            - 19.2c Recent Developments in Vertical Coordinate Systems
        - '- Section: 19.3 Stacked Baroclinic Modes:':
            subsections:
            - 19.3a Definition of Stacked Baroclinic Modes
            - 19.3b Importance of Stacked Baroclinic Modes
            - 19.3c Applications of Stacked Baroclinic Modes in Ocean and Atmospheric
              Studies
    - '- Chapter 20: Surface':
        sections: []
