textbook:
  'Gaoming Studio - China":':
    chapters:
    - '- Chapter 1: Pre-semester Site Visit and Existing Context Analysis:':
        sections:
        - '- Section: 1.1 10 Day Site Visit to Gaoming, China:':
            subsections:
            - 1.1a Introduction to Gaoming
            - 1.1b Cultural and Historical Significance
            - 1.1c Study of Existing Infrastructure
            - 1.1d Analysis of Environmental Factors
            - 1.1e Observations and Initial Impressions
        - '- Section: 1.2 Present Initial Impressions and Ideas:':
            subsections:
            - 1.2a Presentation of Initial Impressions
            - 1.2b Brainstorming Session
            - 1.2c Identifying Key Issues and Challenges
            - 1.2d Generating Initial Ideas and Concepts
        - '- Section: 1.3 Gather Feedback:':
            subsections:
            - 1.3a Feedback from Peers and Instructors
            - 1.3b Expert Consultation and Review
            - 1.3c Incorporating Feedback into the Analysis
        - '- Section: 1.4 Develop an understanding of the existing context:':
            subsections:
            - 1.4a Socio-economic Analysis
            - 1.4b Demographic Study
            - 1.4c Urban Planning and Development
            - 1.4d Infrastructure Assessment
            - 1.4e Natural Environment Assessment
        - '- Section: 1.5 Research existing conditions:':
            subsections:
            - 1.5a Gathering Data and Information
            - 1.5b Analyzing Existing Policies and Regulations
            - 1.5c Case Studies of Similar Projects
            - 1.5d Reviewing Best Practices in Urban Design and Planning
    - '- Chapter 2: Best Practices Research:':
        sections:
        - '- Section: 2.1 Draft recommendations:':
            subsections:
            - 2.1a Identification of Key Challenges
            - 2.1b Review of Best Practices in Urban Design
            - 2.1c Developing Recommendations and Strategies
    - '- Chapter 3: Site Visit:':
        sections:
        - '- Section: 3.1 5 Day Site Visit to Gaoming:':
            subsections:
            - 3.1a Study of Site Specifics and Constraints
            - 3.1b Interaction with Local Stakeholders
            - 3.1c Assessment of Site Potential
        - '- Section: 3.2 Present ideas:':
            subsections:
            - 3.2a Presentation of Design Concepts
            - 3.2b Explanation of Design Rationale
            - 3.2c Addressing Feedback and Concerns
        - '- Section: 3.3 Gather feedback:':
            subsections:
            - 3.3a Feedback from Local Community
            - 3.3b Feedback from Experts and Professionals
            - 3.3c Incorporating Feedback into Design Concepts
        - '- Section: 3.4 Perform further site research:':
            subsections:
            - 3.4a Detailed Analysis of Site Conditions
            - 3.4b Environmental Impact Assessment
            - 3.4c Technical Feasibility Study
            - 3.4d Preliminary Cost Estimation
    - '- Chapter 4: Scenario Revisions:':
        sections:
        - '- Section: 4.1 Revise Draft Scenarios:':
            subsections:
            - 4.1a Analysis of Initial Scenarios
            - 4.1b Identifying Areas for Improvement
            - 4.1c Development of Revised Scenarios
        - '- Section: 4.2 Presentation:':
            subsections:
            - 4.2a Presentation of Revised Scenarios
            - 4.2b Explanation of Changes Made
            - 4.2c Addressing Questions and Concerns
    - '- Chapter 5: Final Report:':
        sections:
        - '- Section: 5.1 Small group collaboration:':
            subsections:
            - 5.1a Formation of Collaborative Teams
            - 5.1b Distribution of Tasks and Responsibilities
            - 5.1c Coordination and Communication
            - 5.1d Conflict Resolution within Teams
        - '- Section: 5.2 Development of recommendations:':
            subsections:
            - 5.2a Assessment of Design Options
            - 5.2b Selection of Preferred Design
            - 5.2c Detailed Design Development
            - 5.2d Integration of Stakeholder Feedback
            - 5.2e Preparation of Final Recommendations
        - '- Section: 5.3 Integration of water/hydrological factors into a modern city:':
            subsections:
            - 5.3a Study of Water Management Strategies
            - 5.3b Incorporating Sustainable Water Systems
            - 5.3c Designing Waterfront Development
        - '- Section: 5.4 Watershed and natural ecosystem protection:':
            subsections:
            - 5.4a Analysis of Watershed Characteristics
            - 5.4b Identification of Ecological Hotspots
            - 5.4c Designing Ecosystem Conservation Measures
        - '- Section: 5.5 Recreational activities:':
            subsections:
            - 5.5a Assessment of Recreational Needs
            - 5.5b Designing Parks and Public Spaces
            - 5.5c Planning for Sports and Leisure Facilities
        - '- Section: 5.6 Housing:':
            subsections:
            - 5.6a Housing Demand Analysis
            - 5.6b Designing Affordable Housing Solutions
            - 5.6c Planning for Mixed-Use Developments
        - '- Section: 5.7 Transportation:':
            subsections:
            - 5.7a Evaluation of Existing Transportation Systems
            - 5.7b Designing Efficient and Sustainable Transportation Networks
            - 5.7c Integrating Public Transport and Non-Motorized Modes
        - '- Section: 5.8 Tourism:':
            subsections:
            - 5.8a Analysis of Tourism Potential
            - 5.8b Designing Tourist Attractions and Landmarks
            - 5.8c Planning for Cultural and Heritage Tourism
    - '- Chapter 6: Project Exhibition:':
        sections:
        - '- Section: 6.1 Display of final report:':
            subsections:
            - 6.1a Designing an Engaging Exhibition Space
            - 6.1b Preparation of Visual Displays
            - 6.1c Interaction with Exhibition Visitors
        - '- Section: 6.2 Presentation of findings:':
            subsections:
            - 6.2a Oral Presentation of Project Findings
            - 6.2b Visual Presentation Aids and Tools
            - 6.2c Addressing Questions and Feedback
        - '- Section: 6.3 Client interaction:':
            subsections:
            - 6.3a Building Rapport with Clients
            - 6.3b Understanding Client Expectations
            - 6.3c Effective Communication with Clients
            - 6.3d Incorporating Client Feedback in Final Report
        - '- Section: 6.4 Copyright concerns:':
            subsections:
            - 6.4a Understanding Intellectual Property Rights
            - 6.4b Copyright Protection for Design Works
            - 6.4c Fair Use and Attribution Guidelines
            - 6.4d Addressing Copyright Infringement Concerns
        - '- Section: 6.5 Image removal:':
            subsections:
            - 6.5a Assessment of Image Usage Rights
            - 6.5b Obtaining Proper Image Licenses
            - 6.5c Image Removal Procedures
            - 6.5d Replacing Removed Images with Licensed Alternatives
        - '- Section: 6.6 Student content retention:':
            subsections:
            - 6.6a Ownership of Student Works
            - 6.6b Retention and Archiving of Student Works
            - 6.6c Student Consent and Permissions
            - 6.6d Data Protection and Privacy Considerations
        - '- Section: 6.7 Permission usage:':
            subsections:
            - 6.7a Obtaining Permissions for External Content
            - 6.7b Proper Attribution and Acknowledgment
            - 6.7c Compliance with Usage Guidelines
            - 6.7d Documenting Permissions for Future Reference
        - '- Section: 6.8 Acknowledgment of student contributors:':
            subsections:
            - 6.8a Recognition of Student Contributions
            - 6.8b Acknowledgment in Final Report and Exhibition
            - 6.8c Awards and Prizes for Outstanding Contributions
        - '- Section: 6.9 Student names:':
            subsections:
            - 6.9a Handling and Protection of Student Personal Information
            - 6.9b Privacy Laws and Regulations
            - 6.9c Anonymity and Pseudonyms
    - '- Chapter 7: Project Planning and Management:':
        sections:
        - '- Section: 7.1 Project Timeline and Milestones:':
            subsections:
            - 7.1a Developing a Project Timeline
            - 7.1b Setting Project Milestones
            - 7.1c Monitoring Project Progress
            - 7.1d Adjusting the Project Plan as Needed
        - '- Section: 7.2 Resource Management:':
            subsections:
            - 7.2a Identifying Required Resources
            - 7.2b Allocating Resources Effectively
            - 7.2c Managing Resource Constraints
            - 7.2d Optimizing Resource Use
        - '- Section: 7.3 Risk Management:':
            subsections:
            - 7.3a Identifying Potential Risks
            - 7.3b Assessing Risk Impact and Probability
            - 7.3c Developing Risk Mitigation Strategies
            - 7.3d Monitoring and Controlling Risks
        - '- Section: 7.4 Stakeholder Management:':
            subsections:
            - 7.4a Identifying Key Stakeholders
            - 7.4b Understanding Stakeholder Expectations
            - 7.4c Engaging Stakeholders in the Project
            - 7.4d Managing Stakeholder Communication
    - '- Chapter 8: Design Principles and Guidelines:':
        sections:
        - '- Section: 8.1 Urban Design Principles:':
            subsections:
            - 8.1a Understanding Urban Design Principles
            - 8.1b Applying Urban Design Principles in the Project
            - 8.1c Evaluating Design Solutions Based on Principles
            - 8.1d Refining Design Solutions
        - '- Section: 8.2 Sustainable Design Guidelines:':
            subsections:
            - 8.2a Understanding Sustainable Design Guidelines
            - 8.2b Incorporating Sustainability in Design Solutions
            - 8.2c Evaluating Sustainability of Design Solutions
            - 8.2d Refining Design Solutions for Sustainability
        - '- Section: 8.3 Accessibility Guidelines:':
            subsections:
            - 8.3a Understanding Accessibility Guidelines
            - 8.3b Incorporating Accessibility in Design Solutions
            - 8.3c Evaluating Accessibility of Design Solutions
            - 8.3d Refining Design Solutions for Accessibility
        - '- Section: 8.4 Aesthetic Guidelines:':
            subsections:
            - 8.4a Understanding Aesthetic Guidelines
            - 8.4b Incorporating Aesthetics in Design Solutions
            - 8.4c Evaluating Aesthetic Appeal of Design Solutions
            - 8.4d Refining Design Solutions for Aesthetics
    - '- Chapter 9: Design Development and Refinement:':
        sections:
        - '- Section: 9.1 Conceptual Design Development:':
            subsections:
            - 9.1a Developing Initial Design Concepts
            - 9.1b Evaluating and Selecting Design Concepts
            - 9.1c Refining Selected Design Concepts
            - 9.1d Presenting Design Concepts for Feedback
        - '- Section: 9.2 Detailed Design Development:':
            subsections:
            - 9.2a Developing Detailed Design Solutions
            - 9.2b Evaluating and Refining Design Solutions
            - 9.2c Preparing Design Documentation
            - 9.2d Presenting Design Solutions for Approval
        - '- Section: 9.3 Design Review and Approval:':
            subsections:
            - 9.3a Conducting Design Reviews
            - 9.3b Incorporating Feedback into Design Solutions
            - 9.3c Seeking Approval for Design Solutions
            - 9.3d Finalizing Design Solutions for Implementation
        - '- Section: 9.4 Design Implementation Planning:':
            subsections:
            - 9.4a Planning for Design Implementation
            - 9.4b Coordinating with Implementation Teams
            - 9.4c Preparing Implementation Documentation
            - 9.4d Monitoring Design Implementation
    - '- Chapter 10: Project Evaluation and Closure:':
        sections:
        - '- Section: 10.1 Project Performance Evaluation:':
            subsections:
            - 10.1a Conducting Project Performance Evaluation
            - 10.1b Analyzing Project Results and Outcomes
            - 10.1c Identifying Lessons Learned
            - 10.1d Preparing Project Evaluation Report
        - '- Section: 10.2 Project Closure:':
            subsections:
            - 10.2a Completing Project Deliverables
            - 10.2b Conducting Project Closure Meeting
            - 10.2c Documenting Project Closure
            - 10.2d Celebrating Project Success
        - '- Section: 10.3 Post-Project Review:':
            subsections:
            - 10.3a Conducting Post-Project Review
            - 10.3b Analyzing Post-Project Feedback
            - 10.3c Identifying Opportunities for Improvement
            - 10.3d Documenting Post-Project Review Findings
        - '- Section: 10.4 Project Archiving:':
            subsections:
            - 10.4a Archiving Project Documentation
            - 10.4b Preserving Project Artifacts
            - 10.4c Updating Project Management Knowledge Base
            - 10.4d Sharing Project Experience and Knowledge
    - '- Chapter 11: Professional Development and Learning:':
        sections:
        - '- Section: 11.1 Professional Skills Development:':
            subsections:
            - 11.1a Identifying Professional Skills Gaps
            - 11.1b Developing Professional Skills
            - 11.1c Applying Professional Skills in the Project
            - 11.1d Reflecting on Professional Skills Development
        - '- Section: 11.2 Learning from the Project:':
            subsections:
            - 11.2a Reflecting on Project Experience
            - 11.2b Identifying Learning Opportunities
            - 11.2c Applying Learning in Future Projects
            - 11.2d Sharing Learning with Peers
        - '- Section: 11.3 Career Development:':
            subsections:
            - 11.3a Reflecting on Career Goals
            - 11.3b Identifying Career Development Opportunities
            - 11.3c Planning for Career Development
            - 11.3d Seeking Career Advice and Guidance
        - '- Section: 11.4 Professional Networking:':
            subsections:
            - 11.4a Building Professional Relationships
            - 11.4b Participating in Professional Networking Events
            - 11.4c Leveraging Professional Networks for Career Development
            - 11.4d Maintaining Professional Networks
    - '- Chapter 12: Community Engagement and Impact:':
        sections:
        - '- Section: 12.1 Community Engagement:':
            subsections:
            - 12.1a Understanding Community Needs and Expectations
            - 12.1b Engaging Community in the Project
            - 12.1c Incorporating Community Feedback in the Project
            - 12.1d Building Strong Community Relationships
        - '- Section: 12.2 Social Impact of the Project:':
            subsections:
            - 12.2a Assessing Social Impact of the Project
            - 12.2b Maximizing Positive Social Impact
            - 12.2c Mitigating Negative Social Impact
            - 12.2d Communicating Social Impact to Stakeholders
        - '- Section: 12.3 Economic Impact of the Project:':
            subsections:
            - 12.3a Assessing Economic Impact of the Project
            - 12.3b Maximizing Economic Benefits
            - 12.3c Mitigating Economic Risks
            - 12.3d Communicating Economic Impact to Stakeholders
        - '- Section: 12.4 Environmental Impact of the Project:':
            subsections:
            - 12.4a Assessing Environmental Impact of the Project
            - 12.4b Maximizing Environmental Benefits
            - 12.4c Mitigating Environmental Risks
            - 12.4d Communicating Environmental Impact to Stakeholders
    - '- Chapter 13: Ethics and Professional Conduct:':
        sections:
        - '- Section: 13.1 Understanding Professional Ethics:':
            subsections:
            - 13.1a Understanding Ethical Principles and Standards
            - 13.1b Applying Ethics in Professional Practice
            - 13.1c Dealing with Ethical Dilemmas
            - 13.1d Promoting Ethical Conduct in the Project
        - '- Section: 13.2 Responsible':
            subsections: []
