textbook:
  'Science and Policy of Natural Hazards: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: Introduction:':
        sections:
        - '- Section: 1.1 Earthquakes:':
            subsections:
            - 1.1a Seismic waves
            - 1.1b Earthquake kinematics
            - 1.1c Earthquake dynamics
            - '1.1d Associated phenomena: Tsunami'
            - 1.1e Earthquake preparedness and warning systems
        - '- Section: 1.2 Hurricanes:':
            subsections:
            - 1.2a Tropical cyclones
            - '1.2b The tropical atmosphere: Hurricane incubator'
            - 1.2c Computational models of hurricanes
        - '- Section: 1.3 Volcanoes:':
            subsections:
            - 1.3a Volcano overview
            - 1.3b Magma generation
            - 1.3c Magma ascent and eruption
            - 1.3d Volcanic hazards
            - 1.3e Volcano hazards
        - '- Section: 1.4 Tornadoes:':
            subsections:
            - 1.4a Tornado overview
            - 1.4b Moist convection
            - 1.4c Stability assessment
            - 1.4d Thunderstorms
            - 1.4e Mesoscale organization of convection
            - 1.4f Supercells and tornadoes
            - 1.4g Forecasting tornadoes
        - '- Section: 1.5 Term Project:':
            subsections:
            - 1.5a Purpose of the project
            - 1.5b Scientific skills required
            - 1.5c Hazard assessment
            - 1.5d Location selection
            - 1.5e Communication of scientific information
