textbook:
  'Comprehensive Guide to Healthy Cities: Assessing Health Impacts of Policies and Plans":':
    chapters:
    - '- Chapter 1: Introduction to Healthy Cities:':
        sections:
        - '- Section: 1.1 Course description':
            subsections: []
        - '- Section: 1.2 Understanding the Social Determinants of Health':
            subsections: []
        - '- Section: 1.3 Introduction to Rapid Health Impact Assessment (HIA) for Clients':
            subsections: []
    - '- Chapter 2: Major Health Challenges:':
        sections:
        - '- Section: 2.1 A Synopsis of Mortality and Morbidity Domestically and Abroad':
            subsections: []
        - '- Section: 2.2 Contrasting Perspectives on Health and Disease: A Global Perspective':
            subsections: []
        - '- Section: 2.3 The Interplay of Social Factors in Health Inequities':
            subsections: []
    - '- Chapter 3: Rapid HIA:':
        sections:
        - '- Section: 3.1 Training for Effective Rapid Health Impact Assessment':
            subsections: []
    - '- Chapter 4: Health Disparities:':
        sections:
        - '- Section: 4.1 Measurement, Definition, Monitoring, and Tracking of Health Disparities':
            subsections: []
        - '- Section: 4.2 Inequity versus Inequality: Understanding the Difference and Implications':
            subsections: []
        - '- Section: 4.3 Arguments for and Against a Focus on Narrowing Gaps in Health':
            subsections: []
        - '- Section: 4.4 Strategies for Addressing Health Disparities in Urban Settings':
            subsections: []
    - '- Chapter 5: HIA Assessment:':
        sections:
        - '- Section: 5.1 Introduction to Health Impact Assessment (HIA)':
            subsections: []
        - '- Section: 5.2 Key Steps and Components of a Comprehensive HIA':
            subsections: []
        - '- Section: 5.3 Best Practices for Implementing HIA in Policy and Planning':
            subsections: []
    - '- Chapter 6: Criminal Justice System:':
        sections:
        - '- Section: 6.1 Overview of the Criminal Justice System and Its Impacts on Health':
            subsections: []
        - '- Section: 6.2 Addressing Health Disparities in the Criminal Justice System':
            subsections: []
        - '- Section: 6.3 Promoting Health and Well-being in Correctional Facilities':
            subsections: []
    - '- Chapter 7: Pathway Presentations:':
        sections:
        - ? '- Section: 7.1 Presentation of Pathway Diagrams Demonstrating Links between
            Proposed Policies, Programs, or Projects, and Health Impacts'
          : subsections: []
        - '- Section: 7.2 Analyzing Pathways for Health Equity: Methods and Case Studies':
            subsections: []
    - '- Chapter 8: HIA Assessment Workshop:':
        sections:
        - '- Section: 8.1 Health Impact Assessment of Record Expungement Policies':
            subsections: []
        - '- Section: 8.2 Assessing Health Impacts of Just Cause for Eviction Policies':
            subsections: []
        - '- Section: 8.3 Workshop Exercises and Case Studies':
            subsections: []
    - '- Chapter 9: Final HIA Presentations with Clients:':
        sections:
        - '- Section: 9.1 Presentation of Final HIA Results and Recommendations to Clients':
            subsections: []
        - '- Section: 9.2 Collaborating with Stakeholders for Effective Implementation of HIA Recommendations':
            subsections: []
        - '- Section: 9.3 Evaluating the Impact of HIA on Policy and Planning Processes':
            subsections: []
    - '- Chapter 10: Health Impact Assessment Methodologies:':
        sections:
        - '- Section: 10.1 Introduction to HIA Methodologies':
            subsections: []
        - '- Section: 10.2 Quantitative and Qualitative Approaches':
            subsections: []
        - '- Section: 10.3 Case Studies and Examples':
            subsections: []
    - '- Chapter 11: Health Equity and Social Justice:':
        sections:
        - '- Section: 11.1 Understanding Health Equity':
            subsections: []
        - '- Section: 11.2 Social Determinants of Health Equity':
            subsections: []
        - '- Section: 11.3 Strategies for Promoting Health Equity':
            subsections: []
    - '- Chapter 12: Urban Planning and Health:':
        sections:
        - '- Section: 12.1 The Role of Urban Planning in Health':
            subsections: []
        - '- Section: 12.2 Health Impacts of Urban Design':
            subsections: []
        - '- Section: 12.3 Case Studies in Healthy Urban Planning':
            subsections: []
    - '- Chapter 13: Environmental Health:':
        sections:
        - '- Section: 13.1 Introduction to Environmental Health':
            subsections: []
        - '- Section: 13.2 Environmental Factors and Health Outcomes':
            subsections: []
        - '- Section: 13.3 Strategies for Promoting Environmental Health':
            subsections: []
    - '- Chapter 14: Health Promotion and Disease Prevention:':
        sections:
        - '- Section: 14.1 Understanding Health Promotion':
            subsections: []
        - '- Section: 14.2 Strategies for Disease Prevention':
            subsections: []
        - '- Section: 14.3 Case Studies in Health Promotion and Disease Prevention':
            subsections: []
    - '- Chapter 15: Health Policy and Advocacy:':
        sections:
        - '- Section: 15.1 Introduction to Health Policy':
            subsections: []
        - '- Section: 15.2 The Role of Advocacy in Health Policy':
            subsections: []
        - '- Section: 15.3 Case Studies in Health Policy and Advocacy':
            subsections: []
    - '- Chapter 16: Community Engagement in Health:':
        sections:
        - '- Section: 16.1 Understanding Community Engagement':
            subsections: []
        - '- Section: 16.2 Strategies for Effective Community Engagement':
            subsections: []
        - '- Section: 16.3 Case Studies in Community Engagement':
            subsections: []
    - '- Chapter 17: Health Communication:':
        sections:
        - '- Section: 17.1 Introduction to Health Communication':
            subsections: []
        - '- Section: 17.2 Strategies for Effective Health Communication':
            subsections: []
        - '- Section: 17.3 Case Studies in Health Communication':
            subsections: []
    - '- Chapter 18: Health Literacy:':
        sections:
        - '- Section: 18.1 Understanding Health Literacy':
            subsections: []
        - '- Section: 18.2 The Role of Health Literacy in Health Outcomes':
            subsections: []
        - '- Section: 18.3 Strategies for Promoting Health Literacy':
            subsections: []
    - '- Chapter 19: Health Financing:':
        sections:
        - '- Section: 19.1 Introduction to Health Financing':
            subsections: []
        - '- Section: 19.2 The Role of Health Financing in Health Outcomes':
            subsections: []
        - '- Section: 19.3 Case Studies in Health Financing':
            subsections: []
    - '- Chapter 20: Global Health:':
        sections:
        - '- Section: 20.1 Understanding Global Health':
            subsections: []
        - '- Section: 20.2 Major Challenges in Global Health':
            subsections: []
        - '- Section: 20.3 Strategies for Addressing Global Health Challenges':
            subsections: []
