textbook:
  'Computer Systems Security: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: Introduction to Computer Systems Security:':
        sections:
        - '- Section: 1.1 What is Computer Systems Security?:':
            subsections:
            - 1.1a Definition of Computer Systems Security
            - 1.1b Importance of Computer Systems Security
            - 1.1c Evolution of Computer Systems Security
            - 1.1d Current Challenges in Computer Systems Security
    - '- Chapter 2: Threat Models:':
        sections:
        - '- Section: 2.1 Introduction to Threat Models:':
            subsections:
            - 2.1a Understanding Threat Models
            - 2.1b Types of Threats and Attackers
            - 2.1c Security Models and Frameworks
    - '- Chapter 3: Control Hijacking Attacks:':
        sections:
        - '- Section: 3.1 Buffer Overflow Attacks:':
            subsections:
            - 3.1a Understanding Buffer Overflow Attacks
            - 3.1b Return-Oriented Programming (ROP)
            - 3.1c Control Flow Integrity (CFI)
    - '- Chapter 4: Buffer Overflow Exploits and Defenses:':
        sections:
        - '- Section: 4.1 Stack-based Buffer Overflows:':
            subsections:
            - 4.1a Understanding Stack-based Buffer Overflows
            - 4.1b Heap-based Buffer Overflows
            - 4.1c Return-to-libc Attacks
            - 4.1d Address Space Layout Randomization (ASLR)
            - 4.1e Data Execution Prevention (DEP)
            - 4.1f Stack Canaries and Guard Pages
    - '- Chapter 5: Privilege Separation:':
        sections:
        - '- Section: 5.1 User and Kernel Mode:':
            subsections:
            - 5.1a Understanding User and Kernel Mode
            - 5.1b Process Isolation
            - 5.1c Privilege Escalation
            - 5.1d Mandatory Access Control (MAC)
    - '- Chapter 6: Capabilities:':
        sections:
        - '- Section: 6.1 Principle of Least Privilege:':
            subsections:
            - 6.1a Understanding the Principle of Least Privilege
            - 6.1b Capability-based Security
            - 6.1c Domain and Object Capabilities
            - 6.1d Capability-based Systems
    - '- Chapter 7: Sandboxing Native Code:':
        sections:
        - '- Section: 7.1 Native Code Execution Risks:':
            subsections:
            - 7.1a Understanding Native Code Execution Risks
            - 7.1b Sandboxing Techniques
            - 7.1c Address Space Layout Randomization (ASLR)
            - 7.1d Just-In-Time (JIT) Compilation
            - 7.1e Code Signing and Verification
    - '- Chapter 8: Web Security Model:':
        sections:
        - '- Section: 8.1 Web Application Architecture:':
            subsections:
            - 8.1a Understanding Web Application Architecture
            - 8.1b Same-Origin Policy (SOP)
            - 8.1c Cross-Site Scripting (XSS)
            - 8.1d Cross-Site Request Forgery (CSRF)
            - 8.1e Clickjacking
            - 8.1f Content Security Policy (CSP)
    - '- Chapter 9: Securing Web Applications:':
        sections:
        - '- Section: 9.1 Input Validation and Sanitization:':
            subsections:
            - 9.1a Understanding Input Validation and Sanitization
            - 9.1b Session Management
            - 9.1c Authentication and Authorization
            - 9.1d Secure Communication (HTTPS)
            - 9.1e Secure Coding Practices
            - 9.1f Web Application Firewalls (WAF)
    - '- Chapter 10: Symbolic Execution:':
        sections:
        - '- Section: 10.1 Program Analysis Techniques:':
            subsections:
            - 10.1a Understanding Program Analysis Techniques
            - 10.1b Symbolic Execution Basics
            - 10.1c Path Conditions and Constraints
            - 10.1d Constraint Solvers
            - 10.1e Dynamic Symbolic Execution
            - 10.1f Concolic Testing
    - '- Chapter 11: Ur / Web:':
        sections:
        - '- Section: 11.1 Web Programming with Ur / Web:':
            subsections:
            - 11.1a Understanding Web Programming with Ur / Web
            - 11.1b Security Features in Ur / Web
            - 11.1c Web Application Development Workflow
            - 11.1d Web Application Testing and Debugging
            - 11.1e Web Application Security Best Practices
    - '- Chapter 12: Network Security:':
        sections:
        - '- Section: 12.1 Network Threats and Vulnerabilities:':
            subsections:
            - 12.1a Understanding Network Threats and Vulnerabilities
            - 12.1b Network Security Protocols
            - 12.1c Secure Network Design Principles
            - 12.1d Intrusion Detection and Prevention Systems (IDS/IPS)
            - 12.1e Virtual Private Networks (VPNs)
            - 12.1f Network Access Control (NAC)
    - '- Chapter 13: Network Protocols:':
        sections:
        - '- Section: 13.1 Internet Protocol Suite (TCP/IP):':
            subsections:
            - 13.1a Understanding the Internet Protocol Suite (TCP/IP)
            - 13.1b Network Address Translation (NAT)
            - 13.1c Domain Name System (DNS)
            - 13.1d Dynamic Host Configuration Protocol (DHCP)
            - 13.1e Simple Mail Transfer Protocol (SMTP)
            - 13.1f Secure Shell (SSH)
    - '- Chapter 14: SSL and HTTPS:':
        sections:
        - '- Section: 14.1 Secure Sockets Layer (SSL):':
            subsections:
            - 14.1a Understanding Secure Sockets Layer (SSL)
            - 14.1b Transport Layer Security (TLS)
            - 14.1c Public Key Infrastructure (PKI)
            - 14.1d Certificate Authorities (CAs)
            - 14.1e HTTPS Protocol and Implementation
            - 14.1f SSL/TLS Vulnerabilities and Attacks
    - '- Chapter 15: Medical Software:':
        sections:
        - '- Section: 15.1 Security Challenges in Medical Software:':
            subsections:
            - 15.1a Understanding Security Challenges in Medical Software
            - 15.1b Privacy and Confidentiality in Health Information Systems
            - 15.1c Medical Device Security
            - 15.1d Electronic Health Records (EHRs)
            - 15.1e Health Information Exchange (HIE)
            - 15.1f Regulatory Compliance (HIPAA, GDPR)
    - '- Chapter 16: Side-Channel Attacks:':
        sections:
        - '- Section: 16.1 Side-Channel Information Leakage:':
            subsections:
            - 16.1a Understanding Side-Channel Information Leakage
            - 16.1b Timing Attacks
            - 16.1c Power Analysis Attacks
            - 16.1d Electromagnetic Emanation Attacks
            - 16.1e Fault Injection Attacks
            - 16.1f Countermeasures and Mitigation Techniques
    - '- Chapter 17: User Authentication:':
        sections:
        - '- Section: 17.1 Password-based Authentication:':
            subsections:
            - 17.1a Understanding Password-based Authentication
            - 17.1b Biometric Authentication
            - 17.1c Multi-factor Authentication
            - 17.1d Single Sign-On (SSO)
            - 17.1e Token-based Authentication
            - 17.1f Authentication Protocols (OAuth, OpenID)
    - '- Chapter 18: Private Browsing:':
        sections:
        - '- Section: 18.1 Browser Privacy Features:':
            subsections:
            - 18.1a Understanding Browser Privacy Features
            - 18.1b Private Browsing Modes
            - 18.1c Tracking Protection
            - 18.1d Incognito Mode
            - 18.1e Privacy Threats and Risks
            - 18.1f Privacy-enhancing Technologies
    - '- Chapter 19: Anonymous Communication:':
        sections:
        - '- Section: 19.1 Anonymity and Pseudonymity:':
            subsections:
            - 19.1a Understanding Anonymity and Pseudonymity
            - 19.1b Onion Routing (Tor)
            - 19.1c Mix Networks
            - 19.1d Decentralized Anonymous Communication
            - 19.1e Anonymous Messaging Protocols
            - 19.1f Anonymity Attacks and Defenses
    - '- Chapter 20: Mobile Phone Security:':
        sections:
        - '- Section: 20.1 Mobile Operating Systems Security:':
            subsections:
            - 20.1a Understanding Mobile Operating Systems Security
            - 20.1b App Permissions and Privacy
            - 20.1c Mobile Device Management (MDM)
            - 20.1d Mobile Malware and Exploits
            - 20.1e Secure Mobile App Development
            - 20.1f Mobile Payment Security
    - '- Chapter 21: Data Tracking:':
        sections:
        - '- Section: 21.1 Online Tracking Technologies:':
            subsections:
            - 21.1a Understanding Online Tracking Technologies
            - 21.1b Web Browser Fingerprinting
            - 21.1c Mobile Device Tracking
            - 21.1d Behavioral Tracking and Profiling
            - 21.1e Privacy Laws and Regulations
            - 21.1f Privacy-enhancing Tools and Techniques
    - '- Chapter 22: Security Economics:':
        sections:
        - '- Section: 22.1 Economic Incentives in Cybersecurity:':
            subsections:
            - 22.1a Understanding Economic Incentives in Cybersecurity
            - 22.1b Cost-Benefit Analysis of Security Measures
            - 22.1c Risk Management and Insurance
            - 22.1d Security Investments and Returns
            - 22.1e Cybersecurity Markets and Industry
            - 22.1f Cybersecurity Policy and Regulation
    - '- Chapter 23: Project Presentations:':
        sections:
        - '- Section: 23.1 Final Project Presentations:':
            subsections:
            - 23.1a Understanding Final Project Presentations
            - 23.1b Project Demonstrations and Evaluations
            - 23.1c Peer Feedback and Evaluation
            - 23.1d Lessons Learned and Best Practices
