textbook:
  'The Power of Place: Media Technology, Youth, and City Design and Development":':
    chapters:
    - '- Chapter 1: Prologue: Gateway to an Unfolding Project:':
        sections:
        - '- Section: 1.1 Introduction to the West Philadelphia Landscape Project:':
            subsections:
            - 1.1a Understanding the Landscape
            - 1.1b Role of Youth in the Project
            - 1.1c Project Goals and Objectives
    - '- Chapter 2: Frameworks for Action: Water, Infrastructure, Architecture, People:':
        sections:
        - '- Section: 2.1 Understanding the Neighborhood:':
            subsections:
            - 2.1a Neighborhood Demographics
            - 2.1b Neighborhood History
            - 2.1c Neighborhood Challenges
        - '- Section: 2.2 Tracing the Past, Envisioning the Future: Historical Context for Projects:':
            subsections:
            - 2.2a Historical Analysis
            - 2.2b Future Vision
            - 2.2c Role of Media Technology
        - '- Section: 2.3 The Internet and Community Design and Development:':
            subsections:
            - 2.3a Role of the Internet
            - 2.3b Community Engagement through the Internet
            - 2.3c Case Studies
    - '- Chapter 3: Proposals for Projects Due: Presentation and Discussion:':
        sections:
        - '- Section: 3.1 Revised Proposals Due:':
            subsections:
            - 3.1a Proposal Writing
            - 3.1b Proposal Review
            - 3.1c Proposal Revision
        - '- Section: 3.2 Determine Class Topics:':
            subsections:
            - 3.2a Topic Selection
            - 3.2b Topic Discussion
            - 3.2c Topic Implementation
    - '- Chapter 4: Field Trip to Philadelphia:':
        sections:
        - '- Section: 4.1 Work with Sulzberger students:':
            subsections:
            - 4.1a Preparing for the Field Trip
            - 4.1b Collaborative Work with Students
            - 4.1c Post-Trip Reflections
    - '- Chapter 5: Work on Projects:':
        sections:
        - '- Section: 5.1 Finishing Projects:':
            subsections:
            - 5.1a Project Completion
            - 5.1b Project Presentation
            - 5.1c Project Evaluation
        - '- Section: 5.2 Reflecting on Projects:':
            subsections:
            - 5.2a Reflection Process
            - 5.2b Lessons Learned
            - 5.2c Future Implications
        - '- Section: 5.3 Discussion:':
            subsections:
            - 5.3a Group Discussion
            - 5.3b Individual Reflections
            - 5.3c Action Steps
    - '- Chapter 6: Various Projects:':
        sections:
        - '- Section: 6.1 Searching Out the Lines - Christine Gaspar:':
            subsections:
            - 6.1a Project Overview
            - 6.1b Project Implementation
            - 6.1c Project Outcomes
        - '- Section: 6.2 Revealing and Creating - Tracy Taylor:':
            subsections:
            - 6.2a Project Overview
            - 6.2b Project Implementation
            - 6.2c Project Outcomes
    - '- Chapter 7: The Power of Place:':
        sections:
        - '- Section: 7.1 Understanding Place:':
            subsections:
            - 7.1a Definition of Place
            - 7.1b Importance of Place
            - 7.1c Place and Identity
        - '- Section: 7.2 Place and Community Development:':
            subsections:
            - 7.2a Role of Place in Development
            - 7.2b Community Engagement in Place
            - 7.2c Case Studies of Place-Based Development
        - '- Section: 7.3 Media Technology and Place:':
            subsections:
            - 7.3a Role of Media Technology
            - 7.3b Media Technology and Community Engagement
            - 7.3c Case Studies of Media Technology in Place-Based Development
    - '- Chapter 8: Youth Engagement in City Design and Development:':
        sections:
        - '- Section: 8.1 Understanding Youth Engagement:':
            subsections:
            - 8.1a Definition of Youth Engagement
            - 8.1b Importance of Youth Engagement
            - 8.1c Challenges in Youth Engagement
        - '- Section: 8.2 Youth Engagement in City Design:':
            subsections:
            - 8.2a Role of Youth in City Design
            - 8.2b Case Studies of Youth Engagement in City Design
            - 8.2c Future Implications of Youth Engagement in City Design
        - '- Section: 8.3 Youth Engagement in City Development:':
            subsections:
            - 8.3a Role of Youth in City Development
            - 8.3b Case Studies of Youth Engagement in City Development
            - 8.3c Future Implications of Youth Engagement in City Development
    - '- Chapter 9: The Role of the Internet in Community Design and Development:':
        sections:
        - '- Section: 9.1 Understanding the Role of the Internet:':
            subsections:
            - 9.1a Definition of the Internet
            - 9.1b Importance of the Internet in Community Design and Development
            - 9.1c Challenges in Using the Internet for Community Design and Development
        - '- Section: 9.2 The Internet and Community Design:':
            subsections:
            - 9.2a Role of the Internet in Community Design
            - 9.2b Case Studies of the Internet in Community Design
            - 9.2c Future Implications of the Internet in Community Design
        - '- Section: 9.3 The Internet and Community Development:':
            subsections:
            - 9.3a Role of the Internet in Community Development
            - 9.3b Case Studies of the Internet in Community Development
            - 9.3c Future Implications of the Internet in Community Development
    - '- Chapter 10: The Power of Media Technology in City Design and Development:':
        sections:
        - '- Section: 10.1 Understanding the Role of Media Technology:':
            subsections:
            - 10.1a Definition of Media Technology
            - 10.1b Importance of Media Technology in City Design and Development
            - 10.1c Challenges in Using Media Technology for City Design and Development
        - '- Section: 10.2 Media Technology and City Design:':
            subsections:
            - 10.2a Role of Media Technology in City Design
            - 10.2b Case Studies of Media Technology in City Design
            - 10.2c Future Implications of Media Technology in City Design
        - '- Section: 10.3 Media Technology and City Development:':
            subsections:
            - 10.3a Role of Media Technology in City Development
            - 10.3b Case Studies of Media Technology in City Development
            - 10.3c Future Implications of Media Technology in City Development
    - '- Chapter 11: The Role of Youth in City Design and Development:':
        sections:
        - '- Section: 11.1 Understanding the Role of Youth:':
            subsections:
            - 11.1a Definition of Youth
            - 11.1b Importance of Youth in City Design and Development
            - 11.1c Challenges in Engaging Youth in City Design and Development
        - '- Section: 11.2 Youth and City Design:':
            subsections:
            - 11.2a Role of Youth in City Design
            - 11.2b Case Studies of Youth in City Design
            - 11.2c Future Implications of Youth in City Design
        - '- Section: 11.3 Youth and City Development:':
            subsections:
            - 11.3a Role of Youth in City Development
            - 11.3b Case Studies of Youth in City Development
            - 11.3c Future Implications of Youth in City Development
    - '- Chapter 12: The Power of Place in City Design and Development:':
        sections:
        - '- Section: 12.1 Understanding the Power of Place:':
            subsections:
            - 12.1a Definition of Place
            - 12.1b Importance of Place in City Design and Development
            - 12.1c Challenges in Using Place for City Design and Development
        - '- Section: 12.2 Place and City Design:':
            subsections:
            - 12.2a Role of Place in City Design
            - 12.2b Case Studies of Place in City Design
            - 12.2c Future Implications of Place in City Design
        - '- Section: 12.3 Place and City Development:':
            subsections:
            - 12.3a Role of Place in City Development
            - 12.3b Case Studies of Place in City Development
            - 12.3c Future Implications of Place in City Development
    - '- Chapter 13: The Role of the Internet in City Design and Development:':
        sections:
        - '- Section: 13.1 Understanding the Role of the Internet:':
            subsections:
            - 13.1a Definition of the Internet
            - 13.1b Importance of the Internet in City Design and Development
            - 13.1c Challenges in Using the Internet for City Design and Development
        - '- Section: 13.2 The Internet and City Design:':
            subsections:
            - 13.2a Role of the Internet in City Design
            - 13.2b Case Studies of the Internet in City Design
            - 13.2c Future Implications of the Internet in City Design
        - '- Section: 13.3 The Internet and City Development:':
            subsections:
            - 13.3a Role of the Internet in City Development
            - 13.3b Case Studies of the Internet in City Development
            - 13.3c Future Implications of the Internet in City Development
    - '- Chapter 14: The Power of Media Technology in City Design and Development:':
        sections:
        - '- Section: 14.1 Understanding the Power of Media Technology:':
            subsections:
            - 14.1a Definition of Media Technology
            - 14.1b Importance of Media Technology in City Design and Development
            - 14.1c Challenges in Using Media Technology for City Design and Development
        - '- Section: 14.2 Media Technology and City Design:':
            subsections:
            - 14.2a Role of Media Technology in City Design
            - 14.2b Case Studies of Media Technology in City Design
            - 14.2c Future Implications of Media Technology in City Design
        - '- Section: 14.3 Media Technology and City Development:':
            subsections:
            - 14.3a Role of Media Technology in City Development
            - 14.3b Case Studies of Media Technology in City Development
            - 14.3c Future Implications of Media Technology in City Development
    - '- Chapter 15: The Role of Youth in City Design and Development:':
        sections:
        - '- Section: 15.1 Understanding the Role of Youth:':
            subsections:
            - 15.1a Definition of Youth
            - 15.1b Importance of Youth in City Design and Development
            - 15.1c Challenges in Engaging Youth in City Design and Development
        - '- Section: 15.2 Youth and City Design:':
            subsections:
            - 15.2a Role of Youth in City Design
            - 15.2b Case Studies of Youth in City Design
            - 15.2c Future Implications of Youth in City Design
        - '- Section: 15.3 Youth and City Development:':
            subsections:
            - 15.3a Role of Youth in City Development
            - 15.3b Case Studies of Youth in City Development
            - 15.3c Future Implications of Youth in City Development
    - '- Chapter 16: The Power of Place in City Design and Development:':
        sections:
        - '- Section: 16.1 Understanding the Power of Place:':
            subsections:
            - 16.1a Definition of Place
            - 16.1b Importance of Place in City Design and Development
            - 16.1c Challenges in Using Place for City Design and Development
        - '- Section: 16.2 Place and City Design:':
            subsections:
            - 16.2a Role of Place in City Design
            - 16.2b Case Studies of Place in City Design
            - 16.2c Future Implications of Place in City Design
        - '- Section: 16.3 Place and City Development:':
            subsections:
            - 16.3a Role of Place in City Development
            - 16.3b Case Studies of Place in City Development
            - 16.3c Future Implications of Place in City Development
    - '- Chapter 17: The Role of the Internet in City Design and Development:':
        sections:
        - '- Section: 17.1 Understanding the Role of the Internet:':
            subsections:
            - 17.1a Definition of the Internet
            - 17.1b Importance of the Internet in City Design and Development
            - 17.1c Challenges in Using the Internet for City Design and Development
        - '- Section: 17.2 The Internet and City Design:':
            subsections:
            - 17.2a Role of the Internet in City Design
            - 17.2b Case Studies of the Internet in City Design
            - 17.2c Future Implications of the Internet in City Design
        - '- Section: 17.3 The Internet and City Development:':
            subsections:
            - 17.3a Role of the Internet in City Development
            - 17.3b Case Studies of the Internet in City Development
            - 17.3c Future Implications of the Internet in City Development
    - '- Chapter 18: The Power of Media Technology in City Design and Development:':
        sections:
        - '- Section: 18.1 Understanding the Power of Media Technology:':
            subsections:
            - 18.1a Definition of Media Technology
            - 18.1b Importance of Media Technology in City Design and Development
            - 18.1c Challenges in Using Media Technology for City Design and Development
        - '- Section: 18.2 Media Technology and City Design:':
            subsections:
            - 18.2a Role of Media Technology in City Design
            - 18.2b Case Studies of Media Technology in City Design
            - 18.2c Future Implications of Media Technology in City Design
        - '- Section: 18.3 Media Technology and City Development:':
            subsections:
            - 18.3a Role of Media Technology in City Development
            - 18.3b Case Studies of Media Technology in City Development
            - 18.3c Future Implications of Media Technology in City Development
    - '- Chapter 19: The Role of Youth in City Design and Development:':
        sections:
        - '- Section: 19.1 Understanding the Role of Youth:':
            subsections:
            - 19.1a Definition of Youth
            - 19.1b Importance of Youth in City Design and Development
            - 19.1c Challenges in Engaging Youth in City Design and Development
        - '- Section: 19.2 Youth and City Design:':
            subsections:
            - 19.2a Role of Youth in City Design
            - 19.2b Case Studies of Youth in City Design
            - 19.2c Future Implications of Youth in City Design
        - '- Section: 19.3 Youth and City Development:':
            subsections:
            - 19.3a Role of Youth in City Development
            - 19.3b Case Studies of Youth in City Development
            - 19.3c Future Implications of Youth in City Development
    - '- Chapter 20: The Power of Place in City Design and Development:':
        sections:
        - '- Section: 20.1 Understanding the Power of Place:':
            subsections:
            - 20.1a Definition of Place
            - 20.1b Importance of Place in City Design and Development
            - 20.1c Challenges in Using Place for City Design and Development
        - '- Section: 20.2 Place and City Design:':
            subsections:
            - 20.2a Role of Place in City Design
            - 20.2b Case Studies of Place in City Design
            - 20.2c Future Implications of Place in City Design
        - '- Section: 20.3 Place and City Development:':
            subsections:
            - 20.3a Role of Place in City Development
            - 20.3b Case Studies of Place in City Development
            - 20.3c Future Implications of Place in City Development
