textbook:
  'Network and Computer Security: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: Introduction:':
        sections:
        - '- Section: 1.1 Course Number:':
            subsections:
            - 1.1a Course Code
            - 1.1b Course Registration
            - 1.1c Course Prerequisites
        - '- Section: 1.2 Course Name:':
            subsections:
            - 1.2a Course Title
            - 1.2b Course Description
            - 1.2c Course Objectives
        - '- Section: 1.3 Resource Level:':
            subsections:
            - 1.3a Resource Allocation
            - 1.3b Resource Management
            - 1.3c Resource Optimization
    - '- Chapter 2: Security Mechanisms and Principles:':
        sections:
        - '- Section: 2.1 Security Mechanisms:':
            subsections:
            - 2.1a Types of Security Mechanisms
            - 2.1b Implementing Security Mechanisms
            - 2.1c Security Mechanisms Evaluation
        - '- Section: 2.2 Security Principles:':
            subsections:
            - 2.2a Fundamental Security Principles
            - 2.2b Security Principles in Practice
            - 2.2c Security Principles and Policies
    - '- Chapter 3: Encryption and Perfect Secrecy:':
        sections:
        - '- Section: 3.1 Encryption:':
            subsections:
            - 3.1a Basics of Encryption
            - 3.1b Symmetric Encryption
            - 3.1c Asymmetric Encryption
        - '- Section: 3.2 Perfect Secrecy:':
            subsections:
            - 3.2a Definition of Perfect Secrecy
            - 3.2b Achieving Perfect Secrecy
            - 3.2c Limitations of Perfect Secrecy
        - '- Section: 3.3 One-Time Pad:':
            subsections:
            - 3.3a Introduction to One-Time Pad
            - 3.3b Using One-Time Pad
            - 3.3c One-Time Pad and Perfect Secrecy
    - '- Chapter 4: Cryptographic Hash Functions:':
        sections:
        - '- Section: 4.1 Hash Functions:':
            subsections:
            - 4.1a Basics of Hash Functions
            - 4.1b Hash Functions in Cryptography
            - 4.1c Hash Function Properties
        - '- Section: 4.2 Cryptographic Hash Functions:':
            subsections:
            - 4.2a Definition of Cryptographic Hash Functions
            - 4.2b Uses of Cryptographic Hash Functions
            - 4.2c Security of Cryptographic Hash Functions
    - '- Chapter 5: Hashing Applications and Constructions:':
        sections:
        - '- Section: 5.1 Hashing Applications:':
            subsections:
            - 5.1a Hashing in Data Retrieval
            - 5.1b Hashing in Password Storage
            - 5.1c Hashing in Digital Signatures
        - '- Section: 5.2 Hashing Constructions:':
            subsections:
            - 5.2a Merkle-Damgard Construction
            - 5.2b Sponge Construction
            - 5.2c Double Hashing
    - '- Chapter 6: Bitcoin:':
        sections:
        - '- Section: 6.1 Bitcoin Overview:':
            subsections:
            - 6.1a Introduction to Bitcoin
            - 6.1b Bitcoin Mining
            - 6.1c Bitcoin Transactions
    - '- Chapter 7: Secret Sharing:':
        sections:
        - '- Section: 7.1 Secret Sharing:':
            subsections:
            - 7.1a Basics of Secret Sharing
            - 7.1b Shamir's Secret Sharing
            - 7.1c Secret Sharing in Practice
    - '- Chapter 8: Block Ciphers:':
        sections:
        - '- Section: 8.1 Block Ciphers:':
            subsections:
            - 8.1a Introduction to Block Ciphers
            - 8.1b DES and AES
            - 8.1c Block Cipher Modes of Operation
    - '- Chapter 9: Block Cipher Modes:':
        sections:
        - '- Section: 9.1 Block Cipher Modes:':
            subsections:
            - 9.1a ECB and CBC Modes
            - 9.1b CFB and OFB Modes
            - 9.1c GCM and CTR Modes
    - '- Chapter 10: Message Authentication Codes:':
        sections:
        - '- Section: 10.1 Message Authentication Codes:':
            subsections:
            - 10.1a Basics of MACs
            - 10.1b HMAC and CMAC
            - 10.1c MACs in Practice
    - '- Chapter 11: Prime Finding and Crypto Math:':
        sections:
        - '- Section: 11.1 Prime Finding:':
            subsections:
            - 11.1a Sieve of Eratosthenes
            - 11.1b Primality Testing
            - 11.1c Prime Numbers in Cryptography
        - '- Section: 11.2 Crypto Math:':
            subsections:
            - 11.2a Modular Arithmetic
            - 11.2b Euler's Totient Function
            - 11.2c Chinese Remainder Theorem
    - '- Chapter 12: Diffie-Hellman Key Exchange:':
        sections:
        - '- Section: 12.1 Diffie-Hellman Key Exchange:':
            subsections:
            - 12.1a Basics of Diffie-Hellman
            - 12.1b Security of Diffie-Hellman
            - 12.1c Diffie-Hellman in Practice
        - '- Section: 12.2 Crypto Groups:':
            subsections:
            - 12.2a Definition of Crypto Groups
            - 12.2b Properties of Crypto Groups
            - 12.2c Crypto Groups in Key Exchange
    - '- Chapter 13: Pedersen Commitment:':
        sections:
        - '- Section: 13.1 Pedersen Commitment:':
            subsections:
            - 13.1a Basics of Pedersen Commitment
            - 13.1b Security of Pedersen Commitment
            - 13.1c Pedersen Commitment in Practice
        - '- Section: 13.2 PK Encryption:':
            subsections:
            - 13.2a Basics of PK Encryption
            - 13.2b RSA Encryption
            - 13.2c ElGamal Encryption
        - '- Section: 13.3 DDH:':
            subsections:
            - 13.3a Definition of DDH
            - 13.3b DDH Assumption
            - 13.3c DDH in Cryptography
    - '- Chapter 14: Malleability of El Gamal:':
        sections:
        - '- Section: 14.1 Malleability of El Gamal:':
            subsections:
            - 14.1a Definition of Malleability
            - 14.1b Malleability of El Gamal
            - 14.1c Malleability and IND-CCA2
        - '- Section: 14.2 IND-CCA2:':
            subsections:
            - 14.2a Definition of IND-CCA2
            - 14.2b IND-CCA2 and Malleability
            - 14.2c IND-CCA2 in Practice
    - '- Chapter 15: Digital Signatures:':
        sections:
        - '- Section: 15.1 Digital Signatures:':
            subsections:
            - 15.1a Basics of Digital Signatures
            - 15.1b RSA and DSA Signatures
            - 15.1c Digital Signatures in Practice
        - '- Section: 15.2 DSA:':
            subsections:
            - 15.2a Basics of DSA
            - 15.2b Security of DSA
            - 15.2c DSA in Practice
        - '- Section: 15.3 Gap Groups:':
            subsections:
            - 15.3a Definition of Gap Groups
            - 15.3b Gap Groups in Cryptography
            - 15.3c Gap Groups and Digital Signatures
    - '- Chapter 16: Gap Groups and Bilinear Maps:':
        sections:
        - '- Section: 16.1 Gap Groups:':
            subsections:
            - 16.1a Basics of Gap Groups
            - 16.1b Gap Groups in Cryptography
            - 16.1c Gap Groups and Digital Signatures
        - '- Section: 16.2 Bilinear Maps:':
            subsections:
            - 16.2a Definition of Bilinear Maps
            - 16.2b Bilinear Maps in Cryptography
            - 16.2c Bilinear Maps and Pairing-Based Cryptography
        - '- Section: 16.3 Applications:':
            subsections:
            - 16.3a Applications of Bilinear Maps
            - 16.3b Applications of Gap Groups
            - 16.3c Applications of Pairing-Based Cryptography
    - '- Chapter 17: Zero-Knowledge Proofs:':
        sections:
        - '- Section: 17.1 Zero-Knowledge Proofs:':
            subsections:
            - 17.1a Basics of Zero-Knowledge Proofs
            - 17.1b Interactive and Non-Interactive ZKPs
            - 17.1c ZKPs in Cryptography
    - '- Chapter 18: Security of Voting:':
        sections:
        - '- Section: 18.1 Security of Voting:':
            subsections:
            - 18.1a Basics of Voting Security
            - 18.1b Electronic Voting Security
            - 18.1c Voting Security Best Practices
    - '- Chapter 19: Project Presentations:':
        sections:
        - '- Section: 19.1 Project Presentations:':
            subsections:
            - 19.1a Preparing for Project Presentations
            - 19.1b Delivering Project Presentations
            - 19.1c Evaluating Project Presentations
    - '- Chapter 20: No Class:':
        sections:
        - '- Section: 20.1 No Class:':
            subsections:
            - 20.1a Course Breaks
            - 20.1b Independent Study
            - 20.1c Course Wrap-up
