textbook:
  'Comprehensive Guide to Linear Algebra and the Calculus of Variations":':
    chapters:
    - '- Chapter 1: Mathematical Preliminaries:':
        sections:
        - '- Section: 1.1 Vector Space:':
            subsections:
            - 1.1a Introduction to Vector Spaces
            - 1.1b Vector Addition and Scalar Multiplication
            - 1.1c Subspaces and Spanning Sets
            - 1.1d Linear Independence and Basis
            - 1.1e Dimension of Vector Space
            - 1.1f Components of a Vector
        - '- Section: 1.2 Linear Systems:':
            subsections:
            - 1.2a Solving Linear Systems
            - 1.2b Gaussian Elimination
            - 1.2c Matrix Representations
            - 1.2d Homogeneous Systems
            - 1.2e Matrix Inverses
        - '- Section: 1.3 Determinants:':
            subsections:
            - 1.3a Properties of Determinants
            - 1.3b Cofactor Expansion
            - 1.3c Cramer's Rule
            - 1.3d Applications of Determinants
    - '- Chapter 2: Scalar Product and Vector Operations:':
        sections:
        - '- Section: 2.1 Vector Operations:':
            subsections:
            - 2.1a Addition and Subtraction of Vectors
            - 2.1b Scalar Multiplication of Vectors
            - 2.1c Cross Product
            - 2.1d Dot Product
            - 2.1e Projection of Vectors
        - '- Section: 2.2 Length and Distance:':
            subsections:
            - 2.2a Length of Vector
            - 2.2b Distance between Vectors
        - '- Section: 2.3 Angles and Orthonormal Basis:':
            subsections:
            - 2.3a Angle between Vectors
            - 2.3b Orthonormal Basis
    - '- Chapter 3: Linear Transformations:':
        sections:
        - '- Section: 3.1 Introduction to Linear Transformations:':
            subsections:
            - 3.1a Definition and Examples
            - 3.1b Null Space and Range
            - 3.1c Matrix Representations
            - 3.1d Inverse Transformations
            - 3.1e Eigenvalue Problem
        - '- Section: 3.2 Orthogonal Transformations:':
            subsections:
            - 3.2a Orthogonal Matrices
            - 3.2b Diagonalization of Matrices
            - 3.2c Spectral Theorem
            - 3.2d Singular Value Decomposition
            - 3.2e Applications of Orthogonal Transformations
    - '- Chapter 4: Cartesian Tensors:':
        sections:
        - '- Section: 4.1 Introduction to Tensors:':
            subsections:
            - 4.1a Definition and Examples
            - 4.1b Tensor Operations
            - 4.1c Tensor Algebra
            - 4.1d Tensor Product
            - 4.1e Scalar Invariants
        - '- Section: 4.2 Symmetric Tensors:':
            subsections:
            - 4.2a Definition and Properties
            - 4.2b Eigenvalues and Eigenvectors
            - 4.2c Principal Basis
            - 4.2d Applications of Symmetric Tensors
        - '- Section: 4.3 Skew-symmetric Tensors:':
            subsections:
            - 4.3a Definition and Properties
            - 4.3b Cross Product of Vectors
        - '- Section: 4.4 General Tensors:':
            subsections:
            - 4.4a Contravariant and Covariant Tensors
            - 4.4b Mixed Tensors
            - 4.4c Tensor Derivatives
            - 4.4d Applications of General Tensors
    - '- Chapter 5: Orthogonal Tensors:':
        sections:
        - '- Section: 5.1 Positive-definite Tensors:':
            subsections:
            - 5.1a Definition and Properties
            - 5.1b Positive-definite Matrices
            - 5.1c Cholesky Decomposition
            - 5.1d Applications of Positive-definite Tensors
        - '- Section: 5.2 Orthogonal Tensors:':
            subsections:
            - 5.2a Definition and Properties
            - 5.2b Orthogonal Matrices
            - 5.2c Polar Decomposition
            - 5.2d Applications of Orthogonal Tensors
        - '- Section: 5.3 Improper Orthogonal Tensors:':
            subsections:
            - 5.3a Definition and Properties
            - 5.3b Improper Orthogonal Matrices
            - 5.3c Applications of Improper Orthogonal Tensors
    - '- Chapter 6: Linear Algebra Applications:':
        sections:
        - '- Section: 6.1 Mechanics of Elastic Solids:':
            subsections:
            - 6.1a Stress and Strain
            - 6.1b Hooke's Law
            - 6.1c Linear Elasticity
            - 6.1d Applications in Engineering
        - '- Section: 6.2 Linear Vector Spaces:':
            subsections:
            - 6.2a Inner Product Spaces
            - 6.2b Orthogonal Projection
            - 6.2c Fourier Series
            - 6.2d Applications in Signal Processing
        - '- Section: 6.3 Finite Dimensional Vector Spaces:':
            subsections:
            - 6.3a Bases and Dimension
            - 6.3b Linear Transformations
            - 6.3c Eigenvalues and Eigenvectors
            - 6.3d Applications in Physics
        - '- Section: 6.4 Lectures on Linear Algebra:':
            subsections:
            - 6.4a Matrix Algebra
            - 6.4b Determinants and Inverses
            - 6.4c Systems of Linear Equations
            - 6.4d Vector Spaces and Subspaces
        - '- Section: 6.5 Applications of Linear Algebra:':
            subsections:
            - 6.5a Data Analysis and Machine Learning
            - 6.5b Network Analysis
            - 6.5c Cryptography
            - 6.5d Optimization Techniques
    - '- Chapter 7: Matrix Theory:':
        sections:
        - '- Section: 7.1 Matrix Algebra:':
            subsections:
            - 7.1a Matrix Addition and Subtraction
            - 7.1b Matrix Multiplication
            - 7.1c Matrix Transpose
            - 7.1d Matrix Inverse
            - 7.1e Special Matrices
        - '- Section: 7.2 Matrix Determinants:':
            subsections:
            - 7.2a Definition and Properties
            - 7.2b Cofactor Expansion
            - 7.2c Applications of Determinants
        - '- Section: 7.3 Eigenvalues and Eigenvectors:':
            subsections:
            - 7.3a Definition and Properties
            - 7.3b Diagonalization of Matrices
            - 7.3c Applications of Eigenvalues and Eigenvectors
        - '- Section: 7.4 Matrix Decompositions:':
            subsections:
            - 7.4a LU Decomposition
            - 7.4b QR Decomposition
            - 7.4c Singular Value Decomposition
            - 7.4d Applications of Matrix Decompositions
    - '- Chapter 8: Vector Spaces:':
        sections:
        - '- Section: 8.1 Definition and Examples:':
            subsections:
            - 8.1a Vector Addition and Scalar Multiplication
            - 8.1b Linear Independence and Basis
            - 8.1c Dimension of Vector Space
            - 8.1d Subspaces
        - '- Section: 8.2 Inner Product Spaces:':
            subsections:
            - 8.2a Definition and Properties
            - 8.2b Orthogonal and Orthonormal Sets
            - 8.2c Gram-Schmidt Process
            - 8.2d Applications of Inner Product Spaces
        - '- Section: 8.3 Linear Transformations:':
            subsections:
            - 8.3a Definition and Examples
            - 8.3b Kernel and Image
            - 8.3c Matrix Representation
            - 8.3d Applications of Linear Transformations
        - '- Section: 8.4 Dual Spaces:':
            subsections:
            - 8.4a Definition and Examples
            - 8.4b Dual Basis
            - 8.4c Applications of Dual Spaces
    - '- Chapter 9: Calculus of Variations:':
        sections:
        - '- Section: 9.1 Introduction to Calculus of Variations:':
            subsections:
            - 9.1a Functionals
            - 9.1b Euler-Lagrange Equation
            - 9.1c Variational Principles
            - 9.1d Applications of Calculus of Variations
        - '- Section: 9.2 Hamilton''s Principle:':
            subsections:
            - 9.2a Lagrangian and Hamiltonian Mechanics
            - 9.2b Hamilton's Principle of Least Action
            - 9.2c Applications in Physics
        - '- Section: 9.3 Optimal Control Theory:':
            subsections:
            - 9.3a Introduction to Optimal Control
            - 9.3b Pontryagin's Maximum Principle
            - 9.3c Applications in Engineering
        - '- Section: 9.4 Variational Methods in Quantum Mechanics:':
            subsections:
            - "9.4a Schr\xF6dinger Equation"
            - 9.4b Variational Principle in Quantum Mechanics
            - 9.4c Applications in Quantum Mechanics
    - '- Chapter 10: Differential Equations:':
        sections:
        - '- Section: 10.1 Ordinary Differential Equations:':
            subsections:
            - 10.1a First Order ODEs
            - 10.1b Second Order ODEs
            - 10.1c Linear ODEs
            - 10.1d Nonlinear ODEs
            - 10.1e Applications of ODEs
        - '- Section: 10.2 Partial Differential Equations:':
            subsections:
            - 10.2a First Order PDEs
            - 10.2b Second Order PDEs
            - 10.2c Linear PDEs
            - 10.2d Nonlinear PDEs
            - 10.2e Applications of PDEs
        - '- Section: 10.3 Boundary Value Problems:':
            subsections:
            - 10.3a Definition and Examples
            - 10.3b Sturm-Liouville Theory
            - 10.3c Applications of Boundary Value Problems
        - '- Section: 10.4 Numerical Methods for Differential Equations:':
            subsections:
            - 10.4a Euler's Method
            - 10.4b Runge-Kutta Methods
            - 10.4c Finite Difference Method
            - 10.4d Applications of Numerical Methods
    - '- Chapter 11: Probability and Statistics:':
        sections:
        - '- Section: 11.1 Probability Theory:':
            subsections:
            - 11.1a Probability Spaces
            - 11.1b Random Variables
            - 11.1c Probability Distributions
            - 11.1d Expectation and Variance
            - 11.1e Applications of Probability Theory
        - '- Section: 11.2 Statistical Theory:':
            subsections:
            - 11.2a Descriptive Statistics
            - 11.2b Inferential Statistics
            - 11.2c Hypothesis Testing
            - 11.2d Regression Analysis
            - 11.2e Applications of Statistical Theory
        - '- Section: 11.3 Stochastic Processes:':
            subsections:
            - 11.3a Definition and Examples
            - 11.3b Markov Chains
            - 11.3c Brownian Motion
            - 11.3d Applications of Stochastic Processes
        - '- Section: 11.4 Linear Algebra in Probability and Statistics:':
            subsections:
            - 11.4a Covariance Matrix
            - 11.4b Principal Component Analysis
            - 11.4c Singular Value Decomposition in Data Analysis
            - 11.4d Applications in Machine Learning
    - '- Chapter 12: Optimization:':
        sections:
        - '- Section: 12.1 Unconstrained Optimization:':
            subsections:
            - 12.1a Definition and Examples
            - 12.1b Gradient Descent
            - 12.1c Newton's Method
            - 12.1d Applications of Unconstrained Optimization
        - '- Section: 12.2 Constrained Optimization:':
            subsections:
            - 12.2a Definition and Examples
            - 12.2b Lagrange Multipliers
            - 12.2c KKT Conditions
            - 12.2d Applications of Constrained Optimization
        - '- Section: 12.3 Linear Programming:':
            subsections:
            - 12.3a Definition and Examples
            - 12.3b Simplex Method
            - 12.3c Duality in Linear Programming
            - 12.3d Applications of Linear Programming
        - '- Section: 12.4 Nonlinear Programming:':
            subsections:
            - 12.4a Definition and Examples
            - 12.4b Interior Point Methods
            - 12.4c Convex Optimization
            - 12.4d Applications of Nonlinear Programming
    - '- Chapter 13: Numerical Linear Algebra:':
        sections:
        - '- Section: 13.1 Numerical Matrix Operations:':
            subsections:
            - 13.1a Numerical Matrix Addition and Subtraction
            - 13.1b Numerical Matrix Multiplication
            - 13.1c Numerical Matrix Inverse
            - 13.1d Numerical Matrix Decompositions
            - 13.1e Applications of Numerical Matrix Operations
        - '- Section: 13.2 Numerical Vector Operations:':
            subsections:
            - 13.2a Numerical Vector Addition and Subtraction
            - 13.2b Numerical Scalar Multiplication
            - 13.2c Numerical Dot Product
            - 13.2d Numerical Cross Product
            - 13.2e Applications of Numerical Vector Operations
        - '- Section: 13.3 Numerical Solutions of Linear Systems:':
            subsections:
            - 13.3a Direct Methods
            - 13.3b Iterative Methods
            - 13.3c Error Analysis
            - 13.3d Applications of Numerical Solutions of Linear Systems
        - '- Section: 13.4 Numerical Eigenvalue Problems:':
            subsections:
            - 13.4a Power Method
            - 13.4b QR Algorithm
            - 13.4c Jacobi Method
            - 13.4d Applications of Numerical Eigenvalue Problems
    - '- Chapter 14: Linear Algebra in Computer Science:':
        sections:
        - '- Section: 14.1 Data Structures for Matrices and Vectors:':
            subsections:
            - 14.1a Array Data Structure
            - 14.1b Linked List Data Structure
            - 14.1c Sparse Matrix Data Structure
            - 14.1d Applications in Computer Science
        - '- Section: 14.2 Algorithms for Matrix Operations:':
            subsections:
            - 14.2a Algorithm for Matrix Addition
            - 14.2b Algorithm for Matrix Multiplication
            - 14.2c Algorithm for Matrix Inverse
            - 14.2d Applications in Computer Science
        - '- Section: 14.3 Graph Theory and Linear Algebra:':
            subsections:
            - 14.3a Graphs and Matrices
            - 14.3b Adjacency Matrix
            - 14.3c Incidence Matrix
            - 14.3d Applications in Computer Science
        - '- Section: 14.4 Linear Algebra in Cryptography:':
            subsections:
            - 14.4a Hill Cipher
            - 14.4b RSA Algorithm
            - 14.4c Elliptic Curve Cryptography
            - 14.4d Applications in Computer Science
    - '- Chapter 15: Linear Algebra in Engineering:':
        sections:
        - '- Section: 15.1 Linear Algebra in Electrical Engineering:':
            subsections:
            - 15.1a Circuit Analysis
            - 15.1b Signal Processing
            - 15.1c Control Systems
            - 15.1d Applications in Electrical Engineering
        - '- Section: 15.2 Linear Algebra in Mechanical Engineering:':
            subsections:
            - 15.2a Stress and Strain Analysis
            - 15.2b Vibration Analysis
            - 15.2c Finite Element Method
            - 15.2d Applications in Mechanical Engineering
        - '- Section: 15.3 Linear Algebra in Civil Engineering:':
            subsections:
            - 15.3a Structural Analysis
            - 15.3b Transportation Engineering
            - 15.3c Environmental Engineering
            - 15.3d Applications in Civil Engineering
        - '- Section: 15.4 Linear Algebra in Chemical Engineering:':
            subsections:
            - 15.4a Chemical Reaction Networks
            - 15.4b Process Control
            - 15.4c Thermodynamics
            - 15.4d Applications in Chemical Engineering
    - '- Chapter 16: Linear Algebra in Physics:':
        sections:
        - '- Section: 16.1 Linear Algebra in Classical Mechanics:':
            subsections:
            - 16.1a Newton's Laws
            - 16.1b Lagrangian Mechanics
            - 16.1c Hamiltonian Mechanics
            - 16.1d Applications in Classical Mechanics
        - '- Section: 16.2 Linear Algebra in Quantum Mechanics:':
            subsections:
            - "16.2a Schr\xF6dinger Equation"
            - 16.2b Quantum States and Operators
            - 16.2c Quantum Entanglement
            - 16.2d Applications in Quantum Mechanics
        - '- Section: 16.3 Linear Algebra in Electrodynamics:':
            subsections:
            - 16.3a Maxwell's Equations
            - 16.3b Electromagnetic Waves
            - 16.3c Electromagnetic Fields
            - 16.3d Applications in Electrodynamics
        - '- Section: 16.4 Linear Algebra in General Relativity:':
            subsections:
            - 16.4a Einstein's Field Equations
            - 16.4b Metric Tensor
            - 16.4c Curvature Tensor
            - 16.4d Applications in General Relativity
    - '- Chapter 17: Linear Algebra in Economics:':
        sections:
        - '- Section: 17.1 Linear Algebra in Microeconomics:':
            subsections:
            - 17.1a Consumer Theory
            - 17.1b Producer Theory
            - 17.1c Market Equilibrium
            - 17.1d Applications in Microeconomics
        - '- Section: 17.2 Linear Algebra in Macroeconomics:':
            subsections:
            - 17.2a National Income Accounting
            - 17.2b IS-LM Model
            - 17.2c Aggregate Demand and Supply
            - 17.2d Applications in Macroeconomics
        - '- Section: 17.3 Linear Algebra in Econometrics:':
            subsections:
            - 17.3a Regression Analysis
            - 17.3b Time Series Analysis
            - 17.3c Panel Data Analysis
            - 17.3d Applications in Econometrics
        - '- Section: 17.4 Linear Algebra in Game Theory:':
            subsections:
            - 17.4a Normal Form Games
            - 17.4b Nash Equilibrium
            - 17.4c Mixed Strategies
            - 17.4d Applications in Game Theory
    - '- Chapter 18: Linear Algebra in Biology:':
        sections:
        - '- Section: 18.1 Linear Algebra in Population Biology:':
            subsections:
            - 18.1a Population Growth Models
            - 18.1b Predator-Prey Models
            - 18.1c Epidemiological Models
            - 18.1d Applications in Population Biology
