textbook:
  'Science, Politics, and Environmental Policy: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: What is Science?:':
        sections:
        - '- Section: 1.1 Introduction to the Course:':
            subsections:
            - 1.1a Course Overview
            - 1.1b Course Objectives
            - 1.1c Course Materials
        - '- Section: 1.2 The Policy Process and the Political Debate Over ''Sound Science'':':
            subsections:
            - 1.2a Understanding Policy Process
            - 1.2b The Role of Science in Policy
            - 1.2c Debates Over 'Sound Science'
        - '- Section: 1.3 The Scientific Method and the Production of Scientific Knowledge:':
            subsections:
            - 1.3a Understanding the Scientific Method
            - 1.3b The Production of Scientific Knowledge
            - 1.3c The Role of Scientific Knowledge in Society
    - '- Chapter 2: Environmental Science:':
        sections:
        - '- Section: 2.1 Environmental Advocacy: Using Science to Define Problems:':
            subsections:
            - 2.1a The Role of Science in Environmental Advocacy
            - 2.1b Using Science to Define Environmental Problems
            - 2.1c Case Studies in Environmental Advocacy
        - '- Section: 2.2 Media Coverage of Science and Environmental Risk:':
            subsections:
            - 2.2a The Role of Media in Science Communication
            - 2.2b Media Coverage of Environmental Risks
            - 2.2c The Impact of Media on Public Perception of Science
        - '- Section: 2.3 The Public''s Perception of Science and Environmental Risk:':
            subsections:
            - 2.3a Understanding Public Perception of Science
            - 2.3b Public Perception of Environmental Risks
            - 2.3c Influencing Public Perception of Science and Environmental Risks
    - '- Chapter 3: Science in Decision Making:':
        sections:
        - '- Section: 3.1 Science in Legislative Decision Making:':
            subsections:
            - 3.1a The Role of Science in Legislative Decision Making
            - 3.1b Case Studies in Legislative Decision Making
            - 3.1c Challenges in Incorporating Science into Legislative Decision Making
        - '- Section: 3.2 Science in Administrative and Judicial Decision Making:':
            subsections:
            - 3.2a The Role of Science in Administrative Decision Making
            - 3.2b The Role of Science in Judicial Decision Making
            - 3.2c Challenges in Incorporating Science into Administrative and Judicial
              Decision Making
        - '- Section: 3.3 Science in the International Arena:':
            subsections:
            - 3.3a The Role of Science in International Policy Making
            - 3.3b Case Studies in International Science Policy
            - 3.3c Challenges in Incorporating Science into International Policy Making
    - '- Chapter 4: Advocacy Science vs. Collaborative Science:':
        sections:
        - '- Section: 4.1 Advocacy Science vs. Collaborative Science:':
            subsections:
            - 4.1a Understanding Advocacy Science
            - 4.1b Understanding Collaborative Science
            - 4.1c Comparing Advocacy Science and Collaborative Science
        - '- Section: 4.2 Local Knowledge:':
            subsections:
            - 4.2a The Role of Local Knowledge in Science
            - 4.2b Case Studies in Local Knowledge
            - 4.2c Challenges in Incorporating Local Knowledge into Science
        - '- Section: 4.3 Uncertainty, Adaptive Management and the Precautionary Principle:':
            subsections:
            - 4.3a Understanding Uncertainty in Science
            - 4.3b The Role of Adaptive Management in Science
            - 4.3c The Precautionary Principle in Science
    - '- Chapter 5: Other Topics:':
        sections:
        - '- Section: 5.1 (Add additional topics and subtopics as needed):':
            subsections:
            - 5.1a Topic 1
            - 5.1b Topic 2
            - 5.1c Topic 3
