textbook:
  'Continuum Mechanics for Earth, Atmospheric, and Planetary Sciences":':
    chapters:
    - '- Chapter 1: Introduction to Continuum Mechanics:':
        sections:
        - '- Section: 1.1 Fundamentals of Continuum Mechanics:':
            subsections:
            - 1.1a Introduction to Continuum Mechanics
            - 1.1b Continuum Approximation in Earth Sciences
            - 1.1c Continuum Approximation in Atmospheric Sciences
            - 1.1d Continuum Approximation in Planetary Sciences
    - '- Chapter 2: Traction and Stress Analysis:':
        sections:
        - '- Section: 2.1 Definition of Traction:':
            subsections:
            - 2.1a Definition of Traction
            - 2.1b Normal and Shear Traction
            - 2.1c Traction Vector
        - '- Section: 2.2 Stress Tensor:':
            subsections:
            - 2.2a Definition of Stress Tensor
            - 2.2b Components of Stress Tensor
            - 2.2c Stress in Different Coordinate Systems
    - '- Chapter 3: Pore Fluid Pressure and Its Effects:':
        sections:
        - '- Section: 3.1 Definition of Pore Fluid Pressure:':
            subsections:
            - 3.1a Definition of Pore Fluid Pressure
            - 3.1b Effect of Pore Fluid Pressure on Stress Distribution
            - 3.1c Fluid Pressure in Porous Media
    - '- Chapter 4: Equations of Motion and Conservation Laws:':
        sections:
        - '- Section: 4.1 Newton''s Second Law:':
            subsections:
            - 4.1a Newton's Second Law
            - 4.1b Conservation of Momentum
            - 4.1c Forces Acting on a Body
    - '- Chapter 5: Stress Analysis in the Earth:':
        sections:
        - '- Section: 5.1 Stress Distribution in the Earth:':
            subsections:
            - 5.1a Stress Distribution in the Earth
            - 5.1b Lithospheric Stress
            - 5.1c Tectonic Stress
    - '- Chapter 6: Stress Rotation and Mohr''s Circle:':
        sections:
        - '- Section: 6.1 Transformations of Stress Tensor:':
            subsections:
            - 6.1a Transformations of Stress Tensor
            - 6.1b Principal Stresses and Directions
            - 6.1c Mohr's Circle
    - '- Chapter 7: Sandbox Tectonics and Experimental Models:':
        sections:
        - '- Section: 7.1 Experimental Models of Tectonic Processes:':
            subsections:
            - 7.1a Experimental Models of Tectonic Processes
            - 7.1b Scaling Laws in Sandbox Experiments
            - 7.1c Tectonic Deformation Patterns
    - '- Chapter 8: Displacement Gradients and Strain Analysis:':
        sections:
        - '- Section: 8.1 Definition of Displacement Gradient:':
            subsections:
            - 8.1a Definition of Displacement Gradient
            - 8.1b Strain Tensor
            - 8.1c Deformation Gradient
    - '- Chapter 9: Techniques for Measuring Displacement Gradient:':
        sections:
        - '- Section: 9.1 Introduction to Measurement of Displacement Gradient:':
            subsections:
            - 9.1a Introduction to Measurement of Displacement Gradient
            - 9.1b Image Velocimetry
            - 9.1c Strain Gauges
    - '- Chapter 10: Finite Strain Analysis:':
        sections:
        - '- Section: 10.1 Large Deformation Theory:':
            subsections:
            - 10.1a Large Deformation Theory
            - 10.1b Green-Lagrange Strain Tensor
            - 10.1c Compatibility Equations
    - '- Chapter 11: Elasticity and Elastic Moduli:':
        sections:
        - '- Section: 11.1 Hooke''s Law:':
            subsections:
            - 11.1a Hooke's Law
            - 11.1b Elastic Moduli
            - 11.1c Elasticity Tensor
    - '- Chapter 12: Example: Uniaxial Strain and Young''s Modulus:':
        sections:
        - '- Section: 12.1 One-Dimensional Strain:':
            subsections:
            - 12.1a One-Dimensional Strain
            - 12.1b Stress-Strain Relationship
            - 12.1c Young's Modulus
    - '- Chapter 13: Special Cases of Strain Analysis:':
        sections:
        - '- Section: 13.1 Plane Strain:':
            subsections:
            - 13.1a Plane Strain
            - 13.1b Plane Stress
            - 13.1c Axisymmetric Deformation
    - '- Chapter 14: Dislocation Theory and Earthquake Cycle:':
        sections:
        - '- Section: 14.1 Fault Slip:':
            subsections:
            - 14.1a Fault Slip
            - 14.1b Earthquake Rupture
            - 14.1c Aseismic Slip
    - '- Chapter 15: Stress and Strain Analysis from Dislocation:':
        sections:
        - '- Section: 15.1 Dislocation Theory:':
            subsections:
            - 15.1a Dislocation Theory
            - 15.1b Burgers Vector
            - 15.1c Dislocation Line
    - '- Chapter 16: Plate Tectonics and Boundaries:':
        sections:
        - '- Section: 16.1 Plate Tectonics:':
            subsections:
            - 16.1a Plate Tectonics
            - 16.1b Plate Boundaries
            - 16.1c Plate Motions
    - '- Chapter 17: Plate Tectonics Overview and Rheology:':
        sections:
        - '- Section: 17.1 Plate Tectonics Overview:':
            subsections:
            - 17.1a Plate Tectonics Overview
            - 17.1b Plate Boundary Interactions
            - 17.1c Rheology of the Lithosphere
    - '- Chapter 18: Fluid Properties and Equations:':
        sections:
        - '- Section: 18.1 Fluid Properties:':
            subsections:
            - 18.1a Fluid Properties
            - 18.1b Continuity Equation
            - 18.1c Bernoulli's Equation
    - '- Chapter 19: Fluid Flow and Navier-Stokes Equation:':
        sections:
        - '- Section: 19.1 Governing Equations for Fluid Flow:':
            subsections:
            - 19.1a Governing Equations for Fluid Flow
            - 19.1b Incompressible Flow
            - 19.1c Viscous Effects
    - '- Chapter 20: Growth, Decay, and Surface Instabilities:':
        sections:
        - '- Section: 20.1 Linear Stability Analysis:':
            subsections:
            - 20.1a Linear Stability Analysis
            - 20.1b Growth and Decay Rates
            - 20.1c Surface Instabilities
    - '- Chapter 21: Fluid Flow in Porous Media:':
        sections:
        - '- Section: 21.1 Darcy''s Law:':
            subsections:
            - 21.1a Darcy's Law
            - 21.1b Permeability
            - 21.1c Fluid Flow in Sedimentary Basins
    - '- Chapter 22: Time Dependent Porous Flow:':
        sections:
        - '- Section: 22.1 Transient Flow:':
            subsections:
            - 22.1a Transient Flow
            - 22.1b Diffusion Equation
            - 22.1c Boundary Conditions
    - '- Chapter 23: Introduction to Geomechanics:':
        sections:
        - '- Section: 23.1 Basic Concepts of Geomechanics:':
            subsections:
            - 23.1a Stress and Strain in Geomechanics
            - 23.1b Mechanical Properties of Rocks
            - 23.1c Geomechanical Modeling
    - '- Chapter 24: Geomechanics Applications:':
        sections:
        - '- Section: 24.1 Geomechanics in Oil and Gas Industry:':
            subsections:
            - 24.1a Wellbore Stability
            - 24.1b Hydraulic Fracturing
            - 24.1c Reservoir Compaction and Subsidence
    - '- Chapter 25: Geomechanics in Mining:':
        sections:
        - '- Section: 25.1 Rock Mechanics in Mining:':
            subsections:
            - 25.1a Slope Stability
            - 25.1b Ground Control in Underground Mines
            - 25.1c Subsidence due to Mining
    - '- Chapter 26: Geomechanics in Civil Engineering:':
        sections:
        - '- Section: 26.1 Soil Mechanics:':
            subsections:
            - 26.1a Shear Strength of Soils
            - 26.1b Consolidation and Settlement
            - 26.1c Slope Stability in Soils
    - '- Chapter 27: Geomechanics in Geotechnical Engineering:':
        sections:
        - '- Section: 27.1 Foundation Engineering:':
            subsections:
            - 27.1a Bearing Capacity
            - 27.1b Pile Foundations
            - 27.1c Retaining Walls
    - '- Chapter 28: Geomechanics in Geohazards:':
        sections:
        - '- Section: 28.1 Landslides:':
            subsections:
            - 28.1a Types of Landslides
            - 28.1b Landslide Mechanics
            - 28.1c Landslide Mitigation
    - '- Chapter 29: Geomechanics in Earthquake Engineering:':
        sections:
        - '- Section: 29.1 Seismic Hazard Assessment:':
            subsections:
            - 29.1a Ground Motion Prediction
            - 29.1b Site Response Analysis
            - 29.1c Seismic Risk Assessment
    - '- Chapter 30: Geomechanics in Environmental Engineering:':
        sections:
        - '- Section: 30.1 Waste Disposal:':
            subsections:
            - 30.1a Landfill Design
            - 30.1b Nuclear Waste Disposal
            - 30.1c Carbon Capture and Storage
