textbook:
  'Quantum Physics: A Comprehensive Introduction":':
    chapters:
    - '- Chapter 1: Introduction to Quantum Mechanics:':
        sections:
        - '- Section: 1.1 Basic Features of Quantum Mechanics:':
            subsections:
            - 1.1a Linearity
            - 1.1b Complex Numbers
            - 1.1c Non-deterministic Behavior
            - 1.1d Superposition
            - 1.1e Entanglement
            - 1.1f Wave-particle Duality
        - '- Section: 1.2 Experimental Basis of Quantum Physics:':
            subsections:
            - 1.2a Two-slit Experiments
            - 1.2b Mach-Zehnder Interferometer
            - 1.2c Elitzur-Vaidman Bombs
            - 1.2d Photoelectric Effect
            - 1.2e Compton Scattering
            - 1.2f de Broglie Wavelength
            - 1.2g Quantum Tunneling
        - '- Section: 1.3 Wave Mechanics:':
            subsections:
            - 1.3a Galilean Transformation of de Broglie Wavelength
            - 1.3b Wave-packets and Group Velocity
            - 1.3c Matter Wave for a Particle
            - 1.3d Momentum and Position Operators
            - "1.3e Schr\xF6dinger Equation"
            - "1.3f Time-independent Schr\xF6dinger Equation"
            - "1.3g Time-dependent Schr\xF6dinger Equation"
        - '- Section: 1.4 Interpretation of Quantum Mechanics:':
            subsections:
            - 1.4a Probability Density
            - 1.4b Probability Current
            - 1.4c Current Conservation
            - 1.4d Hermitian Operators
            - 1.4e Eigenvalues and Eigenfunctions
            - 1.4f Measurement in Quantum Mechanics
    - '- Chapter 2: Expectation Values and Uncertainty:':
        sections:
        - '- Section: 2.1 Expectation Values of Operators:':
            subsections:
            - 2.1a Expectation Values
            - 2.1b Time Evolution of Wave-packets
            - 2.1c Fourier Transforms
            - 2.1d Parseval Theorem
            - 2.1e Uncertainty Relation
            - 2.1f Heisenberg's Uncertainty Principle
        - '- Section: 2.2 Quantum Physics in One-dimensional Potentials:':
            subsections:
            - 2.2a Stationary States
            - 2.2b Boundary Conditions
            - 2.2c Particle on a Circle
            - 2.2d Infinite Square Well
            - 2.2e Finite Square Well
            - 2.2f Semiclassical Approximations
            - 2.2g Numerical Solution by the Shooting Method
            - 2.2h Delta Function Potential
            - 2.2i Simple Harmonic Oscillator
            - 2.2j Reflection and Transmission Coefficients
            - 2.2k Ramsauer Townsend Effect
            - 2.2l 1D Scattering and Phase Shifts
            - "2.2m Levinson\u2019s Theorem"
            - 2.2n Quantum Tunneling in One-dimensional Potentials
        - '- Section: 2.3 Angular Momentum and Central Potentials:':
            subsections:
            - 2.3a Resonances and Breit-Wigner Distribution
            - 2.3b Central Potentials
            - 2.3c Algebra of Angular Momentum
            - 2.3d Legendre Polynomials
            - 2.3e Hydrogen Atom
            - 2.3f Energy Levels Diagram
            - 2.3g Virial Theorem
            - 2.3h Circular Orbits and Eccentricity
            - 2.3i Discovery of Spin
            - 2.3j Addition of Angular Momenta
            - 2.3k Fine Structure of Hydrogen Atom
            - 2.3l Zeeman Effect
            - 2.3m Paschen-Back Effect
    - '- Chapter 3: Katrina Practicum:':
        sections:
        - '- Section: 3.1 Introduction to Katrina Practicum:':
            subsections:
            - 3.1a Introduction
            - 3.1b Background Research
            - 3.1c New Orleans Context
            - 3.1d Environmental History/Context
            - 3.1e Data Report-back
            - 3.1f Survey Development
            - 3.1g Housing Group Presentation
            - 3.1h Site Visit
            - 3.1i Racism, Society, and New Orleans
            - 3.1j Update on Student Projects
            - 3.1k Check-in/Work Session
            - 3.1l Final Presentation
    - '- Chapter 4: Quantum Mechanics in Three Dimensions:':
        sections:
        - "- Section: 4.1 Three-Dimensional Schr\xF6dinger Equation:":
            subsections:
            - 4.1a Derivation of the Equation
            - 4.1b Solutions for Various Potentials
            - 4.1c Radial Equation
            - 4.1d Spherical Harmonics
        - '- Section: 4.2 Hydrogen Atom:':
            subsections:
            - "4.2a Schr\xF6dinger Equation for Hydrogen"
            - 4.2b Radial Solutions
            - 4.2c Quantum Numbers
            - 4.2d Orbital Shapes
        - '- Section: 4.3 Angular Momentum:':
            subsections:
            - 4.3a Orbital Angular Momentum
            - 4.3b Spin Angular Momentum
            - 4.3c Total Angular Momentum
            - 4.3d Addition of Angular Momenta
        - '- Section: 4.4 Spin:':
            subsections:
            - 4.4a Stern-Gerlach Experiment
            - 4.4b Spinors
            - 4.4c Pauli Matrices
            - 4.4d Spin-Orbit Interaction
    - '- Chapter 5: Quantum Mechanics of Identical Particles:':
        sections:
        - '- Section: 5.1 Two-Particle Systems:':
            subsections:
            - 5.1a Two-Particle Wavefunctions
            - 5.1b Exchange Symmetry
            - 5.1c Bosons and Fermions
            - 5.1d Pauli Exclusion Principle
        - '- Section: 5.2 Many-Particle Systems:':
            subsections:
            - 5.2a Many-Particle Wavefunctions
            - 5.2b Fermi-Dirac and Bose-Einstein Statistics
            - 5.2c Fermi Gas
            - 5.2d Bose-Einstein Condensation
        - '- Section: 5.3 Quantum Mechanics of Solids:':
            subsections:
            - 5.3a Band Theory
            - 5.3b Conductors, Insulators, and Semiconductors
            - 5.3c Superconductivity
            - 5.3d Quantum Hall Effect
        - '- Section: 5.4 Quantum Mechanics of Light:':
            subsections:
            - 5.4a Photons
            - 5.4b Blackbody Radiation
            - 5.4c Photoelectric Effect
            - 5.4d Compton Scattering
    - '- Chapter 6: Time-Independent Perturbation Theory:':
        sections:
        - '- Section: 6.1 Non-Degenerate Perturbation Theory:':
            subsections:
            - 6.1a First-Order Corrections
            - 6.1b Second-Order Corrections
            - 6.1c Stark Effect
        - '- Section: 6.2 Degenerate Perturbation Theory:':
            subsections:
            - 6.2a First-Order Corrections
            - 6.2b Second-Order Corrections
            - 6.2c Zeeman Effect
        - '- Section: 6.3 Variational Principle:':
            subsections:
            - 6.3a Variational Formulation of Quantum Mechanics
            - 6.3b Ground State Energy
            - 6.3c Excited States
        - '- Section: 6.4 WKB Approximation:':
            subsections:
            - 6.4a Derivation of the WKB Approximation
            - 6.4b Connection Formulas
            - 6.4c Quantum Tunneling
    - '- Chapter 7: Time-Dependent Perturbation Theory:':
        sections:
        - '- Section: 7.1 Interaction Picture:':
            subsections:
            - 7.1a Interaction Picture Operators and States
            - "7.1b Interaction Picture Schr\xF6dinger Equation"
            - 7.1c Dyson Series
        - '- Section: 7.2 Fermi''s Golden Rule:':
            subsections:
            - 7.2a Derivation of Fermi's Golden Rule
            - 7.2b Transition Rates
            - 7.2c Spontaneous Emission
        - '- Section: 7.3 Adiabatic and Sudden Approximations:':
            subsections:
            - 7.3a Adiabatic Theorem
            - 7.3b Berry Phase
            - 7.3c Sudden Approximation
        - '- Section: 7.4 Quantum Mechanics of Radiation:':
            subsections:
            - 7.4a Absorption and Emission of Radiation
            - 7.4b Selection Rules
            - 7.4c Rabi Oscillations
    - '- Chapter 8: Scattering Theory:':
        sections:
        - '- Section: 8.1 Scattering Amplitude and Cross Section:':
            subsections:
            - 8.1a Scattering Amplitude
            - 8.1b Differential Cross Section
            - 8.1c Total Cross Section
        - '- Section: 8.2 Born Approximation:':
            subsections:
            - 8.2a Derivation of the Born Approximation
            - 8.2b Scattering from a Central Potential
            - 8.2c Form Factor
        - '- Section: 8.3 Partial Wave Analysis:':
            subsections:
            - 8.3a Expansion in Partial Waves
            - 8.3b Phase Shifts
            - 8.3c Resonances
        - '- Section: 8.4 Scattering of Identical Particles:':
            subsections:
            - 8.4a Symmetrization of the Scattering Amplitude
            - 8.4b Bose-Einstein and Fermi-Dirac Scattering
            - 8.4c Exchange Forces
    - '- Chapter 9: Quantum Mechanics of Systems with Spin:':
        sections:
        - '- Section: 9.1 Spin-1/2 Systems:':
            subsections:
            - 9.1a Spinors
            - 9.1b Pauli Matrices
            - 9.1c Spin-Orbit Interaction
        - '- Section: 9.2 Spin-1 Systems:':
            subsections:
            - 9.2a Spin-1 Matrices
            - 9.2b Spin-1 States
            - 9.2c Quadrupole Interaction
        - '- Section: 9.3 Addition of Angular Momenta:':
            subsections:
            - 9.3a Clebsch-Gordan Coefficients
            - 9.3b Wigner-Eckart Theorem
            - 9.3c Hyperfine Structure
        - '- Section: 9.4 Quantum Mechanics of the Electron:':
            subsections:
            - 9.4a Dirac Equation
            - 9.4b Spin and Magnetic Moment of the Electron
            - 9.4c Zitterbewegung
    - '- Chapter 10: Quantum Mechanics of Relativistic Systems:':
        sections:
        - '- Section: 10.1 Klein-Gordon Equation:':
            subsections:
            - 10.1a Derivation of the Klein-Gordon Equation
            - 10.1b Solutions for Various Potentials
            - 10.1c Negative Energy Solutions
        - '- Section: 10.2 Dirac Equation:':
            subsections:
            - 10.2a Derivation of the Dirac Equation
            - 10.2b Solutions for Various Potentials
            - 10.2c Negative Energy Solutions and Hole Theory
        - '- Section: 10.3 Quantum Electrodynamics:':
            subsections:
            - 10.3a Interaction of Light and Matter
            - 10.3b Feynman Diagrams
            - 10.3c Lamb Shift
        - '- Section: 10.4 Quantum Field Theory:':
            subsections:
            - 10.4a Second Quantization
            - 10.4b Creation and Annihilation Operators
            - 10.4c Quantum Electrodynamics
    - '- Chapter 11: Quantum Mechanics of Systems with Spin:':
        sections:
        - '- Section: 11.1 Spin-1/2 Systems:':
            subsections:
            - 11.1a Spinors
            - 11.1b Pauli Matrices
            - 11.1c Spin-Orbit Interaction
        - '- Section: 11.2 Spin-1 Systems:':
            subsections:
            - 11.2a Spin-1 Matrices
            - 11.2b Spin-1 States
            - 11.2c Quadrupole Interaction
        - '- Section: 11.3 Addition of Angular Momenta:':
            subsections:
            - 11.3a Clebsch-Gordan Coefficients
            - 11.3b Wigner-Eckart Theorem
            - 11.3c Hyperfine Structure
        - '- Section: 11.4 Quantum Mechanics of the Electron:':
            subsections:
            - 11.4a Dirac Equation
            - 11.4b Spin and Magnetic Moment of the Electron
            - 11.4c Zitterbewegung
    - '- Chapter 12: Quantum Mechanics of Relativistic Systems:':
        sections:
        - '- Section: 12.1 Klein-Gordon Equation:':
            subsections:
            - 12.1a Derivation of the Klein-Gordon Equation
            - 12.1b Solutions for Various Potentials
            - 12.1c Negative Energy Solutions
        - '- Section: 12.2 Dirac Equation:':
            subsections:
            - 12.2a Derivation of the Dirac Equation
            - 12.2b Solutions for Various Potentials
            - 12.2c Negative Energy Solutions and Hole Theory
        - '- Section: 12.3 Quantum Electrodynamics:':
            subsections:
            - 12.3a Interaction of Light and Matter
            - 12.3b Feynman Diagrams
            - 12.3c Lamb Shift
        - '- Section: 12.4 Quantum Field Theory:':
            subsections:
            - 12.4a Second Quantization
            - 12.4b Creation and Annihilation Operators
            - 12.4c Quantum Electrodynamics
    - '- Chapter 13: Quantum Mechanics of Systems with Spin:':
        sections:
        - '- Section: 13.1 Spin-1/2 Systems:':
            subsections:
            - 13.1a Spinors
            - 13.1b Pauli Matrices
            - 13.1c Spin-Orbit Interaction
        - '- Section: 13.2 Spin-1 Systems:':
            subsections:
            - 13.2a Spin-1 Matrices
            - 13.2b Spin-1 States
            - 13.2c Quadrupole Interaction
        - '- Section: 13.3 Addition of Angular Momenta:':
            subsections:
            - 13.3a Clebsch-Gordan Coefficients
            - 13.3b Wigner-Eckart Theorem
            - 13.3c Hyperfine Structure
        - '- Section: 13.4 Quantum Mechanics of the Electron:':
            subsections:
            - 13.4a Dirac Equation
            - 13.4b Spin and Magnetic Moment of the Electron
            - 13.4c Zitterbewegung
    - '- Chapter 14: Quantum Mechanics of Relativistic Systems:':
        sections:
        - '- Section: 14.1 Klein-Gordon Equation:':
            subsections:
            - 14.1a Derivation of the Klein-Gordon Equation
            - 14.1b Solutions for Various Potentials
            - 14.1c Negative Energy Solutions
        - '- Section: 14.2 Dirac Equation:':
            subsections:
            - 14.2a Derivation of the Dirac Equation
            - 14.2b Solutions for Various Potentials
            - 14.2c Negative Energy Solutions and Hole Theory
        - '- Section: 14.3 Quantum Electrodynamics:':
            subsections:
            - 14.3a Interaction of Light and Matter
            - 14.3b Feynman Diagrams
            - 14.3c Lamb Shift
        - '- Section: 14.4 Quantum Field Theory:':
            subsections:
            - 14.4a Second Quantization
            - 14.4b Creation and Annihilation Operators
            - 14.4c Quantum Electrodynamics
    - '- Chapter 15: Quantum Mechanics of Systems with Spin:':
        sections:
        - '- Section: 15.1 Spin-1/2 Systems:':
            subsections:
            - 15.1a Spinors
            - 15.1b Pauli Matrices
            - 15.1c Spin-Orbit Interaction
        - '- Section: 15.2 Spin-1 Systems:':
            subsections:
            - 15.2a Spin-1 Matrices
            - 15.2b Spin-1 States
            - 15.2c Quadrupole Interaction
        - '- Section: 15.3 Addition of Angular Momenta:':
            subsections:
            - 15.3a Clebsch-Gordan Coefficients
            - 15.3b Wigner-Eckart Theorem
            - 15.3c Hyperfine Structure
        - '- Section: 15.4 Quantum Mechanics of the Electron:':
            subsections:
            - 15.4a Dirac Equation
            - 15.4b Spin and Magnetic Moment of the Electron
            - 15.4c Zitterbewegung
    - '- Chapter 16: Quantum Mechanics of Relativistic Systems:':
        sections:
        - '- Section: 16.1 Klein-Gordon Equation:':
            subsections:
            - 16.1a Derivation of the Klein-Gordon Equation
            - 16.1b Solutions for Various Potentials
            - 16.1c Negative Energy Solutions
        - '- Section: 16.2 Dirac Equation:':
            subsections:
            - 16.2a Derivation of the Dirac Equation
            - 16.2b Solutions for Various Potentials
            - 16.2c Negative Energy Solutions and Hole Theory
        - '- Section: 16.3 Quantum Electrodynamics:':
            subsections:
            - 16.3a Interaction of Light and Matter
            - 16.3b Feynman Diagrams
            - 16.3c Lamb Shift
        - '- Section: 16.4 Quantum Field Theory:':
            subsections:
            - 16.4a Second Quantization
            - 16.4b Creation and Annihilation Operators
            - 16.4c Quantum Electrodynamics
    - '- Chapter 17: Quantum Mechanics of Systems with Spin:':
        sections:
        - '- Section: 17.1 Spin-1/2 Systems:':
            subsections:
            - 17.1a Spinors
            - 17.1b Pauli Matrices
            - 17.1c Spin-Orbit Interaction
        - '- Section: 17.2 Spin-1 Systems:':
            subsections:
            - 17.2a Spin-1 Matrices
            - 17.2b Spin-1 States
            - 17.2c Quadrupole Interaction
        - '- Section: 17.3 Addition of Angular Momenta:':
            subsections:
            - 17.3a Clebsch-Gordan Coefficients
            - 17.3b Wigner-Eckart Theorem
            - 17.3c Hyperfine Structure
        - '- Section: 17.4 Quantum Mechanics of the Electron:':
            subsections:
            - 17.4a Dirac Equation
            - 17.4b Spin and Magnetic Moment of the Electron
            - 17.4c Zitterbewegung
    - '- Chapter 18: Quantum Mechanics of Relativistic Systems:':
        sections:
        - '- Section: 18.1 Klein-Gordon Equation:':
            subsections:
            - 18.1a Derivation of the Klein-Gordon Equation
            - 18.1b Solutions for Various Potentials
            - 18.1c Negative Energy Solutions
        - '- Section: 18.2 Dirac Equation:':
            subsections:
            - 18.2a Derivation of the Dirac Equation
            - 18.2b Solutions for Various Potentials
            - 18.2c Negative Energy Solutions and Hole Theory
        - '- Section:':
            subsections: []
