textbook:
  'Role of Science and Scientists in Collaborative Approaches to Environmental Policymaking: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: Introduction and Overview:':
        sections:
        - '- Section: 1.1 Goals and Scope of the Class:':
            subsections:
            - 1.1a Course Objectives
            - 1.1b Course Syllabus
            - 1.1c Expectations and Grading
        - '- Section: 1.2 Background of Guest Participants:':
            subsections:
            - 1.2a Guest Participant Profiles
            - 1.2b Guest Participant Contributions
            - 1.2c Interaction with Guest Participants
        - '- Section: 1.3 Traditional Role of Science in Society:':
            subsections:
            - 1.3a Historical Perspective
            - 1.3b Science and Public Policy
            - 1.3c Science and Education
        - '- Section: 1.4 Changing Role of Science in Contemporary Society:':
            subsections:
            - 1.4a Science and Technology
            - 1.4b Science and Media
            - 1.4c Science and Public Perception
    - '- Chapter 2: The Role of Science in Environmental Policy-Making:':
        sections:
        - '- Section: 2.1 Collaborative Processes for Policy Decisions:':
            subsections:
            - 2.1a Stakeholder Engagement
            - 2.1b Consensus Building
            - 2.1c Conflict Resolution
        - '- Section: 2.2 Collaborative Learning and Citizen Involvement:':
            subsections:
            - 2.2a Public Participation in Science
            - 2.2b Citizen Science Initiatives
            - 2.2c Impact of Citizen Involvement
    - '- Chapter 3: Collaborative Approaches to Adaptive Management and Governance:':
        sections:
        - '- Section: 3.1 Adaptive Management:':
            subsections:
            - 3.1a Principles of Adaptive Management
            - 3.1b Case Studies in Adaptive Management
            - 3.1c Challenges in Adaptive Management
        - '- Section: 3.2 Adaptive Governance:':
            subsections:
            - 3.2a Governance Structures
            - 3.2b Governance and Policy
            - 3.2c Case Studies in Adaptive Governance
        - '- Section: 3.3 Ecosystem Based Management:':
            subsections:
            - 3.3a Principles of Ecosystem Based Management
            - 3.3b Ecosystem Services
            - 3.3c Case Studies in Ecosystem Based Management
    - '- Chapter 4: The Role of the Citizen - Local and Indigenous Knowledge:':
        sections:
        - '- Section: 4.1 Importance of Local and Indigenous Knowledge:':
            subsections:
            - 4.1a Understanding Local and Indigenous Knowledge
            - 4.1b Role in Environmental Management
            - 4.1c Case Studies
    - '- Chapter 5: Preliminary Student Presentations:':
        sections:
        - '- Section: 5.1 Presentation Topics:':
            subsections:
            - 5.1a Topic Selection
            - 5.1b Presentation Guidelines
            - 5.1c Evaluation Criteria
    - '- Chapter 6: Last Day of Class:':
        sections:
        - '- Section: 6.1 Course Wrap-up:':
            subsections:
            - 6.1a Course Summary
            - 6.1b Final Exam Information
            - 6.1c Course Feedback
