textbook:
  'Integrated Chemical Engineering II: A Comprehensive Guide to Process Design, CO2 Capture, and Power Plant Retrofitting":':
    chapters:
    - '- Chapter 1: Introduction: Global Climate and the CO2 Problem:':
        sections:
        - '- Section: 1.1 Course Overview and Process Design:':
            subsections:
            - 1.1a Introduction to Course
            - 1.1b Basics of Process Design
            - 1.1c Importance of Process Design
        - '- Section: 1.2 Literature Sources for Processes: How to Find Information:':
            subsections:
            - 1.2a Importance of Literature Sources
            - 1.2b How to Find Relevant Information
            - 1.2c Evaluating Sources
    - '- Chapter 2: Process Flowsheet Models:':
        sections:
        - "- Section: 2.1 An Introduction to AspenPlus\xAE:":
            subsections:
            - "2.1a Basics of AspenPlus\xAE"
            - "2.1b Applications of AspenPlus\xAE"
            - "2.1c Advanced Features of AspenPlus\xAE"
        - "- Section: 2.2 Reactor Modeling in AspenPlus\xAE:":
            subsections:
            - 2.2a Introduction to Reactor Modeling
            - "2.2b Using AspenPlus\xAE for Reactor Modeling"
            - 2.2c Case Studies in Reactor Modeling
        - '- Section: 2.3 Introduction to Analysis Tools:':
            subsections:
            - 2.3a Importance of Analysis Tools
            - 2.3b Overview of Analysis Tools
            - 2.3c Applications of Analysis Tools
    - '- Chapter 3: Process Engineering Economics:':
        sections:
        - '- Section: 3.1 Project Evaluation:':
            subsections:
            - 3.1a Basics of Project Evaluation
            - 3.1b Techniques for Project Evaluation
            - 3.1c Case Studies in Project Evaluation
        - '- Section: 3.2 Capital Cost Estimates: Introduction to CAPCOST Software Program:':
            subsections:
            - 3.2a Introduction to CAPCOST
            - 3.2b Using CAPCOST for Capital Cost Estimates
            - 3.2c Advanced Features of CAPCOST
    - '- Chapter 4: Physical Property Models:':
        sections:
        - '- Section: 4.1 Which One is Best?:':
            subsections:
            - 4.1a Introduction to Physical Property Models
            - 4.1b Comparing Different Models
            - 4.1c Case Studies in Physical Property Models
    - '- Chapter 5: Combustion Basics:':
        sections:
        - '- Section: 5.1 How CO2 is Formed:':
            subsections:
            - 5.1a Basics of Combustion
            - 5.1b Role of CO2 in Combustion
            - 5.1c Impact of CO2 on Environment
    - '- Chapter 6: Evaluation of Alternative CO2 Removal Schemes:':
        sections:
        - '- Section: 6.1 Comparing Efficiencies:':
            subsections:
            - 6.1a Introduction to CO2 Removal Schemes
            - 6.1b Evaluating Efficiency of Different Schemes
            - 6.1c Case Studies in CO2 Removal
    - '- Chapter 7: Hierarchical Design Methodology:':
        sections:
        - '- Section: 7.1 Reactor Modeling:':
            subsections:
            - 7.1a Basics of Reactor Modeling
            - 7.1b Techniques for Reactor Modeling
            - 7.1c Case Studies in Reactor Modeling
    - '- Chapter 8: Chemical Process Safety:':
        sections:
        - '- Section: 8.1 HAZOP Analyses:':
            subsections:
            - 8.1a Introduction to HAZOP
            - 8.1b Conducting HAZOP Analyses
            - 8.1c Case Studies in HAZOP Analyses
    - '- Chapter 9: Team Project Work:':
        sections:
        - '- Section: 9.1 Student Presentations:':
            subsections:
            - 9.1a Importance of Team Work
            - 9.1b Preparing for Presentations
            - 9.1c Evaluating Presentations
    - '- Chapter 10: Ammonia Stripping:':
        sections:
        - '- Section: 10.1 Assessment of the IGCC Concept:':
            subsections:
            - 10.1a Introduction to IGCC
            - 10.1b Evaluating IGCC Concept
            - 10.1c Case Studies in IGCC
    - '- Chapter 11: Amine Stripping:':
        sections:
        - '- Section: 11.1 Retrofitting Options for CO2 Capture:':
            subsections:
            - 11.1a Introduction to Retrofitting
            - 11.1b Options for CO2 Capture
            - 11.1c Evaluating Retrofitting Options
        - '- Section: 11.2 Amine Stripping Alternatives:':
            subsections:
            - 11.2a Basics of Amine Stripping
            - 11.2b Evaluating Amine Stripping Alternatives
            - 11.2c Case Studies in Amine Stripping
    - '- Chapter 12: Retrofitting of Existing Power Plants:':
        sections:
        - '- Section: 12.1 Chemical Looping Combustion:':
            subsections:
            - 12.1a Introduction to Chemical Looping Combustion
            - 12.1b Applications of Chemical Looping Combustion
            - 12.1c Case Studies in Chemical Looping Combustion
        - '- Section: 12.2 CO2 Liquefaction:':
            subsections:
            - 12.2a Basics of CO2 Liquefaction
            - 12.2b Applications of CO2 Liquefaction
            - 12.2c Case Studies in CO2 Liquefaction
        - '- Section: 12.3 Oxyfiring:':
            subsections:
            - 12.3a Introduction to Oxyfiring
            - 12.3b Applications of Oxyfiring
            - 12.3c Case Studies in Oxyfiring
        - '- Section: 12.4 Polygeneration:':
            subsections:
            - 12.4a Introduction to Polygeneration
            - 12.4b Applications of Polygeneration
            - 12.4c Case Studies in Polygeneration
        - '- Section: 12.5 Water Gas Shift Reaction:':
            subsections:
            - 12.5a Basics of Water Gas Shift Reaction
            - 12.5b Applications of Water Gas Shift Reaction
            - 12.5c Case Studies in Water Gas Shift Reaction
        - '- Section: 12.6 Retrofitting of Existing Power Plants:':
            subsections:
            - 12.6a Introduction to Retrofitting
            - 12.6b Techniques for Retrofitting
            - 12.6c Case Studies in Retrofitting
        - '- Section: 12.7 Chemical Looping Combustor:':
            subsections:
            - 12.7a Introduction to Chemical Looping Combustor
            - 12.7b Applications of Chemical Looping Combustor
            - 12.7c Case Studies in Chemical Looping Combustor
    - '- Chapter 13: Advanced Process Design:':
        sections:
        - '- Section: 13.1 Process Optimization:':
            subsections:
            - 13.1a Introduction to Process Optimization
            - 13.1b Techniques for Process Optimization
            - 13.1c Case Studies in Process Optimization
        - '- Section: 13.2 Process Simulation:':
            subsections:
            - 13.2a Introduction to Process Simulation
            - 13.2b Techniques for Process Simulation
            - 13.2c Case Studies in Process Simulation
        - '- Section: 13.3 Process Control:':
            subsections:
            - 13.3a Basics of Process Control
            - 13.3b Techniques for Process Control
            - 13.3c Case Studies in Process Control
    - '- Chapter 14: Advanced Reactor Modeling:':
        sections:
        - '- Section: 14.1 Non-Ideal Reactors:':
            subsections:
            - 14.1a Introduction to Non-Ideal Reactors
            - 14.1b Modeling Non-Ideal Reactors
            - 14.1c Case Studies in Non-Ideal Reactors
        - '- Section: 14.2 Catalysts in Reactors:':
            subsections:
            - 14.2a Introduction to Catalysts
            - 14.2b Role of Catalysts in Reactors
            - 14.2c Case Studies in Catalysts in Reactors
        - '- Section: 14.3 Advanced Reactor Design:':
            subsections:
            - 14.3a Introduction to Advanced Reactor Design
            - 14.3b Techniques for Advanced Reactor Design
            - 14.3c Case Studies in Advanced Reactor Design
    - '- Chapter 15: Advanced Process Economics:':
        sections:
        - '- Section: 15.1 Advanced Project Evaluation:':
            subsections:
            - 15.1a Introduction to Advanced Project Evaluation
            - 15.1b Techniques for Advanced Project Evaluation
            - 15.1c Case Studies in Advanced Project Evaluation
        - '- Section: 15.2 Advanced Capital Cost Estimates:':
            subsections:
            - 15.2a Introduction to Advanced Capital Cost Estimates
            - 15.2b Techniques for Advanced Capital Cost Estimates
            - 15.2c Case Studies in Advanced Capital Cost Estimates
        - '- Section: 15.3 Advanced Economic Analysis:':
            subsections:
            - 15.3a Introduction to Advanced Economic Analysis
            - 15.3b Techniques for Advanced Economic Analysis
            - 15.3c Case Studies in Advanced Economic Analysis
    - '- Chapter 16: Advanced Physical Property Models:':
        sections:
        - '- Section: 16.1 Advanced Physical Property Model Selection:':
            subsections:
            - 16.1a Introduction to Advanced Physical Property Model Selection
            - 16.1b Techniques for Advanced Physical Property Model Selection
            - 16.1c Case Studies in Advanced Physical Property Model Selection
        - '- Section: 16.2 Advanced Physical Property Model Evaluation:':
            subsections:
            - 16.2a Introduction to Advanced Physical Property Model Evaluation
            - 16.2b Techniques for Advanced Physical Property Model Evaluation
            - 16.2c Case Studies in Advanced Physical Property Model Evaluation
        - '- Section: 16.3 Advanced Physical Property Model Application:':
            subsections:
            - 16.3a Introduction to Advanced Physical Property Model Application
            - 16.3b Techniques for Advanced Physical Property Model Application
            - 16.3c Case Studies in Advanced Physical Property Model Application
    - '- Chapter 17: Advanced Combustion Basics:':
        sections:
        - '- Section: 17.1 Advanced CO2 Formation:':
            subsections:
            - 17.1a Introduction to Advanced CO2 Formation
            - 17.1b Techniques for Advanced CO2 Formation
            - 17.1c Case Studies in Advanced CO2 Formation
        - '- Section: 17.2 Advanced Combustion Techniques:':
            subsections:
            - 17.2a Introduction to Advanced Combustion Techniques
            - 17.2b Techniques for Advanced Combustion
            - 17.2c Case Studies in Advanced Combustion Techniques
        - '- Section: 17.3 Advanced Combustion Analysis:':
            subsections:
            - 17.3a Introduction to Advanced Combustion Analysis
            - 17.3b Techniques for Advanced Combustion Analysis
            - 17.3c Case Studies in Advanced Combustion Analysis
    - '- Chapter 18: Advanced CO2 Removal Schemes:':
        sections:
        - '- Section: 18.1 Advanced CO2 Removal Techniques:':
            subsections:
            - 18.1a Introduction to Advanced CO2 Removal Techniques
            - 18.1b Techniques for Advanced CO2 Removal
            - 18.1c Case Studies in Advanced CO2 Removal
        - '- Section: 18.2 Advanced CO2 Removal Evaluation:':
            subsections:
            - 18.2a Introduction to Advanced CO2 Removal Evaluation
            - 18.2b Techniques for Advanced CO2 Removal Evaluation
            - 18.2c Case Studies in Advanced CO2 Removal Evaluation
        - '- Section: 18.3 Advanced CO2 Removal Application:':
            subsections:
            - 18.3a Introduction to Advanced CO2 Removal Application
            - 18.3b Techniques for Advanced CO2 Removal Application
            - 18.3c Case Studies in Advanced CO2 Removal Application
    - '- Chapter 19: Advanced Hierarchical Design Methodology:':
        sections:
        - '- Section: 19.1 Advanced Reactor Modeling:':
            subsections:
            - 19.1a Introduction to Advanced Reactor Modeling
            - 19.1b Techniques for Advanced Reactor Modeling
            - 19.1c Case Studies in Advanced Reactor Modeling
        - '- Section: 19.2 Advanced Hierarchical Design Techniques:':
            subsections:
            - 19.2a Introduction to Advanced Hierarchical Design Techniques
            - 19.2b Techniques for Advanced Hierarchical Design
            - 19.2c Case Studies in Advanced Hierarchical Design
        - '- Section: 19.3 Advanced Hierarchical Design Application:':
            subsections:
            - 19.3a Introduction to Advanced Hierarchical Design Application
            - 19.3b Techniques for Advanced Hierarchical Design Application
            - 19.3c Case Studies in Advanced Hierarchical Design Application
    - '- Chapter 20: Advanced Chemical Process Safety:':
        sections:
        - '- Section: 20.1 Advanced HAZOP Analyses:':
            subsections:
            - 20.1a Introduction to Advanced HAZOP Analyses
            - 20.1b Techniques for Advanced HAZOP Analyses
            - 20.1c Case Studies in Advanced HAZOP Analyses
        - '- Section: 20.2 Advanced Chemical Process Safety Techniques:':
            subsections:
            - 20.2a Introduction to Advanced Chemical Process Safety Techniques
            - 20.2b Techniques for Advanced Chemical Process Safety
            - 20.2c Case Studies in Advanced Chemical Process Safety
        - '- Section: 20.3 Advanced Chemical Process Safety Application:':
            subsections:
            - 20.3a Introduction to Advanced Chemical Process Safety Application
            - 20.3b Techniques for Advanced Chemical Process Safety Application
            - 20.3c Case Studies in Advanced Chemical Process Safety Application
