textbook:
  'Special Studies in Urban Studies and Planning - The Cardener River Corridor Workshop":':
    chapters:
    - '- Chapter 1: Urban Planning and Design Principles:':
        sections:
        - '- Section: 1.1 Background material on urban planning:':
            subsections:
            - 1.1a Introduction to Urban Planning
            - 1.1b History of Urban Planning
            - 1.1c Key Concepts in Urban Planning
        - '- Section: 1.2 Urban Design Planning Model:':
            subsections:
            - 1.2a Understanding the Model
            - 1.2b Application of the Model
            - 1.2c Case Studies
        - '- Section: 1.3 Urban Design Principles:':
            subsections:
            - 1.3a Basic Principles
            - 1.3b Advanced Principles
            - 1.3c Principles in Practice
        - '- Section: 1.4 Cardener River Corridor Guiding Principles:':
            subsections:
            - 1.4a Introduction to the Cardener River Corridor
            - 1.4b Guiding Principles for Development
            - 1.4c Implementation of Principles
    - '- Chapter 2: Sustainable Development in Urban Areas:':
        sections:
        - '- Section: 2.1 Environmental considerations:':
            subsections:
            - 2.1a Understanding Environmental Impact
            - 2.1b Environmental Impact Assessment
            - 2.1c Mitigating Environmental Impact
        - '- Section: 2.2 Social and economic aspects:':
            subsections:
            - 2.2a Social Impact of Urban Development
            - 2.2b Economic Impact of Urban Development
            - 2.2c Balancing Social and Economic Aspects
        - '- Section: 2.3 Energy efficiency:':
            subsections:
            - 2.3a Importance of Energy Efficiency
            - 2.3b Strategies for Energy Efficiency
            - 2.3c Case Studies in Energy Efficiency
        - '- Section: 2.4 Green infrastructure:':
            subsections:
            - 2.4a Understanding Green Infrastructure
            - 2.4b Benefits of Green Infrastructure
            - 2.4c Implementing Green Infrastructure
    - '- Chapter 3: Transportation and Mobility:':
        sections:
        - '- Section: 3.1 Public transportation systems:':
            subsections:
            - 3.1a Types of Public Transportation
            - 3.1b Planning Public Transportation Systems
            - 3.1c Case Studies in Public Transportation
        - '- Section: 3.2 Bicycle infrastructure:':
            subsections:
            - 3.2a Importance of Bicycle Infrastructure
            - 3.2b Designing Bicycle Infrastructure
            - 3.2c Case Studies in Bicycle Infrastructure
        - '- Section: 3.3 Pedestrian-friendly design:':
            subsections:
            - 3.3a Principles of Pedestrian-friendly Design
            - 3.3b Implementing Pedestrian-friendly Design
            - 3.3c Case Studies in Pedestrian-friendly Design
        - '- Section: 3.4 Traffic management:':
            subsections:
            - 3.4a Understanding Traffic Management
            - 3.4b Traffic Management Strategies
            - 3.4c Case Studies in Traffic Management
    - '- Chapter 4: Community Engagement and Participation:':
        sections:
        - '- Section: 4.1 Stakeholder involvement:':
            subsections:
            - 4.1a Identifying Stakeholders
            - 4.1b Engaging Stakeholders
            - 4.1c Case Studies in Stakeholder Involvement
        - '- Section: 4.2 Public consultation processes:':
            subsections:
            - 4.2a Understanding Public Consultation
            - 4.2b Conducting Public Consultation
            - 4.2c Case Studies in Public Consultation
        - '- Section: 4.3 Collaborative decision-making:':
            subsections:
            - 4.3a Principles of Collaborative Decision-making
            - 4.3b Implementing Collaborative Decision-making
            - 4.3c Case Studies in Collaborative Decision-making
        - '- Section: 4.4 Participatory design:':
            subsections:
            - 4.4a Understanding Participatory Design
            - 4.4b Conducting Participatory Design
            - 4.4c Case Studies in Participatory Design
    - '- Chapter 5: Urban Resilience and Adaptation:':
        sections:
        - '- Section: 5.1 Climate change mitigation:':
            subsections:
            - 5.1a Understanding Climate Change Mitigation
            - 5.1b Strategies for Climate Change Mitigation
            - 5.1c Case Studies in Climate Change Mitigation
        - '- Section: 5.2 Disaster risk reduction:':
            subsections:
            - 5.2a Understanding Disaster Risk Reduction
            - 5.2b Strategies for Disaster Risk Reduction
            - 5.2c Case Studies in Disaster Risk Reduction
        - '- Section: 5.3 Resilient infrastructure:':
            subsections:
            - 5.3a Understanding Resilient Infrastructure
            - 5.3b Designing Resilient Infrastructure
            - 5.3c Case Studies in Resilient Infrastructure
        - '- Section: 5.4 Adaptive land use planning:':
            subsections:
            - 5.4a Understanding Adaptive Land Use Planning
            - 5.4b Implementing Adaptive Land Use Planning
            - 5.4c Case Studies in Adaptive Land Use Planning
    - '- Chapter 6: Economic Development and Revitalization:':
        sections:
        - '- Section: 6.1 Urban economic strategies:':
            subsections:
            - 6.1a Understanding Urban Economic Strategies
            - 6.1b Implementing Urban Economic Strategies
            - 6.1c Case Studies in Urban Economic Strategies
        - '- Section: 6.2 Brownfield redevelopment:':
            subsections:
            - 6.2a Understanding Brownfield Redevelopment
            - 6.2b Strategies for Brownfield Redevelopment
            - 6.2c Case Studies in Brownfield Redevelopment
        - '- Section: 6.3 Heritage preservation:':
            subsections:
            - 6.3a Understanding Heritage Preservation
            - 6.3b Strategies for Heritage Preservation
            - 6.3c Case Studies in Heritage Preservation
        - '- Section: 6.4 Small business support:':
            subsections:
            - 6.4a Understanding Small Business Support
            - 6.4b Strategies for Small Business Support
            - 6.4c Case Studies in Small Business Support
    - '- Chapter 7: Land Use and Zoning:':
        sections:
        - '- Section: 7.1 Mixed-use development:':
            subsections:
            - 7.1a Understanding Mixed-use Development
            - 7.1b Implementing Mixed-use Development
            - 7.1c Case Studies in Mixed-use Development
        - '- Section: 7.2 Zoning regulations:':
            subsections:
            - 7.2a Understanding Zoning Regulations
            - 7.2b Implementing Zoning Regulations
            - 7.2c Case Studies in Zoning Regulations
        - '- Section: 7.3 Urban growth boundaries:':
            subsections:
            - 7.3a Understanding Urban Growth Boundaries
            - 7.3b Implementing Urban Growth Boundaries
            - 7.3c Case Studies in Urban Growth Boundaries
        - '- Section: 7.4 Land parceling and subdivision:':
            subsections:
            - 7.4a Understanding Land Parceling and Subdivision
            - 7.4b Implementing Land Parceling and Subdivision
            - 7.4c Case Studies in Land Parceling and Subdivision
    - '- Chapter 8: Historic Preservation and Heritage Conservation:':
        sections:
        - '- Section: 8.1 Historic preservation policies:':
            subsections:
            - 8.1a Understanding Historic Preservation Policies
            - 8.1b Implementing Historic Preservation Policies
            - 8.1c Case Studies in Historic Preservation Policies
        - '- Section: 8.2 Heritage designation processes:':
            subsections:
            - 8.2a Understanding Heritage Designation Processes
            - 8.2b Implementing Heritage Designation Processes
            - 8.2c Case Studies in Heritage Designation Processes
        - '- Section: 8.3 Adaptive reuse of historic buildings:':
            subsections:
            - 8.3a Understanding Adaptive Reuse
            - 8.3b Implementing Adaptive Reuse
            - 8.3c Case Studies in Adaptive Reuse
        - '- Section: 8.4 Conservation of cultural landscapes:':
            subsections:
            - 8.4a Understanding Cultural Landscape Conservation
            - 8.4b Implementing Cultural Landscape Conservation
            - 8.4c Case Studies in Cultural Landscape Conservation
    - '- Chapter 9: Green and Blue Spaces:':
        sections:
        - '- Section: 9.1 Parks and recreational areas:':
            subsections:
            - 9.1a Understanding Parks and Recreational Areas
            - 9.1b Designing Parks and Recreational Areas
            - 9.1c Case Studies in Parks and Recreational Areas
        - '- Section: 9.2 Urban forests and green belts:':
            subsections:
            - 9.2a Understanding Urban Forests and Green Belts
            - 9.2b Implementing Urban Forests and Green Belts
            - 9.2c Case Studies in Urban Forests and Green Belts
        - '- Section: 9.3 Riverfront development:':
            subsections:
            - 9.3a Understanding Riverfront Development
            - 9.3b Implementing Riverfront Development
            - 9.3c Case Studies in Riverfront Development
        - '- Section: 9.4 Waterfront revitalization:':
            subsections:
            - 9.4a Understanding Waterfront Revitalization
            - 9.4b Implementing Waterfront Revitalization
            - 9.4c Case Studies in Waterfront Revitalization
    - '- Chapter 10: Urban Governance and Policy:':
        sections:
        - '- Section: 10.1 Urban planning legislation:':
            subsections:
            - 10.1a Understanding Urban Planning Legislation
            - 10.1b Implementing Urban Planning Legislation
            - 10.1c Case Studies in Urban Planning Legislation
        - '- Section: 10.2 Policy development and implementation:':
            subsections:
            - 10.2a Understanding Policy Development
            - 10.2b Implementing Policy
            - 10.2c Case Studies in Policy Development and Implementation
        - '- Section: 10.3 Interagency coordination:':
            subsections:
            - 10.3a Understanding Interagency Coordination
            - 10.3b Implementing Interagency Coordination
            - 10.3c Case Studies in Interagency Coordination
        - '- Section: 10.4 Public-private partnerships:':
            subsections:
            - 10.4a Understanding Public-private Partnerships
            - 10.4b Implementing Public-private Partnerships
            - 10.4c Case Studies in Public-private Partnerships
    - '- Chapter 11: Climate Change and Urbanization:':
        sections:
        - '- Section: 11.1 Impacts of climate change on urban areas:':
            subsections:
            - 11.1a Understanding Climate Change Impacts
            - 11.1b Mitigating Climate Change Impacts
            - 11.1c Case Studies in Climate Change Impacts
        - '- Section: 11.2 Urban heat island effect:':
            subsections:
            - 11.2a Understanding the Urban Heat Island Effect
            - 11.2b Mitigating the Urban Heat Island Effect
            - 11.2c Case Studies in the Urban Heat Island Effect
        - '- Section: 11.3 Mitigation strategies for climate change:':
            subsections:
            - 11.3a Understanding Mitigation Strategies
            - 11.3b Implementing Mitigation Strategies
            - 11.3c Case Studies in Mitigation Strategies
        - '- Section: 11.4 Urban planning for resilience to climate change:':
            subsections:
            - 11.4a Understanding Resilience Planning
            - 11.4b Implementing Resilience Planning
            - 11.4c Case Studies in Resilience Planning
    - '- Chapter 12: Housing and Social Equity:':
        sections:
        - '- Section: 12.1 Affordable housing policies and programs:':
            subsections:
            - 12.1a Understanding Affordable Housing Policies
            - 12.1b Implementing Affordable Housing Policies
            - 12.1c Case Studies in Affordable Housing Policies
        - '- Section: 12.2 Gentrification and displacement:':
            subsections:
            - 12.2a Understanding Gentrification and Displacement
            - 12.2b Mitigating Gentrification and Displacement
            - 12.2c Case Studies in Gentrification and Displacement
        - '- Section: 12.3 Social housing and inclusionary zoning:':
            subsections:
            - 12.3a Understanding Social Housing and Inclusionary Zoning
            - 12.3b Implementing Social Housing and Inclusionary Zoning
            - 12.3c Case Studies in Social Housing and Inclusionary Zoning
        - '- Section: 12.4 Accessible and inclusive housing design:':
            subsections:
            - 12.4a Understanding Accessible and Inclusive Design
            - 12.4b Implementing Accessible and Inclusive Design
            - 12.4c Case Studies in Accessible and Inclusive Design
    - '- Chapter 13: Urban Health and Well-being:':
        sections:
        - '- Section: 13.1 Healthy city planning and design:':
            subsections:
            - 13.1a Understanding Healthy City Planning
            - 13.1b Implementing Healthy City Planning
            - 13.1c Case Studies in Healthy City Planning
        - '- Section: 13.2 Access to healthcare and health services:':
            subsections:
            - 13.2a Understanding Access to Healthcare
            - 13.2b Implementing Access to Healthcare
            - 13.2c Case Studies in Access to Healthcare
        - '- Section: 13.3 Active transportation and walkable communities:':
            subsections:
            - 13.3a Understanding Active Transportation
            - 13.3b Implementing Active Transportation
            - 13.3c Case Studies in Active Transportation
        - '- Section: 13.4 Green spaces and mental health:':
            subsections:
            - 13.4a Understanding the Impact of Green Spaces
            - 13.4b Implementing Green Spaces for Mental Health
            - 13.4c Case Studies in Green Spaces and Mental Health
    - '- Chapter 14: Smart Cities and Technology:':
        sections:
        - '- Section: 14.1 Internet of Things (IoT) in urban planning:':
            subsections:
            - 14.1a Understanding IoT in Urban Planning
            - 14.1b Implementing IoT in Urban Planning
            - 14.1c Case Studies in IoT in Urban Planning
        - '- Section: 14.2 Smart infrastructure and connected systems:':
            subsections:
            - 14.2a Understanding Smart Infrastructure
            - 14.2b Implementing Smart Infrastructure
            - 14.2c Case Studies in Smart Infrastructure
        - '- Section: 14.3 Big data and urban analytics:':
            subsections:
            - 14.3a Understanding Big Data and Urban Analytics
            - 14.3b Implementing Big Data and Urban Analytics
            - 14.3c Case Studies in Big Data and Urban Analytics
        - '- Section: 14.4 Smart mobility and transportation solutions:':
            subsections:
            - 14.4a Understanding Smart Mobility
            - 14.4b Implementing Smart Mobility
            - 14.4c Case Studies in Smart Mobility
    - '- Chapter 15: Cultural Diversity and Urban Identity:':
        sections:
        - '- Section: 15.1 Cultural diversity in urban contexts:':
            subsections:
            - 15.1a Understanding Cultural Diversity in Urban Contexts
            - 15.1b Implementing Cultural Diversity in Urban Contexts
            - 15.1c Case Studies in Cultural Diversity in Urban Contexts
        - '- Section: 15.2 Ethnic enclaves and urban neighborhoods:':
            subsections:
            - 15.2a Understanding Ethnic Enclaves and Urban Neighborhoods
            - 15.2b Implementing Ethnic Enclaves and Urban Neighborhoods
            - 15.2c Case Studies in Ethnic Enclaves and Urban Neighborhoods
        - '- Section: 15.3 Cultural heritage and urban identity:':
            subsections:
            - 15.3a Understanding Cultural Heritage and Urban Identity
            - 15.3b Implementing Cultural Heritage and Urban Identity
            - 15.3c Case Studies in Cultural Heritage and Urban Identity
        - '- Section: 15.4 Public art and placemaking:':
            subsections:
            - 15.4a Understanding Public Art and Placemaking
            - 15.4b Implementing Public Art and Placemaking
            - 15.4c Case Studies in Public Art and Placemaking
    - '- Chapter 16: Urban Economics and Finance:':
        sections:
        - '- Section: 16.1 Economic development strategies for cities:':
            subsections:
            - 16.1a Understanding Economic Development Strategies
            - 16.1b Implementing Economic Development Strategies
            - 16.1c Case Studies in Economic Development Strategies
        - '- Section: 16.2 Real estate markets and urban development:':
            subsections:
            - 16.2a Understanding Real Estate Markets
            - 16.2b Implementing Real Estate Development
            - 16.2c Case Studies in Real Estate Development
        - '- Section: 16.3 Public-private partnerships in urban projects:':
            subsections:
            - 16.3a Understanding Public-private Partnerships
            - 16.3b Implementing Public-private Partnerships
