textbook:
  'Fluid Dynamics and Environmental Flows: Theory and Applications":':
    chapters:
    - '- Chapter 1: Basics:':
        sections:
        - '- Section: 1.1 Eulerian and Lagrangian Descriptions of Fluid Motion:':
            subsections:
            - 1.1a Introduction to Eulerian and Lagrangian Descriptions
            - 1.1b Differences and Applications
            - 1.1c Case Studies
        - '- Section: 1.2 Kinematics, Strain and Vorticity:':
            subsections:
            - 1.2a Definition and Importance of Kinematics
            - 1.2b Understanding Strain
            - 1.2c Vorticity in Fluid Dynamics
        - '- Section: 1.3 Kinematic Transport Theorem and Consequences:':
            subsections:
            - 1.3a Introduction to Kinematic Transport Theorem
            - 1.3b Consequences and Applications
            - 1.3c Practical Examples
        - "- Section: 1.4 Forces in the Fluid, Stresses and Cauchy\u2019s Law:":
            subsections:
            - 1.4a Understanding Forces in Fluids
            - 1.4b Stresses in Fluid Dynamics
            - "1.4c Cauchy\u2019s Law and its Importance"
        - '- Section: 1.5 Momentum Conservation Law:':
            subsections:
            - 1.5a Introduction to Momentum Conservation
            - 1.5b Applications in Fluid Dynamics
            - 1.5c Case Studies and Examples
        - '- Section: 1.6 Stress and Strain, Navier-Stokes Equations:':
            subsections:
            - 1.6a Understanding Stress and Strain
            - 1.6b Introduction to Navier-Stokes Equations
            - 1.6c Applications and Importance
    - '- Chapter 2: Simple Deductions:':
        sections:
        - '- Section: 2.1 Vorticity Theorems for Homogeneous and Stratified Fluids:':
            subsections:
            - 2.1a Introduction to Vorticity Theorems
            - 2.1b Homogeneous and Stratified Fluids
            - 2.1c Practical Applications
        - "- Section: 2.2 Rayleigh Problem \u2013 Where Does Vorticity Come From?:":
            subsections:
            - 2.2a Understanding the Rayleigh Problem
            - 2.2b Origin of Vorticity
            - 2.2c Case Studies and Examples
        - '- Section: 2.3 Scaling and Approximations:':
            subsections:
            - 2.3a Basics of Scaling in Fluid Dynamics
            - 2.3b Understanding Approximations
            - 2.3c Practical Applications
        - '- Section: 2.4 Slow Spreading of a Mud Layer on an Incline:':
            subsections:
            - 2.4a Understanding the Phenomenon
            - 2.4b Mathematical Modelling
            - 2.4c Practical Implications
        - '- Section: 2.5 Selective Withdrawal into a Line Sink, Boundary Layer Approximation and Similarity Solution:':
            subsections:
            - 2.5a Understanding Selective Withdrawal
            - 2.5b Boundary Layer Approximation
            - 2.5c Similarity Solutions and Applications
        - '- Section: 2.6 Stokes Flow Past a Sphere:':
            subsections:
            - 2.6a Introduction to Stokes Flow
            - 2.6b Mathematical Modelling of Flow Past a Sphere
            - 2.6c Practical Applications and Examples
        - '- Section: 2.7 Mechanics of Aerosols:':
            subsections:
            - 2.7a Understanding Aerosols
            - 2.7b Aerosol Mechanics in Fluid Dynamics
            - 2.7c Practical Implications and Examples
        - '- Section: 2.8 Inviscid Irrotational Flows of a Homogeneous Fluid:':
            subsections:
            - 2.8a Introduction to Inviscid Irrotational Flows
            - 2.8b Understanding Homogeneous Fluids
            - 2.8c Practical Applications and Examples
        - "- Section: 2.9 Bernoulli\u2019s Theorems for Inviscid Homogeneous Fluids:":
            subsections:
            - "2.9a Understanding Bernoulli\u2019s Theorems"
            - 2.9b Applications in Inviscid Homogeneous Fluids
            - 2.9c Case Studies and Examples
        - '- Section: 2.10 Example of Steady Boundary Layer; The Laminar Jet:':
            subsections:
            - 2.10a Understanding Steady Boundary Layers
            - '2.10b The Laminar Jet: A Case Study'
            - 2.10c Practical Implications and Examples
