textbook:
  'Revitalizing Urban Main Streets: Strategies for Mission Hill & Egleston Square, Boston":':
    chapters:
    - '- Chapter 1: Introduction and Overview:':
        sections:
        - '- Section: 1.1 Urban Neighborhood Decline: Causes, Consequences, Challenges:':
            subsections:
            - 1.1a Causes of Urban Neighborhood Decline
            - 1.1b Consequences of Urban Neighborhood Decline
            - 1.1c Challenges in Urban Neighborhood Revitalization
        - '- Section: 1.2 Introduction to Main Street Sites/Issues:':
            subsections:
            - 1.2a Overview of Main Street Sites
            - 1.2b Identifying Main Street Issues
            - 1.2c Strategies for Addressing Main Street Issues
    - '- Chapter 2: Revitalization Strategies I:':
        sections:
        - '- Section: 2.1 Project Discussion:':
            subsections:
            - 2.1a Identifying Project Goals
            - 2.1b Project Planning and Design
            - 2.1c Project Implementation and Evaluation
        - '- Section: 2.2 Economic Planning Tools II: Retail Market Analysis and Economic Planning:':
            subsections:
            - 2.2a Understanding Retail Market Analysis
            - 2.2b Economic Planning for Retail Development
            - 2.2c Case Studies in Retail Market Analysis and Economic Planning
        - '- Section: 2.3 Physical Design Tools II: Streetscape:':
            subsections:
            - 2.3a Understanding Streetscape Design
            - 2.3b Tools for Streetscape Design
            - 2.3c Case Studies in Streetscape Design
    - '- Chapter 3: Revitalization Strategies II:':
        sections:
        - '- Section: 3.1 Economic Planning Tools III: Asset and Capacity Assessment:':
            subsections:
            - 3.1a Understanding Asset and Capacity Assessment
            - 3.1b Tools for Asset and Capacity Assessment
            - 3.1c Case Studies in Asset and Capacity Assessment
        - '- Section: 3.2 Physical Design Tools III: Image and Neighborhood Form:':
            subsections:
            - 3.2a Understanding Image and Neighborhood Form
            - 3.2b Tools for Designing Image and Neighborhood Form
            - 3.2c Case Studies in Image and Neighborhood Form Design
        - '- Section: 3.3 Egleston Square Team Presentation:':
            subsections:
            - 3.3a Presentation of Egleston Square Revitalization Plan
            - 3.3b Discussion and Feedback on Egleston Square Plan
            - 3.3c Next Steps for Egleston Square Revitalization
        - '- Section: 3.4 Mission Hill Team Presentation:':
            subsections:
            - 3.4a Presentation of Mission Hill Revitalization Plan
            - 3.4b Discussion and Feedback on Mission Hill Plan
            - 3.4c Next Steps for Mission Hill Revitalization
    - '- Chapter 4: Synthesis:':
        sections:
        - '- Section: 4.1 In-class Work - Proposals for moving forward:':
            subsections:
            - 4.1a Review of Revitalization Strategies
            - 4.1b Development of Proposals
            - 4.1c Presentation and Discussion of Proposals
        - '- Section: 4.2 Client Presentations:':
            subsections:
            - 4.2a Preparation for Client Presentations
            - 4.2b Conducting Client Presentations
            - 4.2c Feedback and Next Steps after Client Presentations
    - '- Chapter 5: Policies and Interventions:':
        sections:
        - '- Section: 5.1 Marketing and Promotion:':
            subsections:
            - 5.1a Understanding Marketing and Promotion in Urban Revitalization
            - 5.1b Strategies for Marketing and Promotion
            - 5.1c Case Studies in Marketing and Promotion
        - '- Section: 5.2 Business Development, Retention, and Attraction:':
            subsections:
            - 5.2a Understanding Business Development, Retention, and Attraction
            - 5.2b Strategies for Business Development, Retention, and Attraction
            - 5.2c Case Studies in Business Development, Retention, and Attraction
        - '- Section: 5.3 Development:':
            subsections:
            - 5.3a Understanding Urban Development
            - 5.3b Strategies for Urban Development
            - 5.3c Case Studies in Urban Development
        - '- Section: 5.4 Transit-Oriented Development:':
            subsections:
            - 5.4a Understanding Transit-Oriented Development
            - 5.4b Strategies for Transit-Oriented Development
            - 5.4c Case Studies in Transit-Oriented Development
    - '- Chapter 6: Design and Zoning Guidelines:':
        sections:
        - '- Section: 6.1 Safety and Sanitation:':
            subsections:
            - 6.1a Understanding Safety and Sanitation in Urban Revitalization
            - 6.1b Strategies for Improving Safety and Sanitation
            - 6.1c Case Studies in Safety and Sanitation Improvements
        - '- Section: 6.2 Organization and Capacity Building:':
            subsections:
            - 6.2a Understanding Organization and Capacity Building
            - 6.2b Strategies for Organization and Capacity Building
            - 6.2c Case Studies in Organization and Capacity Building
    - '- Chapter 7: Presentation of Draft Plans:':
        sections:
        - '- Section: 7.1 Presentation of Draft Plans:':
            subsections:
            - 7.1a Preparation for Draft Plan Presentation
            - 7.1b Conducting Draft Plan Presentation
            - 7.1c Feedback and Revisions to Draft Plans
    - '- Chapter 8: Presentations of Final Plans to Clients:':
        sections:
        - '- Section: 8.1 Presentations of Final Plans to Clients:':
            subsections:
            - 8.1a Preparation for Final Plan Presentation
            - 8.1b Conducting Final Plan Presentation
            - 8.1c Feedback and Next Steps after Final Plan Presentation
    - '- Chapter 9: Course Conclusion/Reflections:':
        sections:
        - '- Section: 9.1 Final Reports/Plans:':
            subsections:
            - 9.1a Preparation of Final Reports/Plans
            - 9.1b Submission of Final Reports/Plans
            - 9.1c Reflections on the Course and Next Steps
    - '- Chapter 10: Urban Revitalization Case Studies:':
        sections:
        - '- Section: 10.1 Case Study 1:':
            subsections:
            - 10.1a Overview of Case Study 1
            - 10.1b Lessons Learned from Case Study 1
            - 10.1c Application of Case Study 1 to Main Street Revitalization
        - '- Section: 10.2 Case Study 2:':
            subsections:
            - 10.2a Overview of Case Study 2
            - 10.2b Lessons Learned from Case Study 2
            - 10.2c Application of Case Study 2 to Main Street Revitalization
        - '- Section: 10.3 Case Study 3:':
            subsections:
            - 10.3a Overview of Case Study 3
            - 10.3b Lessons Learned from Case Study 3
            - 10.3c Application of Case Study 3 to Main Street Revitalization
        - '- Section: 10.4 Case Study 4:':
            subsections:
            - 10.4a Overview of Case Study 4
            - 10.4b Lessons Learned from Case Study 4
            - 10.4c Application of Case Study 4 to Main Street Revitalization
    - '- Chapter 11: Urban Revitalization Theories:':
        sections:
        - '- Section: 11.1 Theory 1:':
            subsections:
            - 11.1a Overview of Theory 1
            - 11.1b Application of Theory 1 to Urban Revitalization
            - 11.1c Critiques of Theory 1
        - '- Section: 11.2 Theory 2:':
            subsections:
            - 11.2a Overview of Theory 2
            - 11.2b Application of Theory 2 to Urban Revitalization
            - 11.2c Critiques of Theory 2
        - '- Section: 11.3 Theory 3:':
            subsections:
            - 11.3a Overview of Theory 3
            - 11.3b Application of Theory 3 to Urban Revitalization
            - 11.3c Critiques of Theory 3
        - '- Section: 11.4 Theory 4:':
            subsections:
            - 11.4a Overview of Theory 4
            - 11.4b Application of Theory 4 to Urban Revitalization
            - 11.4c Critiques of Theory 4
    - '- Chapter 12: Urban Revitalization Tools and Techniques:':
        sections:
        - '- Section: 12.1 Tool/Technique 1:':
            subsections:
            - 12.1a Overview of Tool/Technique 1
            - 12.1b Application of Tool/Technique 1 to Urban Revitalization
            - 12.1c Case Studies in the Use of Tool/Technique 1
        - '- Section: 12.2 Tool/Technique 2:':
            subsections:
            - 12.2a Overview of Tool/Technique 2
            - 12.2b Application of Tool/Technique 2 to Urban Revitalization
            - 12.2c Case Studies in the Use of Tool/Technique 2
        - '- Section: 12.3 Tool/Technique 3:':
            subsections:
            - 12.3a Overview of Tool/Technique 3
            - 12.3b Application of Tool/Technique 3 to Urban Revitalization
            - 12.3c Case Studies in the Use of Tool/Technique 3
        - '- Section: 12.4 Tool/Technique 4:':
            subsections:
            - 12.4a Overview of Tool/Technique 4
            - 12.4b Application of Tool/Technique 4 to Urban Revitalization
            - 12.4c Case Studies in the Use of Tool/Technique 4
    - '- Chapter 13: Urban Revitalization Stakeholders:':
        sections:
        - '- Section: 13.1 Stakeholder 1:':
            subsections:
            - 13.1a Overview of Stakeholder 1
            - 13.1b Role of Stakeholder 1 in Urban Revitalization
            - 13.1c Case Studies in the Involvement of Stakeholder 1
        - '- Section: 13.2 Stakeholder 2:':
            subsections:
            - 13.2a Overview of Stakeholder 2
            - 13.2b Role of Stakeholder 2 in Urban Revitalization
            - 13.2c Case Studies in the Involvement of Stakeholder 2
        - '- Section: 13.3 Stakeholder 3:':
            subsections:
            - 13.3a Overview of Stakeholder 3
            - 13.3b Role of Stakeholder 3 in Urban Revitalization
            - 13.3c Case Studies in the Involvement of Stakeholder 3
        - '- Section: 13.4 Stakeholder 4:':
            subsections:
            - 13.4a Overview of Stakeholder 4
            - 13.4b Role of Stakeholder 4 in Urban Revitalization
            - 13.4c Case Studies in the Involvement of Stakeholder 4
    - '- Chapter 14: Urban Revitalization Funding and Financing:':
        sections:
        - '- Section: 14.1 Funding Source 1:':
            subsections:
            - 14.1a Overview of Funding Source 1
            - 14.1b Application of Funding Source 1 to Urban Revitalization
            - 14.1c Case Studies in the Use of Funding Source 1
        - '- Section: 14.2 Funding Source 2:':
            subsections:
            - 14.2a Overview of Funding Source 2
            - 14.2b Application of Funding Source 2 to Urban Revitalization
            - 14.2c Case Studies in the Use of Funding Source 2
        - '- Section: 14.3 Funding Source 3:':
            subsections:
            - 14.3a Overview of Funding Source 3
            - 14.3b Application of Funding Source 3 to Urban Revitalization
            - 14.3c Case Studies in the Use of Funding Source 3
        - '- Section: 14.4 Funding Source 4:':
            subsections:
            - 14.4a Overview of Funding Source 4
            - 14.4b Application of Funding Source 4 to Urban Revitalization
            - 14.4c Case Studies in the Use of Funding Source 4
    - '- Chapter 15: Urban Revitalization Evaluation and Assessment:':
        sections:
        - '- Section: 15.1 Evaluation Method 1:':
            subsections:
            - 15.1a Overview of Evaluation Method 1
            - 15.1b Application of Evaluation Method 1 to Urban Revitalization
            - 15.1c Case Studies in the Use of Evaluation Method 1
        - '- Section: 15.2 Evaluation Method 2:':
            subsections:
            - 15.2a Overview of Evaluation Method 2
            - 15.2b Application of Evaluation Method 2 to Urban Revitalization
            - 15.2c Case Studies in the Use of Evaluation Method 2
        - '- Section: 15.3 Evaluation Method 3:':
            subsections:
            - 15.3a Overview of Evaluation Method 3
            - 15.3b Application of Evaluation Method 3 to Urban Revitalization
            - 15.3c Case Studies in the Use of Evaluation Method 3
        - '- Section: 15.4 Evaluation Method 4:':
            subsections:
            - 15.4a Overview of Evaluation Method 4
            - 15.4b Application of Evaluation Method 4 to Urban Revitalization
            - 15.4c Case Studies in the Use of Evaluation Method 4
    - '- Chapter 16: Urban Revitalization and Sustainability:':
        sections:
        - '- Section: 16.1 Sustainability Principle 1:':
            subsections:
            - 16.1a Overview of Sustainability Principle 1
            - 16.1b Application of Sustainability Principle 1 to Urban Revitalization
            - 16.1c Case Studies in the Use of Sustainability Principle 1
        - '- Section: 16.2 Sustainability Principle 2:':
            subsections:
            - 16.2a Overview of Sustainability Principle 2
            - 16.2b Application of Sustainability Principle 2 to Urban Revitalization
            - 16.2c Case Studies in the Use of Sustainability Principle 2
        - '- Section: 16.3 Sustainability Principle 3:':
            subsections:
            - 16.3a Overview of Sustainability Principle 3
            - 16.3b Application of Sustainability Principle 3 to Urban Revitalization
            - 16.3c Case Studies in the Use of Sustainability Principle 3
        - '- Section: 16.4 Sustainability Principle 4:':
            subsections:
            - 16.4a Overview of Sustainability Principle 4
            - 16.4b Application of Sustainability Principle 4 to Urban Revitalization
            - 16.4c Case Studies in the Use of Sustainability Principle 4
    - '- Chapter 17: Urban Revitalization and Equity:':
        sections:
        - '- Section: 17.1 Equity Principle 1:':
            subsections:
            - 17.1a Overview of Equity Principle 1
            - 17.1b Application of Equity Principle 1 to Urban Revitalization
            - 17.1c Case Studies in the Use of Equity Principle 1
        - '- Section: 17.2 Equity Principle 2:':
            subsections:
            - 17.2a Overview of Equity Principle 2
            - 17.2b Application of Equity Principle 2 to Urban Revitalization
            - 17.2c Case Studies in the Use of Equity Principle 2
        - '- Section: 17.3 Equity Principle 3:':
            subsections:
            - 17.3a Overview of Equity Principle 3
            - 17.3b Application of Equity Principle 3 to Urban Revitalization
            - 17.3c Case Studies in the Use of Equity Principle 3
        - '- Section: 17.4 Equity Principle 4:':
            subsections:
            - 17.4a Overview of Equity Principle 4
            - 17.4b Application of Equity Principle 4 to Urban Revitalization
            - 17.4c Case Studies in the Use of Equity Principle 4
    - '- Chapter 18: Urban Revitalization and Resilience:':
        sections:
        - '- Section: 18.1 Resilience Principle 1:':
            subsections:
            - 18.1a Overview of Resilience Principle 1
            - 18.1b Application of Resilience Principle 1 to Urban Revitalization
            - 18.1c Case Studies in the Use of Resilience Principle 1
        - '- Section: 18.2 Resilience Principle 2:':
            subsections:
            - 18.2a Overview of Resilience Principle 2
            - 18.2b Application of Resilience Principle 2 to Urban Revitalization
            - 18.2c Case Studies in the Use of Resilience Principle 2
        - '- Section: 18.3 Resilience Principle 3:':
            subsections:
            - 18.3a Overview of Resilience Principle 3
            - 18.3b Application of Resilience Principle 3 to Urban Revitalization
            - 18.3c Case Studies in the Use of Resilience Principle 3
        - '- Section: 18.4 Resilience Principle 4:':
            subsections:
            - 18.4a Overview of Resilience Principle 4
            - 18.4b Application of Resilience Principle 4 to Urban Revitalization
            - 18.4c Case Studies in the Use of Resilience Principle 4
    - '- Chapter 19: Urban Revitalization and Innovation:':
        sections:
        - '- Section: 19.1 Innovation Principle 1:':
            subsections:
            - 19.1a Overview of Innovation Principle 1
            - 19.1b Application of Innovation Principle 1 to Urban Revitalization
            - 19.1c Case Studies in the Use of Innovation Principle 1
        - '- Section: 19.2 Innovation Principle 2:':
            subsections:
            - 19.2a Overview of Innovation Principle 2
            - 19.2b Application of Innovation Principle 2 to Urban Revitalization
            - 19.2c Case Studies in the Use of Innovation Principle 2
        - '- Section: 19.3 Innovation Principle 3:':
            subsections:
            - 19.3a Overview of Innovation Principle 3
            - 19.3b Application of Innovation Principle 3 to Urban Revitalization
            - 19.3c Case Studies in the Use of Innovation Principle 3
        - '- Section: 19.4 Innovation Principle 4:':
            subsections:
            - 19.4a Overview of Innovation Principle 4
            - 19.4b Application of Innovation Principle 4 to Urban Revitalization
            - 19.4c Case Studies in the Use of Innovation Principle 4
    - '- Chapter 20: Urban Revitalization and the Future:':
        sections:
        - '- Section: 20.1 Future Trends in Urban Revitalization:':
            subsections:
            - 20.1a Identifying Future Trends
            - 20.1b Implications of Future Trends for Urban Revitalization
            - 20.1c Strategies for Adapting to Future Trends
        - '- Section: 20.2 Future Challenges in Urban Revitalization:':
            subsections:
            - 20.2a Identifying Future Challenges
            - 20.2b Implications of Future Challenges for Urban Revitalization
            - 20.2c Strategies for Addressing Future Challenges
        - '- Section: 20.3 Future Opportunities in Urban Revitalization:':
            subsections:
            - 20.3a Identifying Future Opportunities
            - 20.3b Implications of Future Opportunities for Urban Revitalization
            - 20.3c Strategies for Seizing Future Opportunities
        - '- Section: 20.4 The Future of Urban Revitalization:':
            subsections:
            - 20.4a Predictions for the Future of Urban Revitalization
            - 20.4b Preparing for the Future of Urban Revitalization
            - 20.4c Case Studies in Future-Focused Urban Revitalization
