textbook:
  'Dialogue in Art, Architecture, and Urbanism: Exploring the Intersection of Creativity and the Built Environment":':
    chapters:
    - '- Chapter 1: Introduction and Overview:':
        sections:
        - '- Section: 1.1 Slideshow of examples of Public Artworks:':
            subsections:
            - 1.1a Overview of Public Artworks
            - 1.1b Analysis of Public Artworks
            - 1.1c Impact of Public Artworks
        - "- Section: 1.2 Analysis of Muntadas\u2019 own work in relation to public art:":
            subsections:
            - 1.2a Introduction to Muntadas' Work
            - 1.2b Analysis of Muntadas' Work
            - 1.2c Muntadas' Work in Public Art Context
        - '- Section: 1.3 Understanding the role of dialogue in art, architecture, and urbanism:':
            subsections:
            - 1.3a Definition of Dialogue in Art
            - 1.3b Role of Dialogue in Architecture
            - 1.3c Role of Dialogue in Urbanism
    - '- Chapter 2: Showcasing Student Work:':
        sections:
        - '- Section: 2.1 Presentation of previous work by students:':
            subsections:
            - 2.1a Overview of Student Work
            - 2.1b Analysis of Student Work
            - 2.1c Impact of Student Work
        - '- Section: 2.2 Analysis and critique of student work by instructors and peers:':
            subsections:
            - 2.2a Instructor Critique of Student Work
            - 2.2b Peer Critique of Student Work
            - 2.2c Impact of Critique on Student Work
    - '- Chapter 3: Collaborations between Artists and Architects:':
        sections:
        - "- Section: 3.1 Case study: Acconci + Holl\u2019s Storefront for Art and Architecture:":
            subsections:
            - "3.1a Overview of Acconci + Holl\u2019s Storefront"
            - "3.1b Analysis of Acconci + Holl\u2019s Storefront"
            - "3.1c Impact of Acconci + Holl\u2019s Storefront"
        - "- Section: 3.2 Case study: Barbara Kruger\u2019s Collaboration with Smith-Miller and Hawkinson:":
            subsections:
            - "3.2a Overview of Barbara Kruger\u2019s Collaboration"
            - "3.2b Analysis of Barbara Kruger\u2019s Collaboration"
            - "3.2c Impact of Barbara Kruger\u2019s Collaboration"
        - '- Section: 3.3 Case study: Exploring the work of Silvia Kolbowski and her collaborations:':
            subsections:
            - 3.3a Overview of Silvia Kolbowski's Work
            - 3.3b Analysis of Silvia Kolbowski's Collaborations
            - 3.3c Impact of Silvia Kolbowski's Collaborations
        - '- Section: 3.4 Analysis of the impact of artist-architect collaborations on the built environment:':
            subsections:
            - 3.4a Overview of Impact
            - 3.4b Analysis of Impact
            - 3.4c Case Studies of Impact
    - '- Chapter 4: The Big Dig/Central Artery Project:':
        sections:
        - '- Section: 4.1 Introduction to the Big Dig/Central Artery Project and its significance:':
            subsections:
            - 4.1a Overview of the Big Dig/Central Artery Project
            - 4.1b Analysis of the Big Dig/Central Artery Project
            - 4.1c Impact of the Big Dig/Central Artery Project
        - '- Section: 4.2 Examination of the challenges faced during the project and their resolutions:':
            subsections:
            - 4.2a Overview of Challenges
            - 4.2b Analysis of Challenges
            - 4.2c Case Studies of Resolutions
        - '- Section: 4.3 Analysis of the impact of the Big Dig/Central Artery Project on urbanism:':
            subsections:
            - 4.3a Overview of Impact on Urbanism
            - 4.3b Analysis of Impact on Urbanism
            - 4.3c Case Studies of Impact on Urbanism
    - '- Chapter 5: History of the Central Artery:':
        sections:
        - "- Section: 5.1 Presentation by Hubert Murray, Architect/Planner for Boston\u2019s Central Artery Project:":
            subsections:
            - 5.1a Overview of Hubert Murray's Presentation
            - 5.1b Analysis of Hubert Murray's Presentation
            - 5.1c Impact of Hubert Murray's Presentation
        - '- Section: 5.2 Discussion of the historical context and development of the Central Artery:':
            subsections:
            - 5.2a Overview of Historical Context
            - 5.2b Analysis of Historical Context
            - 5.2c Impact of Historical Context
    - '- Chapter 6: Critical Regionalism Revisited:':
        sections:
        - '- Section: 6.1 Field Trip to Yale University to attend lecture by Kenneth Frampton and Arjun Appadurai:':
            subsections:
            - 6.1a Overview of Field Trip
            - 6.1b Analysis of Lectures
            - 6.1c Impact of Field Trip
        - '- Section: 6.2 Analysis and critique of critical regionalism in the context of art, architecture, and urbanism:':
            subsections:
            - 6.2a Overview of Critical Regionalism
            - 6.2b Analysis of Critical Regionalism
            - 6.2c Impact of Critical Regionalism
    - '- Chapter 7: Visiting Artist: Kelly Dobson:':
        sections:
        - '- Section: 7.1 In-depth exploration of the work and contributions of Kelly Dobson:':
            subsections:
            - 7.1a Overview of Kelly Dobson's Work
            - 7.1b Analysis of Kelly Dobson's Work
            - 7.1c Impact of Kelly Dobson's Work
        - '- Section: 7.2 Discussion and analysis of the role of visiting artists in the course:':
            subsections:
            - 7.2a Overview of Role of Visiting Artists
            - 7.2b Analysis of Role of Visiting Artists
            - 7.2c Impact of Role of Visiting Artists
    - "- Chapter 8: Students\u2019 Proposals for Big Dig Interventions:":
        sections:
        - "- Section: 8.1 Pin-up of Students\u2019 Proposals for interventions in the Big Dig/Central Artery Project:":
            subsections:
            - 8.1a Overview of Student Proposals
            - 8.1b Analysis of Student Proposals
            - 8.1c Impact of Student Proposals
        - '- Section: 8.2 Analysis and critique of student proposals by instructors and visiting critics:':
            subsections:
            - 8.2a Overview of Critiques
            - 8.2b Analysis of Critiques
            - 8.2c Impact of Critiques
    - '- Chapter 9: Planned Cities and Public Art/Architecture:':
        sections:
        - '- Section: 9.1 Introduction to Brasilia and its significance as a planned city:':
            subsections:
            - 9.1a Overview of Brasilia
            - 9.1b Analysis of Brasilia
            - 9.1c Impact of Brasilia
        - '- Section: 9.2 Discussion of other planned cities and their deployments of Public Art and Architecture:':
            subsections:
            - 9.2a Overview of Other Planned Cities
            - 9.2b Analysis of Other Planned Cities
            - 9.2c Impact of Other Planned Cities
        - '- Section: 9.3 Analysis of the relationship between planned cities and public art/architecture:':
            subsections:
            - 9.3a Overview of Relationship
            - 9.3b Analysis of Relationship
            - 9.3c Case Studies of Relationship
    - '- Chapter 10: Field Trip to Brasilia:':
        sections:
        - '- Section: 10.1 Visit to Brasilia to experience its architecture and public art:':
            subsections:
            - 10.1a Overview of Visit
            - 10.1b Analysis of Visit
            - 10.1c Impact of Visit
        - '- Section: 10.2 Reflection and analysis of the impact of Brasilia on urbanism and the built environment:':
            subsections:
            - 10.2a Overview of Reflection
            - 10.2b Analysis of Reflection
            - 10.2c Impact of Reflection
    - '- Chapter 11: Discussion of Brasilia Trip:':
        sections:
        - '- Section: 11.1 Presentation of photographs and film footage from the trip to Brasilia:':
            subsections:
            - 11.1a Overview of Presentation
            - 11.1b Analysis of Presentation
            - 11.1c Impact of Presentation
        - '- Section: 11.2 Analysis and reflection on the experience and lessons learned during the trip:':
            subsections:
            - 11.2a Overview of Analysis and Reflection
            - 11.2b Analysis of Lessons Learned
            - 11.2c Impact of Lessons Learned
    - '- Chapter 12: Films:':
        sections:
        - '- Section: 12.1 Analysis and interpretation of Chris Marker''s Sans Soleil:':
            subsections:
            - 12.1a Overview of Sans Soleil
            - 12.1b Analysis of Sans Soleil
            - 12.1c Impact of Sans Soleil
        - '- Section: 12.2 Analysis and interpretation of Berlin Babylon directed by Hubertus Siegert:':
            subsections:
            - 12.2a Overview of Berlin Babylon
            - 12.2b Analysis of Berlin Babylon
            - 12.2c Impact of Berlin Babylon
    - "- Chapter 13: Final Critique of Students\u2019 Projects:":
        sections:
        - '- Section: 13.1 Critique session with Visiting Critics Wendy Jacob, Hubert Murray, and Laurie Palmer:':
            subsections:
            - 13.1a Overview of Critique Session
            - 13.1b Analysis of Critique Session
            - 13.1c Impact of Critique Session
        - '- Section: 13.2 Analysis and feedback on students'' final projects by instructors and visiting critics:':
            subsections:
            - 13.2a Overview of Feedback
            - 13.2b Analysis of Feedback
            - 13.2c Impact of Feedback
    - '- Chapter 14: Student Projects:':
        sections:
        - '- Section: 14.1 In-depth exploration and analysis of interventions proposed by students for the Rose Kennedy Greenway:':
            subsections:
            - 14.1a Overview of Student Proposals
            - 14.1b Analysis of Student Proposals
            - 14.1c Impact of Student Proposals
        - '- Section: 14.2 Reflection on the process and outcomes of student projects:':
            subsections:
            - 14.2a Overview of Reflection
            - 14.2b Analysis of Reflection
            - 14.2c Impact of Reflection
    - '- Chapter 15: The Role of Public Art in Urban Planning:':
        sections:
        - '- Section: 15.1 Understanding the Importance of Public Art in Urban Planning:':
            subsections:
            - 15.1a Overview of Public Art in Urban Planning
            - 15.1b Analysis of Public Art in Urban Planning
            - 15.1c Impact of Public Art in Urban Planning
        - '- Section: 15.2 Case Studies of Public Art in Urban Planning:':
            subsections:
            - 15.2a Overview of Case Studies
            - 15.2b Analysis of Case Studies
            - 15.2c Impact of Case Studies
    - '- Chapter 16: The Role of Architecture in Urban Planning:':
        sections:
        - '- Section: 16.1 Understanding the Importance of Architecture in Urban Planning:':
            subsections:
            - 16.1a Overview of Architecture in Urban Planning
            - 16.1b Analysis of Architecture in Urban Planning
            - 16.1c Impact of Architecture in Urban Planning
        - '- Section: 16.2 Case Studies of Architecture in Urban Planning:':
            subsections:
            - 16.2a Overview of Case Studies
            - 16.2b Analysis of Case Studies
            - 16.2c Impact of Case Studies
    - '- Chapter 17: The Role of Urbanism in Urban Planning:':
        sections:
        - '- Section: 17.1 Understanding the Importance of Urbanism in Urban Planning:':
            subsections:
            - 17.1a Overview of Urbanism in Urban Planning
            - 17.1b Analysis of Urbanism in Urban Planning
            - 17.1c Impact of Urbanism in Urban Planning
        - '- Section: 17.2 Case Studies of Urbanism in Urban Planning:':
            subsections:
            - 17.2a Overview of Case Studies
            - 17.2b Analysis of Case Studies
            - 17.2c Impact of Case Studies
    - '- Chapter 18: The Intersection of Art, Architecture, and Urbanism:':
        sections:
        - '- Section: 18.1 Understanding the Intersection of Art, Architecture, and Urbanism:':
            subsections:
            - 18.1a Overview of the Intersection
            - 18.1b Analysis of the Intersection
            - 18.1c Impact of the Intersection
        - '- Section: 18.2 Case Studies of the Intersection of Art, Architecture, and Urbanism:':
            subsections:
            - 18.2a Overview of Case Studies
            - 18.2b Analysis of Case Studies
            - 18.2c Impact of Case Studies
    - '- Chapter 19: The Future of Art, Architecture, and Urbanism:':
        sections:
        - '- Section: 19.1 Predictions for the Future of Art, Architecture, and Urbanism:':
            subsections:
            - 19.1a Overview of Predictions
            - 19.1b Analysis of Predictions
            - 19.1c Impact of Predictions
        - '- Section: 19.2 Case Studies of Future Predictions for Art, Architecture, and Urbanism:':
            subsections:
            - 19.2a Overview of Case Studies
            - 19.2b Analysis of Case Studies
            - 19.2c Impact of Case Studies
    - '- Chapter 20: Conclusion:':
        sections:
        - '- Section: 20.1 Reflection on the Course:':
            subsections:
            - 20.1a Overview of Reflection
            - 20.1b Analysis of Reflection
            - 20.1c Impact of Reflection
        - '- Section: 20.2 Final Thoughts on Art, Architecture, and Urbanism:':
            subsections:
            - 20.2a Overview of Final Thoughts
            - 20.2b Analysis of Final Thoughts
            - 20.2c Impact of Final Thoughts
