textbook:
  'Introduction to Sculpture: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: Introduction:':
        sections:
        - '- Section: 1.1 Course Number:':
            subsections:
            - 1.1a Course Code
            - 1.1b Course Registration
            - 1.1c Course Prerequisites
        - '- Section: 1.2 Course Name:':
            subsections:
            - 1.2a Course Title
            - 1.2b Course Description
            - 1.2c Course Objectives
        - '- Section: 1.3 Resource Level:':
            subsections:
            - 1.3a Resource Availability
            - 1.3b Resource Requirements
            - 1.3c Resource Management
    - '- Chapter 2: Readings:':
        sections:
        - '- Section: 2.1 Page: readings:':
            subsections:
            - 2.1a Reading Assignments
            - 2.1b Reading Schedule
            - 2.1c Reading Materials
        - '- Section: 2.2 Text:':
            subsections:
            - 2.2a Textbook Information
            - 2.2b Textbook Chapters
            - 2.2c Textbook Supplements
        - '- Section: 2.3 Information:':
            subsections:
            - 2.3a Overview of Sculpture Materials
            - 2.3b Sculpture Techniques
            - 2.3c Sculpture History
    - '- Chapter 3: Lecture Notes:':
        sections:
        - '- Section: 3.1 Page: lecture-notes:':
            subsections:
            - 3.1a Lecture Schedule
            - 3.1b Lecture Topics
            - 3.1c Lecture Supplements
        - '- Section: 3.2 Text:':
            subsections:
            - 3.2a Lecture Text
            - 3.2b Lecture Summaries
            - 3.2c Lecture References
        - '- Section: 3.3 Information:':
            subsections:
            - 3.3a Introduction to Sculpture History
            - 3.3b Basic Principles of Sculpture Design
            - 3.3c Sculpture Styles and Movements
    - '- Chapter 4: Recitations:':
        sections:
        - '- Section: 4.1 Page: recitations:':
            subsections:
            - 4.1a Recitation Schedule
            - 4.1b Recitation Topics
            - 4.1c Recitation Materials
        - '- Section: 4.2 Text:':
            subsections:
            - 4.2a Recitation Text
            - 4.2b Recitation Summaries
            - 4.2c Recitation References
        - '- Section: 4.3 Information:':
            subsections:
            - 4.3a Sculpture Safety Guidelines
            - 4.3b Tools and Equipment for Sculpting
            - 4.3c Sculpture Studio Etiquette
    - '- Chapter 5: Assignments:':
        sections:
        - '- Section: 5.1 Page: assignments:':
            subsections:
            - 5.1a Assignment Schedule
            - 5.1b Assignment Topics
            - 5.1c Assignment Materials
        - '- Section: 5.2 Text:':
            subsections:
            - 5.2a Assignment Text
            - 5.2b Assignment Summaries
            - 5.2c Assignment References
        - '- Section: 5.3 Information:':
            subsections:
            - 5.3a Sculpting with Clay
            - 5.3b Carving Techniques
            - 5.3c Sculpture Presentation and Display
    - '- Chapter 6: Exams:':
        sections:
        - '- Section: 6.1 Page: exams:':
            subsections:
            - 6.1a Exam Schedule
            - 6.1b Exam Topics
            - 6.1c Exam Materials
        - '- Section: 6.2 Text:':
            subsections:
            - 6.2a Exam Text
            - 6.2b Exam Summaries
            - 6.2c Exam References
        - '- Section: 6.3 Information:':
            subsections:
            - 6.3a Sculpture Analysis
            - 6.3b Sculpture Critique and Evaluation
            - 6.3c Sculpture Appreciation
    - '- Chapter 7: Syllabus:':
        sections:
        - '- Section: 7.1 Page: syllabus:':
            subsections:
            - 7.1a Syllabus Overview
            - 7.1b Syllabus Details
            - 7.1c Syllabus Updates
    - '- Chapter 8: Calendar:':
        sections:
        - '- Section: 8.1 Page: calendar:':
            subsections:
            - 8.1a Academic Calendar
            - 8.1b Important Dates and Deadlines
            - 8.1c Class Schedule and Topics
    - '- Chapter 9: Projects:':
        sections:
        - '- Section: 9.1 Page: projects:':
            subsections:
            - 9.1a Project Schedule
            - 9.1b Project Topics
            - 9.1c Project Materials
        - '- Section: 9.2 Text:':
            subsections:
            - 9.2a Project Text
            - 9.2b Project Summaries
            - 9.2c Project References
        - '- Section: 9.3 Information:':
            subsections:
            - 9.3a Sculpture Installation
            - 9.3b Sculpture in Public Spaces
            - 9.3c Sculpture Exhibition and Critique
    - '- Chapter 10: Sculpture Materials:':
        sections:
        - '- Section: 10.1 Clay:':
            subsections:
            - 10.1a Types of Clay
            - 10.1b Working with Clay
            - 10.1c Clay Sculpture Techniques
        - '- Section: 10.2 Stone:':
            subsections:
            - 10.2a Types of Stone
            - 10.2b Working with Stone
            - 10.2c Stone Carving Techniques
        - '- Section: 10.3 Metal:':
            subsections:
            - 10.3a Types of Metal
            - 10.3b Working with Metal
            - 10.3c Metal Sculpture Techniques
    - '- Chapter 11: Sculpture Techniques:':
        sections:
        - '- Section: 11.1 Carving:':
            subsections:
            - 11.1a Introduction to Carving
            - 11.1b Carving Tools and Techniques
            - 11.1c Carving Safety
        - '- Section: 11.2 Modeling:':
            subsections:
            - 11.2a Introduction to Modeling
            - 11.2b Modeling Tools and Techniques
            - 11.2c Modeling Safety
        - '- Section: 11.3 Casting:':
            subsections:
            - 11.3a Introduction to Casting
            - 11.3b Casting Tools and Techniques
            - 11.3c Casting Safety
    - '- Chapter 12: Sculpture History:':
        sections:
        - '- Section: 12.1 Ancient Sculpture:':
            subsections:
            - 12.1a Egyptian Sculpture
            - 12.1b Greek Sculpture
            - 12.1c Roman Sculpture
        - '- Section: 12.2 Medieval Sculpture:':
            subsections:
            - 12.2a Gothic Sculpture
            - 12.2b Romanesque Sculpture
            - 12.2c Byzantine Sculpture
        - '- Section: 12.3 Modern Sculpture:':
            subsections:
            - 12.3a Abstract Sculpture
            - 12.3b Minimalist Sculpture
            - 12.3c Conceptual Sculpture
    - '- Chapter 13: Sculpture Design Principles:':
        sections:
        - '- Section: 13.1 Balance:':
            subsections:
            - 13.1a Symmetrical Balance
            - 13.1b Asymmetrical Balance
            - 13.1c Radial Balance
        - '- Section: 13.2 Proportion:':
            subsections:
            - 13.2a Human Proportions
            - 13.2b Animal Proportions
            - 13.2c Abstract Proportions
        - '- Section: 13.3 Unity:':
            subsections:
            - 13.3a Unity through Color
            - 13.3b Unity through Shape
            - 13.3c Unity through Texture
    - '- Chapter 14: Sculpture Safety:':
        sections:
        - '- Section: 14.1 Studio Safety:':
            subsections:
            - 14.1a Safety Equipment
            - 14.1b Safety Procedures
            - 14.1c Emergency Procedures
        - '- Section: 14.2 Tool Safety:':
            subsections:
            - 14.2a Hand Tool Safety
            - 14.2b Power Tool Safety
            - 14.2c Cleaning and Maintenance
        - '- Section: 14.3 Material Safety:':
            subsections:
            - 14.3a Hazardous Materials
            - 14.3b Safe Handling Procedures
            - 14.3c Material Disposal
    - '- Chapter 15: Sculpture Presentation:':
        sections:
        - '- Section: 15.1 Display Techniques:':
            subsections:
            - 15.1a Lighting Techniques
            - 15.1b Display Stands
            - 15.1c Outdoor Displays
        - '- Section: 15.2 Documentation:':
            subsections:
            - 15.2a Photography Techniques
            - 15.2b Writing Artist Statements
            - 15.2c Creating a Portfolio
        - '- Section: 15.3 Critique and Evaluation:':
            subsections:
            - 15.3a Giving Constructive Feedback
            - 15.3b Receiving Critique
            - 15.3c Self-Evaluation Techniques
    - '- Chapter 16: Sculpture in Public Spaces:':
        sections:
        - '- Section: 16.1 Public Art:':
            subsections:
            - 16.1a Public Art Commissions
            - 16.1b Public Art Controversies
            - 16.1c Public Art Conservation
        - '- Section: 16.2 Site-Specific Sculpture:':
            subsections:
            - 16.2a Site Analysis
            - 16.2b Site-Specific Design
            - 16.2c Site Installation
        - '- Section: 16.3 Community Engagement:':
            subsections:
            - 16.3a Community Art Projects
            - 16.3b Collaborative Sculpture
            - 16.3c Public Art Education
    - '- Chapter 17: Sculpture Careers:':
        sections:
        - '- Section: 17.1 Professional Sculptor:':
            subsections:
            - 17.1a Building a Career
            - 17.1b Marketing and Promotion
            - 17.1c Grants and Funding
        - '- Section: 17.2 Art Education:':
            subsections:
            - 17.2a Teaching Sculpture
            - 17.2b Curriculum Development
            - 17.2c Continuing Education
        - '- Section: 17.3 Art Conservation:':
            subsections:
            - 17.3a Sculpture Conservation
            - 17.3b Conservation Ethics
            - 17.3c Conservation Techniques
    - '- Chapter 18: Advanced Sculpture Techniques:':
        sections:
        - '- Section: 18.1 Kinetic Sculpture:':
            subsections:
            - 18.1a Introduction to Kinetic Sculpture
            - 18.1b Kinetic Sculpture Techniques
            - 18.1c Kinetic Sculpture Artists
        - '- Section: 18.2 Digital Sculpture:':
            subsections:
            - 18.2a 3D Modeling
            - 18.2b 3D Printing
            - 18.2c Digital Sculpture Artists
        - '- Section: 18.3 Installation Art:':
            subsections:
            - 18.3a Introduction to Installation Art
            - 18.3b Installation Art Techniques
            - 18.3c Installation Art Artists
    - '- Chapter 19: Sculpture and Society:':
        sections:
        - '- Section: 19.1 Sculpture and Politics:':
            subsections:
            - 19.1a Political Sculpture
            - 19.1b Monuments and Memorials
            - 19.1c Censorship and Controversy
        - '- Section: 19.2 Sculpture and Environment:':
            subsections:
            - 19.2a Land Art
            - 19.2b Environmental Sculpture
            - 19.2c Sustainable Art Practices
        - '- Section: 19.3 Sculpture and Identity:':
            subsections:
            - 19.3a Sculpture and Gender
            - 19.3b Sculpture and Race
            - 19.3c Sculpture and Culture
    - '- Chapter 20: Future of Sculpture:':
        sections:
        - '- Section: 20.1 New Materials:':
            subsections:
            - 20.1a Experimental Materials
            - 20.1b Material Innovations
            - 20.1c Future Material Trends
        - '- Section: 20.2 New Technologies:':
            subsections:
            - 20.2a Digital Fabrication
            - 20.2b Virtual Reality
            - 20.2c Augmented Reality
        - '- Section: 20.3 New Ideas:':
            subsections:
            - 20.3a Conceptual Art
            - 20.3b Interactive Sculpture
            - 20.3c Future Art Movements
