textbook:
  'Revitalizing Urban Main Streets: St. Claude Avenue, New Orleans":':
    chapters:
    - '- Chapter 1: Course Introduction:':
        sections:
        - '- Section: 1.1 Main Street Sites and Issues:':
            subsections:
            - 1.1a Understanding Main Street Sites
            - 1.1b Analyzing Main Street Issues
        - '- Section: 1.2 Urban Neighborhood Decline: Causes, Consequences, Challenges:':
            subsections:
            - 1.2a Causes of Urban Neighborhood Decline
            - 1.2b Consequences of Urban Neighborhood Decline
            - 1.2c Challenges in Urban Neighborhood Revitalization
    - '- Chapter 2: New Orleans Background:':
        sections:
        - '- Section: 2.1 Social, Political and Development History:':
            subsections:
            - 2.1a Social History of New Orleans
            - 2.1b Political History of New Orleans
            - 2.1c Development History of New Orleans
        - "- Section: 2.2 Katrina Impact, Disaster Recovery and New Orleans\u2019 Planning Process:":
            subsections:
            - 2.2a Impact of Hurricane Katrina
            - 2.2b Disaster Recovery Efforts
            - "2.2c New Orleans\u2019 Planning Process"
        - '- Section: 2.3 Urban Design and Development: Ways of Seeing and Listening:':
            subsections:
            - 2.3a Visual Perception in Urban Design
            - 2.3b Listening to Community Voices
    - '- Chapter 3: Project Discussion and Planning:':
        sections:
        - '- Section: 3.1 Expectations, goals, and apprehensions:':
            subsections:
            - 3.1a Setting Expectations
            - 3.1b Defining Goals
            - 3.1c Addressing Apprehensions
        - '- Section: 3.2 First experiences and thoughts:':
            subsections:
            - 3.2a Initial Experiences
            - 3.2b Initial Thoughts
            - 3.2c Reflections on Initial Experiences
        - '- Section: 3.3 Defining shared issues or questions to examine through reflection:':
            subsections:
            - 3.3a Identifying Shared Issues
            - 3.3b Formulating Questions for Reflection
            - 3.3c Process of Reflective Examination
        - '- Section: 3.4 How our personal values shape our work:':
            subsections:
            - 3.4a Understanding Personal Values
            - 3.4b Influence of Personal Values on Work
            - 3.4c Balancing Personal Values and Professional Responsibilities
        - '- Section: 3.5 Looking backward and forward:':
            subsections:
            - 3.5a Reflecting on Past Experiences
            - 3.5b Anticipating Future Challenges
            - 3.5c Preparing for Future Opportunities
        - '- Section: 3.6 Commercial revitalization practice:':
            subsections:
            - 3.6a Principles of Commercial Revitalization
            - 3.6b Best Practices in Commercial Revitalization
            - 3.6c Case Studies in Commercial Revitalization
        - '- Section: 3.7 Critical moments: personal understanding:':
            subsections:
            - 3.7a Identifying Critical Moments
            - 3.7b Reflecting on Personal Understanding
            - 3.7c Learning from Critical Moments
    - '- Chapter 4: Field Trip and Interviews:':
        sections:
        - '- Section: 4.1 Field trip walking tour of St. Claude Avenue commercial corridor:':
            subsections:
            - 4.1a Planning the Field Trip
            - 4.1b Conducting the Walking Tour
            - 4.1c Observations from the Field Trip
        - '- Section: 4.2 Interview transcriptions:':
            subsections:
            - 4.2a Conducting Interviews
            - 4.2b Transcribing Interviews
            - 4.2c Analyzing Interview Transcriptions
    - '- Chapter 5: Analysis and Documentation:':
        sections:
        - '- Section: 5.1 Summary of background reports and key documents:':
            subsections:
            - 5.1a Reviewing Background Reports
            - 5.1b Identifying Key Documents
            - 5.1c Summarizing Key Findings
        - '- Section: 5.2 Draft of phase I existing conditions analysis section of plan:':
            subsections:
            - 5.2a Analyzing Existing Conditions
            - 5.2b Drafting the Analysis Section
            - 5.2c Reviewing and Revising the Draft
    - '- Chapter 6: Final Report:':
        sections:
        - ? '- Section: 6.1 The following is the final report prepared by the students
            in the Spring 2009 Revitalizing Urban Main Streets course. Used with permission.:'
          : subsections:
            - 6.1a Final Report Overview
            - 6.1b Methodology and Findings
            - 6.1c Reflections on the Course
        - '- Section: 6.2 ''St Claude in Common.'':':
            subsections:
            - 6.2a Case Studies in Successful Revitalization
            - 6.2b Implementing 'St Claude in Common'
            - 6.2c Evaluating the Impact of 'St Claude in Common'
