textbook:
  'The Dynamics of Complex Systems: A Practical Guide":':
    chapters:
    - '- Chapter 1: Introduction:':
        sections:
        - '- Section: 1.1 Course overview:':
            subsections:
            - 1.1a Course objectives
            - 1.1b Importance of system dynamics
            - 1.1c Course structure
        - '- Section: 1.2 Objectives:':
            subsections:
            - 1.2a Understanding system dynamics
            - 1.2b Application of system dynamics
            - 1.2c Course expectations
        - '- Section: 1.3 Importance of system dynamics:':
            subsections:
            - 1.3a Role in complex systems
            - 1.3b Real-world applications
            - 1.3c Future of system dynamics
    - '- Chapter 2: Guidelines for Kickoff Meeting:':
        sections:
        - '- Section: 2.1 Preparing for kickoff meeting:':
            subsections:
            - 2.1a Meeting preparation
            - 2.1b Setting agenda
            - 2.1c Understanding client expectations
        - '- Section: 2.2 Meeting agenda:':
            subsections:
            - 2.2a Agenda setting
            - 2.2b Time management
            - 2.2c Meeting follow-up
        - '- Section: 2.3 Client expectations:':
            subsections:
            - 2.3a Understanding client needs
            - 2.3b Managing expectations
            - 2.3c Delivering on promises
    - '- Chapter 3: Definition of Concern and Momentum Policies:':
        sections:
        - '- Section: 3.1 Identifying concerns:':
            subsections:
            - 3.1a Identifying client concerns
            - 3.1b Prioritizing concerns
            - 3.1c Addressing concerns
        - '- Section: 3.2 Developing momentum policies:':
            subsections:
            - 3.2a Understanding momentum policies
            - 3.2b Creating momentum policies
            - 3.2c Implementing momentum policies
        - '- Section: 3.3 Presenting concerns to clients:':
            subsections:
            - 3.3a Effective communication
            - 3.3b Presenting concerns
            - 3.3c Handling client feedback
    - '- Chapter 4: Rough Dynamic Hypotheses:':
        sections:
        - '- Section: 4.1 Formulating hypotheses:':
            subsections:
            - 4.1a Understanding hypotheses
            - 4.1b Creating hypotheses
            - 4.1c Testing hypotheses
        - '- Section: 4.2 Initial model development:':
            subsections:
            - 4.2a Understanding model development
            - 4.2b Creating initial models
            - 4.2c Refining models
        - '- Section: 4.3 Hypothesis presentation:':
            subsections:
            - 4.3a Preparing for presentation
            - 4.3b Delivering presentation
            - 4.3c Handling feedback
    - '- Chapter 5: Dynamic Hypotheses:':
        sections:
        - '- Section: 5.1 Refining hypotheses:':
            subsections:
            - 5.1a Reviewing initial hypotheses
            - 5.1b Refining hypotheses
            - 5.1c Finalizing hypotheses
        - '- Section: 5.2 Data collection:':
            subsections:
            - 5.2a Understanding data collection
            - 5.2b Collecting data
            - 5.2c Analyzing data
        - '- Section: 5.3 Model validation:':
            subsections:
            - 5.3a Understanding model validation
            - 5.3b Validating models
            - 5.3c Refining models
    - '- Chapter 6: Mini-presentations:':
        sections:
        - '- Section: 6.1 Presentation structure:':
            subsections:
            - 6.1a Understanding presentation structure
            - 6.1b Creating presentation structure
            - 6.1c Refining presentation structure
        - '- Section: 6.2 Delivering effective presentations:':
            subsections:
            - 6.2a Understanding effective presentations
            - 6.2b Delivering presentations
            - 6.2c Handling feedback
        - '- Section: 6.3 Feedback and revisions:':
            subsections:
            - 6.3a Understanding feedback
            - 6.3b Handling feedback
            - 6.3c Making revisions
    - '- Chapter 7: Partial Model of First Hypothesis:':
        sections:
        - '- Section: 7.1 Developing partial models:':
            subsections:
            - 7.1a Understanding partial models
            - 7.1b Creating partial models
            - 7.1c Refining partial models
        - '- Section: 7.2 Model integration:':
            subsections:
            - 7.2a Understanding model integration
            - 7.2b Integrating models
            - 7.2c Refining integrated models
        - '- Section: 7.3 Presentation to clients:':
            subsections:
            - 7.3a Preparing for client presentation
            - 7.3b Delivering client presentation
            - 7.3c Handling client feedback
    - '- Chapter 8: Model and Analysis of First Hypothesis:':
        sections:
        - '- Section: 8.1 Model refinement:':
            subsections:
            - 8.1a Understanding model refinement
            - 8.1b Refining models
            - 8.1c Finalizing models
        - '- Section: 8.2 Data analysis:':
            subsections:
            - 8.2a Understanding data analysis
            - 8.2b Analyzing data
            - 8.2c Interpreting data
        - '- Section: 8.3 Presentation of results:':
            subsections:
            - 8.3a Preparing results presentation
            - 8.3b Delivering results presentation
            - 8.3c Handling feedback
    - '- Chapter 9: Insights Presentation:':
        sections:
        - '- Section: 9.1 Analyzing insights:':
            subsections:
            - 9.1a Understanding insights
            - 9.1b Analyzing insights
            - 9.1c Interpreting insights
        - '- Section: 9.2 Communicating findings:':
            subsections:
            - 9.2a Understanding communication
            - 9.2b Communicating findings
            - 9.2c Handling feedback
        - '- Section: 9.3 Finalizing recommendations:':
            subsections:
            - 9.3a Understanding recommendations
            - 9.3b Finalizing recommendations
            - 9.3c Presenting recommendations
    - '- Chapter 10: Final Presentations and Models:':
        sections:
        - '- Section: 10.1 Finalizing models:':
            subsections:
            - 10.1a Reviewing models
            - 10.1b Finalizing models
            - 10.1c Presenting models
        - '- Section: 10.2 Preparing presentations:':
            subsections:
            - 10.2a Understanding presentation preparation
            - 10.2b Preparing presentations
            - 10.2c Delivering presentations
        - '- Section: 10.3 Project evaluation:':
            subsections:
            - 10.3a Understanding project evaluation
            - 10.3b Evaluating project
            - 10.3c Presenting evaluation
    - '- Chapter 11: System Dynamics in Practice:':
        sections:
        - '- Section: 11.1 Real-world case studies:':
            subsections:
            - 11.1a Understanding case studies
            - 11.1b Analyzing case studies
            - 11.1c Interpreting case studies
        - '- Section: 11.2 Ethical considerations in system dynamics:':
            subsections:
            - 11.2a Understanding ethics
            - 11.2b Ethical considerations
            - 11.2c Handling ethical dilemmas
        - '- Section: 11.3 Challenges and future directions:':
            subsections:
            - 11.3a Understanding challenges
            - 11.3b Overcoming challenges
            - 11.3c Future directions
    - '- Chapter 12: Advanced System Dynamics:':
        sections:
        - '- Section: 12.1 Advanced modeling techniques:':
            subsections:
            - 12.1a Understanding advanced techniques
            - 12.1b Applying advanced techniques
            - 12.1c Refining advanced techniques
        - '- Section: 12.2 Advanced data analysis:':
            subsections:
            - 12.2a Understanding advanced data analysis
            - 12.2b Applying advanced data analysis
            - 12.2c Interpreting advanced data analysis
        - '- Section: 12.3 Advanced presentation techniques:':
            subsections:
            - 12.3a Understanding advanced presentation techniques
            - 12.3b Applying advanced presentation techniques
            - 12.3c Refining advanced presentation techniques
    - '- Chapter 13: System Dynamics and Decision Making:':
        sections:
        - '- Section: 13.1 Understanding decision making:':
            subsections:
            - 13.1a Role of system dynamics in decision making
            - 13.1b Decision making models
            - 13.1c Decision making case studies
        - '- Section: 13.2 Decision making techniques:':
            subsections:
            - 13.2a Understanding decision making techniques
            - 13.2b Applying decision making techniques
            - 13.2c Refining decision making techniques
        - '- Section: 13.3 Decision making and system dynamics:':
            subsections:
            - 13.3a Role of system dynamics in decision making
            - 13.3b System dynamics decision making models
            - 13.3c System dynamics decision making case studies
    - '- Chapter 14: System Dynamics and Policy Making:':
        sections:
        - '- Section: 14.1 Understanding policy making:':
            subsections:
            - 14.1a Role of system dynamics in policy making
            - 14.1b Policy making models
            - 14.1c Policy making case studies
        - '- Section: 14.2 Policy making techniques:':
            subsections:
            - 14.2a Understanding policy making techniques
            - 14.2b Applying policy making techniques
            - 14.2c Refining policy making techniques
        - '- Section: 14.3 Policy making and system dynamics:':
            subsections:
            - 14.3a Role of system dynamics in policy making
            - 14.3b System dynamics policy making models
            - 14.3c System dynamics policy making case studies
    - '- Chapter 15: System Dynamics and Organizational Change:':
        sections:
        - '- Section: 15.1 Understanding organizational change:':
            subsections:
            - 15.1a Role of system dynamics in organizational change
            - 15.1b Organizational change models
            - 15.1c Organizational change case studies
        - '- Section: 15.2 Organizational change techniques:':
            subsections:
            - 15.2a Understanding organizational change techniques
            - 15.2b Applying organizational change techniques
            - 15.2c Refining organizational change techniques
        - '- Section: 15.3 Organizational change and system dynamics:':
            subsections:
            - 15.3a Role of system dynamics in organizational change
            - 15.3b System dynamics organizational change models
            - 15.3c System dynamics organizational change case studies
    - '- Chapter 16: System Dynamics and Strategic Planning:':
        sections:
        - '- Section: 16.1 Understanding strategic planning:':
            subsections:
            - 16.1a Role of system dynamics in strategic planning
            - 16.1b Strategic planning models
            - 16.1c Strategic planning case studies
        - '- Section: 16.2 Strategic planning techniques:':
            subsections:
            - 16.2a Understanding strategic planning techniques
            - 16.2b Applying strategic planning techniques
            - 16.2c Refining strategic planning techniques
        - '- Section: 16.3 Strategic planning and system dynamics:':
            subsections:
            - 16.3a Role of system dynamics in strategic planning
            - 16.3b System dynamics strategic planning models
            - 16.3c System dynamics strategic planning case studies
    - '- Chapter 17: System Dynamics and Innovation:':
        sections:
        - '- Section: 17.1 Understanding innovation:':
            subsections:
            - 17.1a Role of system dynamics in innovation
            - 17.1b Innovation models
            - 17.1c Innovation case studies
        - '- Section: 17.2 Innovation techniques:':
            subsections:
            - 17.2a Understanding innovation techniques
            - 17.2b Applying innovation techniques
            - 17.2c Refining innovation techniques
        - '- Section: 17.3 Innovation and system dynamics:':
            subsections:
            - 17.3a Role of system dynamics in innovation
            - 17.3b System dynamics innovation models
            - 17.3c System dynamics innovation case studies
    - '- Chapter 18: System Dynamics and Sustainability:':
        sections:
        - '- Section: 18.1 Understanding sustainability:':
            subsections:
            - 18.1a Role of system dynamics in sustainability
            - 18.1b Sustainability models
            - 18.1c Sustainability case studies
        - '- Section: 18.2 Sustainability techniques:':
            subsections:
            - 18.2a Understanding sustainability techniques
            - 18.2b Applying sustainability techniques
            - 18.2c Refining sustainability techniques
        - '- Section: 18.3 Sustainability and system dynamics:':
            subsections:
            - 18.3a Role of system dynamics in sustainability
            - 18.3b System dynamics sustainability models
            - 18.3c System dynamics sustainability case studies
    - '- Chapter 19: System Dynamics and Leadership:':
        sections:
        - '- Section: 19.1 Understanding leadership:':
            subsections:
            - 19.1a Role of system dynamics in leadership
            - 19.1b Leadership models
            - 19.1c Leadership case studies
        - '- Section: 19.2 Leadership techniques:':
            subsections:
            - 19.2a Understanding leadership techniques
            - 19.2b Applying leadership techniques
            - 19.2c Refining leadership techniques
        - '- Section: 19.3 Leadership and system dynamics:':
            subsections:
            - 19.3a Role of system dynamics in leadership
            - 19.3b System dynamics leadership models
            - 19.3c System dynamics leadership case studies
    - '- Chapter 20: System Dynamics and Future Trends:':
        sections:
        - '- Section: 20.1 Understanding future trends:':
            subsections:
            - 20.1a Role of system dynamics in future trends
            - 20.1b Future trends models
            - 20.1c Future trends case studies
        - '- Section: 20.2 Future trends techniques:':
            subsections:
            - 20.2a Understanding future trends techniques
            - 20.2b Applying future trends techniques
            - 20.2c Refining future trends techniques
        - '- Section: 20.3 Future trends and system dynamics:':
            subsections:
            - 20.3a Role of system dynamics in future trends
            - 20.3b System dynamics future trends models
            - 20.3c System dynamics future trends case studies
