textbook:
  'Chemical Investigations of Boston Harbor: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: Physical Oceanography:':
        sections:
        - '- Section: 1.1 The Oceans in Motion:':
            subsections:
            - 1.1a Ocean Currents
            - 1.1b Tides and Waves
            - 1.1c Ocean Temperature and Salinity
        - '- Section: 1.2 Historical Perspective on Sampling Equipment for Oceanic Research:':
            subsections:
            - 1.2a Evolution of Sampling Equipment
            - 1.2b Modern Sampling Techniques
            - 1.2c Challenges in Oceanic Sampling
    - '- Chapter 2: Nutrient Cycles:':
        sections:
        - '- Section: 2.1 Nutrient Cycles and Ecosystem Stoichiometry:':
            subsections:
            - 2.1a Nitrogen Cycle
            - 2.1b Phosphorus Cycle
            - 2.1c Carbon Cycle
    - '- Chapter 3: Carbon Cycle:':
        sections:
        - '- Section: 3.1 The Carbon Cycle: Production and Transformations of Organic Matter:':
            subsections:
            - 3.1a Photosynthesis and Respiration
            - 3.1b Carbon Sequestration
            - 3.1c Impact of Climate Change on Carbon Cycle
    - '- Chapter 4: Marine Bioinorganic Chemistry:':
        sections:
        - '- Section: 4.1 The Role of Trace Metals in the Oceanic Cycles of Major Nutrients:':
            subsections:
            - 4.1a Iron in the Ocean
            - 4.1b Copper and Zinc in the Ocean
            - 4.1c Impact of Trace Metals on Marine Life
    - '- Chapter 5: Chemical Sensors in Marine Science:':
        sections:
        - '- Section: 5.1 Chemical Sensors in Marine Science:':
            subsections:
            - 5.1a pH Sensors
            - 5.1b Conductivity Sensors
            - 5.1c Oxygen Sensors
    - '- Chapter 6: Field Trip to Boston Harbor/ Buzzards Bay:':
        sections:
        - '- Section: 6.1 Field Trip to Boston Harbor/ Buzzards Bay:':
            subsections:
            - 6.1a Overview of Boston Harbor
            - 6.1b Overview of Buzzards Bay
            - 6.1c Comparative Analysis of Boston Harbor and Buzzards Bay
    - '- Chapter 7: Physical Parameters of The Coastal Ocean:':
        sections:
        - '- Section: 7.1 Physical Parameters of The Coastal Ocean:':
            subsections:
            - 7.1a Coastal Ocean Temperature
            - 7.1b Coastal Ocean Salinity
            - 7.1c Coastal Ocean Currents
    - '- Chapter 8: Biological Productivity:':
        sections:
        - '- Section: 8.1 Biological Productivity:':
            subsections:
            - 8.1a Primary Productivity
            - 8.1b Secondary Productivity
            - 8.1c Factors Affecting Productivity
    - '- Chapter 9: Electronic Components and Power Sources for Oceanographic Systems:':
        sections:
        - '- Section: 9.1 Electronic Components and Power Sources for Oceanographic Systems:':
            subsections:
            - 9.1a Power Sources for Oceanographic Systems
            - 9.1b Electronic Components for Data Collection
            - 9.1c Maintenance and Troubleshooting of Electronic Components
    - "- Chapter 10: 'WHOI Tour 1: WHOI\u2019s Chemical Instrumentation Facilities':":
        sections:
        - "- Section: 10.1 'WHOI Tour 1: WHOI\u2019s Chemical Instrumentation Facilities':":
            subsections:
            - 10.1a Overview of WHOI's Facilities
            - 10.1b Chemical Instrumentation at WHOI
            - 10.1c Role of WHOI in Marine Science Research
    - '- Chapter 11: Marine Pollution:':
        sections:
        - '- Section: 11.1 Sources of Marine Pollution:':
            subsections:
            - 11.1a Land-based Sources
            - 11.1b Sea-based Sources
            - 11.1c Atmospheric Sources
        - '- Section: 11.2 Impact of Marine Pollution:':
            subsections:
            - 11.2a Impact on Marine Life
            - 11.2b Impact on Human Health
            - 11.2c Impact on Marine Ecosystems
        - '- Section: 11.3 Mitigation and Control of Marine Pollution:':
            subsections:
            - 11.3a Pollution Control Measures
            - 11.3b Role of International Agreements
            - 11.3c Future Challenges
    - '- Chapter 12: Ocean Acidification:':
        sections:
        - '- Section: 12.1 Causes of Ocean Acidification:':
            subsections:
            - 12.1a Carbon Dioxide Emissions
            - 12.1b Changes in Ocean Chemistry
            - 12.1c Role of Climate Change
        - '- Section: 12.2 Impact of Ocean Acidification:':
            subsections:
            - 12.2a Impact on Coral Reefs
            - 12.2b Impact on Shell-forming Organisms
            - 12.2c Impact on Marine Ecosystems
        - '- Section: 12.3 Mitigation and Adaptation Strategies:':
            subsections:
            - 12.3a Reducing CO2 Emissions
            - 12.3b Enhancing Ocean Resilience
            - 12.3c Role of Policy and Legislation
    - '- Chapter 13: Marine Biodiversity:':
        sections:
        - '- Section: 13.1 Importance of Marine Biodiversity:':
            subsections:
            - 13.1a Ecosystem Services
            - 13.1b Genetic Resources
            - 13.1c Cultural and Recreational Values
        - '- Section: 13.2 Threats to Marine Biodiversity:':
            subsections:
            - 13.2a Overfishing
            - 13.2b Habitat Destruction
            - 13.2c Climate Change
        - '- Section: 13.3 Conservation of Marine Biodiversity:':
            subsections:
            - 13.3a Marine Protected Areas
            - 13.3b Sustainable Fisheries Management
            - 13.3c Species Recovery Plans
    - '- Chapter 14: Marine Biogeochemical Cycles:':
        sections:
        - '- Section: 14.1 Nitrogen Cycle in the Ocean:':
            subsections:
            - 14.1a Nitrogen Fixation
            - 14.1b Nitrification and Denitrification
            - 14.1c Human Impact on the Nitrogen Cycle
        - '- Section: 14.2 Phosphorus Cycle in the Ocean:':
            subsections:
            - 14.2a Phosphorus in Marine Sediments
            - 14.2b Role of Phosphorus in Primary Productivity
            - 14.2c Human Impact on the Phosphorus Cycle
        - '- Section: 14.3 Sulfur Cycle in the Ocean:':
            subsections:
            - 14.3a Sulfate Reduction
            - 14.3b Sulfur Oxidation
            - 14.3c Role of Sulfur in the Marine Ecosystem
    - '- Chapter 15: Marine Microbiology:':
        sections:
        - '- Section: 15.1 Role of Microorganisms in the Ocean:':
            subsections:
            - 15.1a Primary Producers
            - 15.1b Decomposers
            - 15.1c Role in Biogeochemical Cycles
        - '- Section: 15.2 Marine Viruses:':
            subsections:
            - 15.2a Viral Infections in Marine Organisms
            - 15.2b Role of Viruses in Marine Ecosystems
            - 15.2c Viral Shunt
        - '- Section: 15.3 Marine Fungi:':
            subsections:
            - 15.3a Diversity of Marine Fungi
            - 15.3b Role of Fungi in Marine Ecosystems
            - 15.3c Fungi and Marine Diseases
    - '- Chapter 16: Marine Ecology:':
        sections:
        - '- Section: 16.1 Marine Food Webs:':
            subsections:
            - 16.1a Trophic Levels
            - 16.1b Energy Flow in Marine Ecosystems
            - 16.1c Role of Detritus
        - '- Section: 16.2 Marine Ecosystems:':
            subsections:
            - 16.2a Coral Reefs
            - 16.2b Mangroves
            - 16.2c Deep Sea Ecosystems
        - '- Section: 16.3 Human Impact on Marine Ecosystems:':
            subsections:
            - 16.3a Overfishing
            - 16.3b Pollution
            - 16.3c Climate Change
    - '- Chapter 17: Marine Geology:':
        sections:
        - '- Section: 17.1 Ocean Floor Topography:':
            subsections:
            - 17.1a Continental Shelf and Slope
            - 17.1b Mid-Ocean Ridges
            - 17.1c Ocean Trenches
        - '- Section: 17.2 Plate Tectonics and the Ocean:':
            subsections:
            - 17.2a Sea Floor Spreading
            - 17.2b Subduction Zones
            - 17.2c Earthquakes and Tsunamis
        - '- Section: 17.3 Marine Sediments:':
            subsections:
            - 17.3a Types of Marine Sediments
            - 17.3b Sediment Distribution
            - 17.3c Paleoclimatology and Marine Sediments
    - '- Chapter 18: Marine Chemistry:':
        sections:
        - '- Section: 18.1 Seawater Chemistry:':
            subsections:
            - 18.1a Major Ions in Seawater
            - 18.1b Trace Elements in Seawater
            - 18.1c Dissolved Gases in Seawater
        - '- Section: 18.2 Chemical Equilibrium in the Ocean:':
            subsections:
            - 18.2a pH and Carbonate Equilibrium
            - 18.2b Nutrient Cycling
            - 18.2c Redox Reactions in the Ocean
        - '- Section: 18.3 Marine Pollution:':
            subsections:
            - 18.3a Types of Marine Pollution
            - 18.3b Impact of Pollution on Marine Life
            - 18.3c Monitoring and Mitigation of Marine Pollution
    - '- Chapter 19: Marine Technology:':
        sections:
        - '- Section: 19.1 Oceanographic Instruments:':
            subsections:
            - 19.1a CTD Sensors
            - 19.1b Acoustic Doppler Current Profilers
            - 19.1c Remote Sensing
        - '- Section: 19.2 Underwater Vehicles:':
            subsections:
            - 19.2a Remotely Operated Vehicles
            - 19.2b Autonomous Underwater Vehicles
            - 19.2c Human-Occupied Vehicles
        - '- Section: 19.3 Ocean Observatories:':
            subsections:
            - 19.3a Fixed Observatories
            - 19.3b Mobile Observatories
            - 19.3c Satellite Observations
    - '- Chapter 20: Marine Policy and Management:':
        sections:
        - '- Section: 20.1 Marine Protected Areas:':
            subsections:
            - 20.1a Types of Marine Protected Areas
            - 20.1b Effectiveness of Marine Protected Areas
            - 20.1c Challenges in Marine Conservation
        - '- Section: 20.2 Fisheries Management:':
            subsections:
            - 20.2a Overfishing and Bycatch
            - 20.2b Sustainable Fisheries
            - 20.2c Aquaculture
        - '- Section: 20.3 Climate Change and the Ocean:':
            subsections:
            - 20.3a Sea Level Rise
            - 20.3b Ocean Acidification
            - 20.3c Marine Heatwaves
