textbook:
  'Environmental Engineering Masters of Engineering Project":':
    chapters:
    - '- Chapter 1: Course Number:':
        sections:
        - '- Section: 1.1 ''1.782'':':
            subsections:
            - 1.1a Introduction to Course Number
            - 1.1b Importance of Course Number
            - 1.1c Application of Course Number
    - '- Chapter 2: Course Name:':
        sections:
        - '- Section: 2.1 Environmental Engineering Masters of Engineering Project:':
            subsections:
            - 2.1a Introduction to Course Name
            - 2.1b Importance of Course Name
            - 2.1c Application of Course Name
    - '- Chapter 3: Resource Level:':
        sections:
        - '- Section: 3.1 Graduate:':
            subsections:
            - 3.1a Introduction to Resource Level
            - 3.1b Importance of Resource Level
            - 3.1c Application of Resource Level
    - '- Chapter 4: Page: readings:':
        sections:
        - '- Section: 4.1 Text:':
            subsections:
            - 4.1a Introduction to Text
            - 4.1b Importance of Text
            - 4.1c Application of Text
        - '- Section: 4.2 Information:':
            subsections:
            - 4.2a Introduction to Information
            - 4.2b Importance of Information
            - 4.2c Application of Information
    - '- Chapter 5: Page: lecture-notes:':
        sections:
        - '- Section: 5.1 Text:':
            subsections:
            - 5.1a Introduction to Text
            - 5.1b Importance of Text
            - 5.1c Application of Text
        - '- Section: 5.2 Information:':
            subsections:
            - 5.2a Introduction to Information
            - 5.2b Importance of Information
            - 5.2c Application of Information
    - '- Chapter 6: Page: recitations:':
        sections:
        - '- Section: 6.1 Text:':
            subsections:
            - 6.1a Introduction to Text
            - 6.1b Importance of Text
            - 6.1c Application of Text
        - '- Section: 6.2 Information:':
            subsections:
            - 6.2a Introduction to Information
            - 6.2b Importance of Information
            - 6.2c Application of Information
    - '- Chapter 7: Page: assignments:':
        sections:
        - '- Section: 7.1 Text:':
            subsections:
            - 7.1a Introduction to Text
            - 7.1b Importance of Text
            - 7.1c Application of Text
        - '- Section: 7.2 Information:':
            subsections:
            - 7.2a Introduction to Information
            - 7.2b Importance of Information
            - 7.2c Application of Information
    - '- Chapter 8: Page: exams:':
        sections:
        - '- Section: 8.1 Text:':
            subsections:
            - 8.1a Introduction to Text
            - 8.1b Importance of Text
            - 8.1c Application of Text
        - '- Section: 8.2 Information:':
            subsections:
            - 8.2a Introduction to Information
            - 8.2b Importance of Information
            - 8.2c Application of Information
    - '- Chapter 9: Page: syllabus:':
        sections:
        - '- Section: 9.1 Information:':
            subsections:
            - 9.1a Introduction to Information
            - 9.1b Importance of Information
            - 9.1c Application of Information
    - '- Chapter 10: Page: calendar:':
        sections:
        - '- Section: 10.1 Text:':
            subsections:
            - 10.1a Introduction to Text
            - 10.1b Importance of Text
            - 10.1c Application of Text
        - '- Section: 10.2 Information:':
            subsections:
            - 10.2a Introduction to Information
            - 10.2b Importance of Information
            - 10.2c Application of Information
    - '- Chapter 11: Page: projects:':
        sections:
        - '- Section: 11.1 Text:':
            subsections:
            - 11.1a Introduction to Text
            - 11.1b Importance of Text
            - 11.1c Application of Text
        - '- Section: 11.2 Information:':
            subsections:
            - 11.2a Introduction to Information
            - 11.2b Importance of Information
            - 11.2c Application of Information
    - '- Chapter 12: Course Evaluation:':
        sections:
        - '- Section: 12.1 Evaluation Criteria:':
            subsections:
            - 12.1a Introduction to Evaluation Criteria
            - 12.1b Importance of Evaluation Criteria
            - 12.1c Application of Evaluation Criteria
        - '- Section: 12.2 Evaluation Methods:':
            subsections:
            - 12.2a Introduction to Evaluation Methods
            - 12.2b Importance of Evaluation Methods
            - 12.2c Application of Evaluation Methods
    - '- Chapter 13: Course Objectives:':
        sections:
        - '- Section: 13.1 Understanding Objectives:':
            subsections:
            - 13.1a Introduction to Course Objectives
            - 13.1b Importance of Course Objectives
            - 13.1c Application of Course Objectives
    - '- Chapter 14: Course Outcomes:':
        sections:
        - '- Section: 14.1 Expected Outcomes:':
            subsections:
            - 14.1a Introduction to Course Outcomes
            - 14.1b Importance of Course Outcomes
            - 14.1c Application of Course Outcomes
    - '- Chapter 15: Course Materials:':
        sections:
        - '- Section: 15.1 Required Materials:':
            subsections:
            - 15.1a Introduction to Course Materials
            - 15.1b Importance of Course Materials
            - 15.1c Application of Course Materials
    - '- Chapter 16: Course Schedule:':
        sections:
        - '- Section: 16.1 Understanding Schedule:':
            subsections:
            - 16.1a Introduction to Course Schedule
            - 16.1b Importance of Course Schedule
            - 16.1c Application of Course Schedule
    - '- Chapter 17: Course Policies:':
        sections:
        - '- Section: 17.1 Understanding Policies:':
            subsections:
            - 17.1a Introduction to Course Policies
            - 17.1b Importance of Course Policies
            - 17.1c Application of Course Policies
    - '- Chapter 18: Course Assignments:':
        sections:
        - '- Section: 18.1 Understanding Assignments:':
            subsections:
            - 18.1a Introduction to Course Assignments
            - 18.1b Importance of Course Assignments
            - 18.1c Application of Course Assignments
    - '- Chapter 19: Course Examinations:':
        sections:
        - '- Section: 19.1 Understanding Examinations:':
            subsections:
            - 19.1a Introduction to Course Examinations
            - 19.1b Importance of Course Examinations
            - 19.1c Application of Course Examinations
    - '- Chapter 20: Course Projects:':
        sections:
        - '- Section: 20.1 Understanding Projects:':
            subsections:
            - 20.1a Introduction to Course Projects
            - 20.1b Importance of Course Projects
            - 20.1c Application of Course Projects
