textbook:
  'Environmental Microbiology Textbook":':
    chapters:
    - '- Chapter 1: Introduction:':
        sections:
        - '- Section: 1.1 Scope, syllabus, requirements':
            subsections: []
        - '- Section: 1.2 History of (environmental) microbiology':
            subsections: []
        - '- Section: 1.3 Importance of Environmental Microbiology':
            subsections: []
    - '- Chapter 2: Cell Biology and Genetics:':
        sections:
        - '- Section: 2.1 Observation tools:':
            subsections:
            - 2.1a Microscopy
            - 2.1b Culturing techniques
            - 2.1c Molecular biology techniques
        - '- Section: 2.2 Chemical composition of microbial cells':
            subsections: []
        - '- Section: 2.3 Cell structure':
            subsections: []
        - '- Section: 2.4 Genetic elements:':
            subsections:
            - 2.4a Mutation
            - 2.4b Genetic exchange
        - '- Section: 2.5 Taxonomy and phylogeny':
            subsections: []
        - '- Section: 2.6 Microbial Evolution':
            subsections: []
    - '- Chapter 3: Biosynthesis and Fuelling:':
        sections:
        - '- Section: 3.1 Metabolism':
            subsections: []
        - '- Section: 3.2 Anabolism':
            subsections: []
        - '- Section: 3.3 Key enzymes':
            subsections: []
        - '- Section: 3.4 Biosynthesis':
            subsections: []
        - '- Section: 3.5 Nutrient assimilation':
            subsections: []
        - '- Section: 3.6 Fuelling reactions':
            subsections: []
        - '- Section: 3.7 Energetics and Energy Sources':
            subsections: []
        - '- Section: 3.8 Metabolic Pathways and Regulation':
            subsections: []
    - '- Chapter 4: Metabolic Diversity:':
        sections:
        - '- Section: 4.1 Aerobic respirations':
            subsections: []
        - '- Section: 4.2 Diversity of aerobic metabolism':
            subsections: []
        - '- Section: 4.3 Fermentation pathways':
            subsections: []
        - '- Section: 4.4 Anaerobic metabolism':
            subsections: []
        - '- Section: 4.5 Nitrogen metabolism':
            subsections: []
        - '- Section: 4.6 Sulfur metabolism':
            subsections: []
        - '- Section: 4.7 Carbon metabolism':
            subsections: []
        - '- Section: 4.8 Phosphorus metabolism':
            subsections: []
        - '- Section: 4.9 Iron metabolism':
            subsections: []
        - '- Section: 4.10 Hydrogen metabolism':
            subsections: []
        - '- Section: 4.11 Microbial Metabolism in Extreme Environments':
            subsections: []
        - '- Section: 4.12 Metabolic Interactions and Cooperation':
            subsections: []
    - '- Chapter 5: Methods:':
        sections:
        - '- Section: 5.1 Microscopy techniques':
            subsections: []
        - '- Section: 5.2 Culturing techniques':
            subsections: []
        - '- Section: 5.3 Molecular biology techniques':
            subsections: []
        - '- Section: 5.4 Biochemical techniques':
            subsections: []
        - '- Section: 5.5 Metagenomics':
            subsections: []
        - '- Section: 5.6 Proteomics':
            subsections: []
        - '- Section: 5.7 Metabolomics':
            subsections: []
        - '- Section: 5.8 Bioinformatics and Computational Tools in Environmental Microbiology':
            subsections: []
    - '- Chapter 6: Populations, Communities, Ecosystems:':
        sections:
        - '- Section: 6.1 Population growth dynamics':
            subsections: []
        - '- Section: 6.2 Microbial interactions':
            subsections: []
        - '- Section: 6.3 Community structure and function':
            subsections: []
        - '- Section: 6.4 Biogeochemical cycles':
            subsections: []
        - '- Section: 6.5 Microbial ecology':
            subsections: []
        - '- Section: 6.6 Nutrient cycling':
            subsections: []
        - '- Section: 6.7 Microbes and Plant Interactions':
            subsections: []
        - '- Section: 6.8 Microbes and Animal Interactions':
            subsections: []
        - '- Section: 6.9 Microbes and Human Health':
            subsections: []
        - '- Section: 6.10 Microbes and Climate Change':
            subsections: []
    - '- Chapter 7: Applied Environmental Microbiology:':
        sections:
        - '- Section: 7.1 Bioremediation':
            subsections: []
        - '- Section: 7.2 Wastewater treatment':
            subsections: []
        - '- Section: 7.3 Soil microbiology':
            subsections: []
        - '- Section: 7.4 Environmental monitoring':
            subsections: []
        - '- Section: 7.5 Microbial indicators':
            subsections: []
        - '- Section: 7.6 Public health microbiology':
            subsections: []
        - '- Section: 7.7 Food microbiology':
            subsections: []
        - '- Section: 7.8 Water microbiology':
            subsections: []
        - '- Section: 7.9 Air microbiology':
            subsections: []
        - '- Section: 7.10 Industrial microbiology':
            subsections: []
        - '- Section: 7.11 Microbes and Sustainable Agriculture':
            subsections: []
        - '- Section: 7.12 Microbes and Renewable Energy Production':
            subsections: []
        - '- Section: 7.13 Microbes and Biotechnology Applications':
            subsections: []
        - '- Section: 7.14 Microbes and Waste Management':
            subsections: []
        - '- Section: 7.15 Microbes and Environmental Policy':
            subsections: []
    - '- Chapter 8: Microbial Diversity and Evolution:':
        sections:
        - '- Section: 8.1 Microbial Diversity:':
            subsections:
            - 8.1a Bacteria
            - 8.1b Archaea
            - 8.1c Fungi
            - 8.1d Viruses
        - '- Section: 8.2 Microbial Evolution:':
            subsections:
            - 8.2a Evolutionary Theories
            - 8.2b Microbial Phylogeny
            - 8.2c Microbial Genomics and Evolution
    - '- Chapter 9: Microbial Physiology:':
        sections:
        - '- Section: 9.1 Microbial Growth:':
            subsections:
            - 9.1a Growth Factors
            - 9.1b Growth Curve
            - 9.1c Growth Rate
        - '- Section: 9.2 Microbial Metabolism:':
            subsections:
            - 9.2a Metabolic Pathways
            - 9.2b Energy Production
            - 9.2c Metabolic Regulation
        - '- Section: 9.3 Microbial Genetics:':
            subsections:
            - 9.3a Genetic Material
            - 9.3b Genetic Exchange
            - 9.3c Genetic Engineering
    - '- Chapter 10: Microbial Ecology:':
        sections:
        - '- Section: 10.1 Microbial Habitats:':
            subsections:
            - 10.1a Soil Microbiology
            - 10.1b Aquatic Microbiology
            - 10.1c Atmospheric Microbiology
        - '- Section: 10.2 Microbial Interactions:':
            subsections:
            - 10.2a Symbiosis
            - 10.2b Competition
            - 10.2c Predation
        - '- Section: 10.3 Microbial Biogeochemical Cycles:':
            subsections:
            - 10.3a Carbon Cycle
            - 10.3b Nitrogen Cycle
            - 10.3c Sulfur Cycle
    - '- Chapter 11: Microbial Pathogenesis:':
        sections:
        - '- Section: 11.1 Pathogenic Microorganisms:':
            subsections:
            - 11.1a Bacterial Pathogens
            - 11.1b Viral Pathogens
            - 11.1c Fungal Pathogens
        - '- Section: 11.2 Host-Microbe Interactions:':
            subsections:
            - 11.2a Infection
            - 11.2b Immune Response
            - 11.2c Disease Progression
        - '- Section: 11.3 Antimicrobial Agents:':
            subsections:
            - 11.3a Antibiotics
            - 11.3b Antiviral Agents
            - 11.3c Antifungal Agents
    - '- Chapter 12: Environmental Biotechnology:':
        sections:
        - '- Section: 12.1 Bioremediation:':
            subsections:
            - 12.1a In Situ Bioremediation
            - 12.1b Ex Situ Bioremediation
            - 12.1c Bioaugmentation
        - '- Section: 12.2 Bioenergy:':
            subsections:
            - 12.2a Biofuels
            - 12.2b Biogas
            - 12.2c Biohydrogen
        - '- Section: 12.3 Industrial Microbiology:':
            subsections:
            - 12.3a Fermentation
            - 12.3b Production of Enzymes and Chemicals
            - 12.3c Waste Treatment
    - '- Chapter 13: Microbial Genomics:':
        sections:
        - '- Section: 13.1 Genome Sequencing:':
            subsections:
            - 13.1a Sequencing Technologies
            - 13.1b Genome Assembly
            - 13.1c Genome Annotation
        - '- Section: 13.2 Comparative Genomics:':
            subsections:
            - 13.2a Genome Evolution
            - 13.2b Phylogenomics
            - 13.2c Functional Genomics
        - '- Section: 13.3 Metagenomics:':
            subsections:
            - 13.3a Metagenomic Sequencing
            - 13.3b Metagenomic Analysis
            - 13.3c Metagenomic Applications
    - '- Chapter 14: Microbial Proteomics:':
        sections:
        - '- Section: 14.1 Protein Expression:':
            subsections:
            - 14.1a Protein Synthesis
            - 14.1b Protein Folding
            - 14.1c Post-Translational Modifications
        - '- Section: 14.2 Protein Analysis:':
            subsections:
            - 14.2a Protein Separation
            - 14.2b Protein Identification
            - 14.2c Protein Quantification
        - '- Section: 14.3 Functional Proteomics:':
            subsections:
            - 14.3a Protein-Protein Interactions
            - 14.3b Protein Localization
            - 14.3c Protein Function
    - '- Chapter 15: Microbial Metabolomics:':
        sections:
        - '- Section: 15.1 Metabolite Analysis:':
            subsections:
            - 15.1a Metabolite Extraction
            - 15.1b Metabolite Identification
            - 15.1c Metabolite Quantification
        - '- Section: 15.2 Metabolic Profiling:':
            subsections:
            - 15.2a Targeted Metabolomics
            - 15.2b Untargeted Metabolomics
            - 15.2c Metabolic Fingerprinting
        - '- Section: 15.3 Metabolic Pathway Analysis:':
            subsections:
            - 15.3a Metabolic Network Reconstruction
            - 15.3b Metabolic Flux Analysis
            - 15.3c Metabolic Pathway Enrichment
    - '- Chapter 16: Microbial Systems Biology:':
        sections:
        - '- Section: 16.1 Systems Biology Approach:':
            subsections:
            - 16.1a Data Integration
            - 16.1b Network Analysis
            - 16.1c Mathematical Modeling
        - '- Section: 16.2 Microbial Community Analysis:':
            subsections:
            - 16.2a Community Structure
            - 16.2b Community Dynamics
            - 16.2c Community Function
        - '- Section: 16.3 Synthetic Biology:':
            subsections:
            - 16.3a Genetic Circuit Design
            - 16.3b Metabolic Engineering
            - 16.3c Synthetic Genomes
    - '- Chapter 17: Microbial Ecology and Evolution:':
        sections:
        - '- Section: 17.1 Microbial Diversity:':
            subsections:
            - 17.1a Biodiversity
            - 17.1b Biogeography
            - 17.1c Microbial Dark Matter
        - '- Section: 17.2 Microbial Evolution:':
            subsections:
            - 17.2a Evolutionary Theories
            - 17.2b Microbial Phylogeny
            - 17.2c Microbial Genomics and Evolution
        - '- Section: 17.3 Microbial Ecology:':
            subsections:
            - 17.3a Microbial Habitats
            - 17.3b Microbial Interactions
            - 17.3c Microbial Biogeochemical Cycles
    - '- Chapter 18: Microbial Pathogenesis and Public Health:':
        sections:
        - '- Section: 18.1 Pathogenic Microorganisms:':
            subsections:
            - 18.1a Bacterial Pathogens
            - 18.1b Viral Pathogens
            - 18.1c Fungal Pathogens
        - '- Section: 18.2 Host-Microbe Interactions:':
            subsections:
            - 18.2a Infection
            - 18.2b Immune Response
            - 18.2c Disease Progression
        - '- Section: 18.3 Public Health Microbiology:':
            subsections:
            - 18.3a Microbial Indicators
            - 18.3b Waterborne Diseases
            - 18.3c Foodborne Diseases
    - '- Chapter 19: Environmental Biotechnology:':
        sections:
        - '- Section: 19.1 Bioremediation:':
            subsections:
            - 19.1a In Situ Bioremediation
            - 19.1b Ex Situ Bioremediation
            - 19.1c Bioaugmentation
        - '- Section: 19.2 Bioenergy:':
            subsections:
            - 19.2a Biofuels
            - 19.2b Biogas
            - 19.2c Biohydrogen
        - '- Section: 19.3 Industrial Microbiology:':
            subsections:
            - 19.3a Fermentation
            - 19.3b Production of Enzymes and Chemicals
            - 19.3c Waste Treatment
    - '- Chapter 20: Future Perspectives:':
        sections:
        - '- Section: 20.1 Emerging Technologies:':
            subsections:
            - 20.1a Nanotechnology in Environmental Microbiology
            - 20.1b Synthetic Biology for Environmental Applications
            - 20.1c Microbial Electrochemical Systems
        - '- Section: 20.2 Climate Change and Microbes:':
            subsections:
            - 20.2a Microbes and Carbon Sequestration
            - 20.2b Microbes and Methane Emissions
            - 20.2c Microbes and Ocean Acidification
        - '- Section: 20.3 Microbes and Sustainable Development:':
            subsections:
            - 20.3a Microbes and Sustainable Agriculture
            - 20.3b Microbes and Renewable Energy Production
            - 20.3c Microbes and Waste Management
