textbook:
  'Environmental Justice Law and Policy Textbook":':
    chapters:
    - '- Chapter 1: Introduction, Theories, and Histories of Environmental Justice:':
        sections:
        - '- Section: 1.1 Founding Documents of Environmental Justice:':
            subsections:
            - 1.1a Origin of Environmental Justice
            - 1.1b Key Documents in Environmental Justice
            - 1.1c Impact of Founding Documents
        - '- Section: 1.2 Histories of the Environmental Justice Movement:':
            subsections:
            - 1.2a Early Movements and Protests
            - 1.2b Key Figures in the Movement
            - 1.2c Evolution of the Movement
    - '- Chapter 2: Theories of Environmental Justice:':
        sections:
        - '- Section: 2.1 Critical Race Theory:':
            subsections:
            - 2.1a Definition of Critical Race Theory
            - 2.1b Application in Environmental Justice
            - 2.1c Case Studies
        - '- Section: 2.2 Environmental Racism:':
            subsections:
            - 2.2a Definition of Environmental Racism
            - 2.2b Examples of Environmental Racism
            - 2.2c Addressing Environmental Racism
        - '- Section: 2.3 Distributive Justice:':
            subsections:
            - 2.3a Definition of Distributive Justice
            - 2.3b Role in Environmental Justice
            - 2.3c Case Studies
        - '- Section: 2.4 Procedural Justice:':
            subsections:
            - 2.4a Definition of Procedural Justice
            - 2.4b Importance in Environmental Justice
            - 2.4c Examples and Case Studies
    - '- Chapter 3: Causation:':
        sections:
        - '- Section: 3.1 Proximate and Ultimate Causes:':
            subsections:
            - 3.1a Definition of Proximate and Ultimate Causes
            - 3.1b Role in Environmental Justice
            - 3.1c Case Studies
        - '- Section: 3.2 Cumulative Impacts:':
            subsections:
            - 3.2a Definition of Cumulative Impacts
            - 3.2b Importance in Environmental Justice
            - 3.2c Examples and Case Studies
        - '- Section: 3.3 Environmental Injustice:':
            subsections:
            - 3.3a Definition of Environmental Injustice
            - 3.3b Causes and Effects
            - 3.3c Addressing Environmental Injustice
        - '- Section: 3.4 Environmental Displacement:':
            subsections:
            - 3.4a Definition of Environmental Displacement
            - 3.4b Causes and Effects
            - 3.4c Case Studies
    - '- Chapter 4: Environmental Impact Assessment:':
        sections:
        - '- Section: 4.1 Purpose and Process of EIA:':
            subsections:
            - 4.1a Definition of Environmental Impact Assessment
            - 4.1b Process of Conducting an EIA
            - 4.1c Importance in Environmental Justice
        - '- Section: 4.2 Stakeholder Engagement in EIA:':
            subsections:
            - 4.2a Importance of Stakeholder Engagement
            - 4.2b Methods for Engaging Stakeholders
            - 4.2c Case Studies
        - '- Section: 4.3 Environmental Justice in EIA:':
            subsections:
            - 4.3a Role of Environmental Justice in EIA
            - 4.3b Case Studies
            - 4.3c Future Directions
        - '- Section: 4.4 Case Studies of EIA in Environmental Justice:':
            subsections:
            - 4.4a Case Study 1
            - 4.4b Case Study 2
            - 4.4c Case Study 3
    - '- Chapter 5: Site Cleanup and Enforcement:':
        sections:
        - '- Section: 5.1 Superfund Program:':
            subsections:
            - 5.1a Definition of Superfund Program
            - 5.1b Role in Environmental Justice
            - 5.1c Case Studies
        - '- Section: 5.2 Brownfields:':
            subsections:
            - 5.2a Definition of Brownfields
            - 5.2b Environmental Justice Issues
            - 5.2c Case Studies
        - '- Section: 5.3 Remediation Technologies:':
            subsections:
            - 5.3a Overview of Remediation Technologies
            - 5.3b Role in Environmental Justice
            - 5.3c Case Studies
        - '- Section: 5.4 Community Involvement in Site Cleanup:':
            subsections:
            - 5.4a Importance of Community Involvement
            - 5.4b Methods for Involving Community
            - 5.4c Case Studies
    - '- Chapter 6: Advancing Environmental Justice: Risk, Regulation, Information:':
        sections:
        - '- Section: 6.1 Risk Assessment and Management:':
            subsections:
            - 6.1a Definition of Risk Assessment and Management
            - 6.1b Role in Environmental Justice
            - 6.1c Case Studies
        - '- Section: 6.2 Environmental Regulations and Policies:':
            subsections:
            - 6.2a Overview of Environmental Regulations and Policies
            - 6.2b Impact on Environmental Justice
            - 6.2c Case Studies
        - '- Section: 6.3 Environmental Data and Information Access:':
            subsections:
            - 6.3a Importance of Data and Information Access
            - 6.3b Role in Environmental Justice
            - 6.3c Case Studies
        - '- Section: 6.4 Environmental Justice and Public Health:':
            subsections:
            - 6.4a Connection Between Environmental Justice and Public Health
            - 6.4b Public Health Impacts of Environmental Injustice
            - 6.4c Case Studies
    - '- Chapter 7: Standard-Setting:':
        sections:
        - '- Section: 7.1 Environmental Standards and Guidelines:':
            subsections:
            - 7.1a Overview of Environmental Standards and Guidelines
            - 7.1b Role in Environmental Justice
            - 7.1c Case Studies
        - '- Section: 7.2 Environmental Justice in Standard-Setting:':
            subsections:
            - 7.2a Role of Environmental Justice in Standard-Setting
            - 7.2b Case Studies
            - 7.2c Future Directions
        - '- Section: 7.3 Regulatory Impact Analysis:':
            subsections:
            - 7.3a Definition of Regulatory Impact Analysis
            - 7.3b Role in Environmental Justice
            - 7.3c Case Studies
    - '- Chapter 8: Federal Responses:':
        sections:
        - '- Section: 8.1 Federal Agencies and Environmental Justice:':
            subsections:
            - 8.1a Role of Federal Agencies in Environmental Justice
            - 8.1b Case Studies
            - 8.1c Future Directions
        - '- Section: 8.2 Environmental Justice Executive Order:':
            subsections:
            - 8.2a Overview of the Environmental Justice Executive Order
            - 8.2b Impact on Environmental Justice
            - 8.2c Case Studies
        - '- Section: 8.3 Title VI of the Civil Rights Act:':
            subsections:
            - 8.3a Overview of Title VI
            - 8.3b Role in Environmental Justice
            - 8.3c Case Studies
    - '- Chapter 9: The Production of Environmental Knowledge:':
        sections:
        - '- Section: 9.1 Scientific Research and Environmental Justice:':
            subsections:
            - 9.1a Role of Scientific Research in Environmental Justice
            - 9.1b Case Studies
            - 9.1c Future Directions
        - '- Section: 9.2 Indigenous Knowledge and Environmental Justice:':
            subsections:
            - 9.2a Role of Indigenous Knowledge in Environmental Justice
            - 9.2b Case Studies
            - 9.2c Future Directions
        - '- Section: 9.3 Citizen Science and Environmental Justice:':
            subsections:
            - 9.3a Role of Citizen Science in Environmental Justice
            - 9.3b Case Studies
            - 9.3c Future Directions
        - '- Section: 9.4 Environmental Justice in Academic Institutions:':
            subsections:
            - 9.4a Role of Academic Institutions in Environmental Justice
            - 9.4b Case Studies
            - 9.4c Future Directions
    - '- Chapter 10: Risk, Regulation, and Environmental Justice:':
        sections:
        - '- Section: 10.1 Environmental Justice and Risk Assessment:':
            subsections:
            - 10.1a Role of Risk Assessment in Environmental Justice
            - 10.1b Case Studies
            - 10.1c Future Directions
        - '- Section: 10.2 Precautionary Principle and Environmental Justice:':
            subsections:
            - 10.2a Definition of the Precautionary Principle
            - 10.2b Role in Environmental Justice
            - 10.2c Case Studies
        - '- Section: 10.3 Environmental Justice and Regulatory Enforcement:':
            subsections:
            - 10.3a Role of Regulatory Enforcement in Environmental Justice
            - 10.3b Case Studies
            - 10.3c Future Directions
        - '- Section: 10.4 Environmental Justice and Environmental Governance:':
            subsections:
            - 10.4a Role of Environmental Governance in Environmental Justice
            - 10.4b Case Studies
            - 10.4c Future Directions
    - '- Chapter 11: Environmental Justice Movements and Activism:':
        sections:
        - '- Section: 11.1 Grassroots Environmental Justice Organizations:':
            subsections:
            - 11.1a Role of Grassroots Organizations in Environmental Justice
            - 11.1b Case Studies
            - 11.1c Future Directions
        - '- Section: 11.2 International Environmental Justice Movements:':
            subsections:
            - 11.2a Overview of International Environmental Justice Movements
            - 11.2b Case Studies
            - 11.2c Future Directions
        - '- Section: 11.3 Youth Activism and Environmental Justice:':
            subsections:
            - 11.3a Role of Youth Activism in Environmental Justice
            - 11.3b Case Studies
            - 11.3c Future Directions
        - '- Section: 11.4 Intersectionality in Environmental Justice:':
            subsections:
            - 11.4a Definition of Intersectionality
            - 11.4b Role in Environmental Justice
            - 11.4c Case Studies
    - '- Chapter 12: Environmental Justice and Climate Change:':
        sections:
        - '- Section: 12.1 Climate Justice and Equity:':
            subsections:
            - 12.1a Definition of Climate Justice
            - 12.1b Role in Environmental Justice
            - 12.1c Case Studies
        - '- Section: 12.2 Adaptation and Resilience in Environmental Justice:':
            subsections:
            - 12.2a Role of Adaptation and Resilience in Environmental Justice
            - 12.2b Case Studies
            - 12.2c Future Directions
        - '- Section: 12.3 Mitigation and Environmental Justice:':
            subsections:
            - 12.3a Role of Mitigation in Environmental Justice
            - 12.3b Case Studies
            - 12.3c Future Directions
    - '- Chapter 13: Environmental Justice and Indigenous Rights:':
        sections:
        - '- Section: 13.1 Indigenous Environmental Justice Frameworks:':
            subsections:
            - 13.1a Overview of Indigenous Environmental Justice Frameworks
            - 13.1b Case Studies
            - 13.1c Future Directions
        - '- Section: 13.2 Land Rights and Environmental Justice:':
            subsections:
            - 13.2a Role of Land Rights in Environmental Justice
            - 13.2b Case Studies
            - 13.2c Future Directions
        - '- Section: 13.3 Indigenous Sovereignty and Environmental Justice:':
            subsections:
            - 13.3a Role of Indigenous Sovereignty in Environmental Justice
            - 13.3b Case Studies
            - 13.3c Future Directions
    - '- Chapter 14: Environmental Justice and Food Justice:':
        sections:
        - '- Section: 14.1 Food Systems and Environmental Justice:':
            subsections:
            - 14.1a Role of Food Systems in Environmental Justice
            - 14.1b Case Studies
            - 14.1c Future Directions
        - '- Section: 14.2 Food Insecurity and Environmental Justice:':
            subsections:
            - 14.2a Role of Food Insecurity in Environmental Justice
            - 14.2b Case Studies
            - 14.2c Future Directions
        - '- Section: 14.3 Food Sovereignty and Environmental Justice:':
            subsections:
            - 14.3a Definition of Food Sovereignty
            - 14.3b Role in Environmental Justice
            - 14.3c Case Studies
    - '- Chapter 15: Environmental Justice and Water Rights:':
        sections:
        - '- Section: 15.1 Water Access and Environmental Justice:':
            subsections:
            - 15.1a Role of Water Access in Environmental Justice
            - 15.1b Case Studies
            - 15.1c Future Directions
        - '- Section: 15.2 Water Pollution and Environmental Justice:':
            subsections:
            - 15.2a Role of Water Pollution in Environmental Justice
            - 15.2b Case Studies
            - 15.2c Future Directions
        - '- Section: 15.3 Water Privatization and Environmental Justice:':
            subsections:
            - 15.3a Role of Water Privatization in Environmental Justice
            - 15.3b Case Studies
            - 15.3c Future Directions
    - '- Chapter 16: Environmental Justice and Energy Policy:':
        sections:
        - '- Section: 16.1 Energy Justice and Equity:':
            subsections:
            - 16.1a Definition of Energy Justice
            - 16.1b Role in Environmental Justice
            - 16.1c Case Studies
        - '- Section: 16.2 Renewable Energy and Environmental Justice:':
            subsections:
            - 16.2a Role of Renewable Energy in Environmental Justice
            - 16.2b Case Studies
            - 16.2c Future Directions
        - '- Section: 16.3 Fossil Fuels and Environmental Justice:':
            subsections:
            - 16.3a Role of Fossil Fuels in Environmental Justice
            - 16.3b Case Studies
            - 16.3c Future Directions
    - '- Chapter 17: Environmental Justice and Urban Planning:':
        sections:
        - '- Section: 17.1 Environmental Justice in Urban Development:':
            subsections:
            - 17.1a Role of Urban Development in Environmental Justice
            - 17.1b Case Studies
            - 17.1c Future Directions
        - '- Section: 17.2 Gentrification and Environmental Justice:':
            subsections:
            - 17.2a Role of Gentrification in Environmental Justice
            - 17.2b Case Studies
            - 17.2c Future Directions
        - '- Section: 17.3 Transit Equity and Environmental Justice:':
            subsections:
            - 17.3a Definition of Transit Equity
            - 17.3b Role in Environmental Justice
            - 17.3c Case Studies
    - '- Chapter 18: Environmental Justice and Environmental Education:':
        sections:
        - '- Section: 18.1 Environmental Justice in K-12 Education:':
            subsections:
            - 18.1a Role of K-12 Education in Environmental Justice
            - 18.1b Case Studies
            - 18.1c Future Directions
        - '- Section: 18.2 Environmental Justice in Higher Education:':
            subsections:
            - 18.2a Role of Higher Education in Environmental Justice
            - 18.2b Case Studies
            - 18.2c Future Directions
        - '- Section: 18.3 Environmental Justice and Environmental Literacy:':
            subsections:
            - 18.3a Role of Environmental Literacy in Environmental Justice
            - 18.3b Case Studies
            - 18.3c Future Directions
    - '- Chapter 19: Environmental Justice and Public Health:':
        sections:
        - '- Section: 19.1 Public Health Impacts of Environmental Injustice:':
            subsections:
            - 19.1a Overview of Public Health Impacts
            - 19.1b Case Studies
            - 19.1c Future Directions
        - '- Section: 19.2 Addressing Public Health Impacts:':
            subsections:
            - 19.2a Strategies for Addressing Public Health Impacts
            - 19.2b Case Studies
            - 19.2c Future Directions
    - '- Chapter 20: Future Directions for Environmental Justice:':
        sections:
        - '- Section: 20.1 Emerging Issues in Environmental Justice:':
            subsections:
            - 20.1a Overview of Emerging Issues
            - 20.1b Case Studies
            - 20.1c Future Directions
        - '- Section: 20.2 Strategies for Advancing Environmental Justice:':
            subsections:
            - 20.2a Overview of Strategies
            - 20.2b Case Studies
            - 20.2c Future Directions
        - '- Section: 20.3 Environmental Justice in the 21st Century:':
            subsections:
            - 20.3a Current State of Environmental Justice
            - 20.3b Case Studies
            - 20.3c Future Directions
