"completion": "```yaml\ncourse:\n    Computing and Data Analysis for Environmental\
  \ Applications:\n        topics:\n            - Course Introduction:\n         \
  \       subtopics:\n                    - Course Logistics\n                   \
  \ - Repeated Trials\n                    - Virtual Experiments\n               \
  \     - Probability\n                    - Statistics\n            - Programming\
  \ in MATLAB:\n                subtopics:\n                    - Downloading Data\n\
  \                    - Accessing MATLAB\n                    - MATLAB Environment\n\
  \                    - Variables\n                    - Arrays\n               \
  \     - Scripts\n                    - Plotting Data\n            - Descriptive\
  \ Statistics:\n                subtopics:\n                    - Histograms\n  \
  \                  - Percentiles\n                    - Mean\n                 \
  \   - Median\n                    - Variance\n                    - Characterizing\
  \ Streamflow Data\n            - Probability:\n                subtopics:\n    \
  \                - Experiments\n                    - Outcomes\n               \
  \     - Sample Spaces\n                    - Events\n                    - Axioms\
  \ of Probability\n                    - Methods for Assigning Probabilities\n  \
  \          - MATLAB Operations:\n                subtopics:\n                  \
  \  - Internal MATLAB Functions\n                    - Common MATLAB Operations\n\
  \                    - Element-wise Computations\n                    - Loops\n\
  \                    - Translating Equations to Programs\n            - Joint Probability,\
  \ Independence, Repeated Trials:\n                subtopics:\n                 \
  \   - Joint Probability\n                    - Independent Events\n            \
  \        - Repeated Trials\n            - Combinatorial Methods:\n             \
  \   subtopics:\n                    - Counting Rules\n                    - Combinatorial\
  \ Techniques for Evaluating Probabilities\n            - Conditional Probability\
  \ and Bayes Theorem:\n                subtopics:\n                    - Joint Probability\n\
  \                    - Conditional Probability\n                    - Prior & Posterior\
  \ Probabilities\n                    - Bayes Theorem\n                    - Engineering\
  \ Applications\n            - Random Variables and Probability Distributions:\n\
  \                subtopics:\n                    - Definition of a Random Variable\n\
  \                    - Cumulative Distribution Functions\n                    -\
  \ Mass and Density Functions\n                    - Using Distributions to Assign\
  \ Probabilities\n            - Expectation, Functions of a Random Variable:\n  \
  \              subtopics:\n                    - Expectation\n                 \
  \   - Population Mean and Variance\n                    - Defining and Functions\
  \ of a Single Random Variable\n                    - Solving Derived Distribution\
  \ Problems with Stochastic Simulation\n            - Risk:\n                subtopics:\n\
  \                    - Defining and Evaluating Risk\n                    - Engineering\
  \ Applications\n            - Some Common Probability Distributions:\n         \
  \       subtopics:\n                    - Uniform\n                    - Exponential\n\
  \                    - Normal\n                    - Lognormal Distributions\n \
  \                   - Special Properties of Normal Random Variables\n          \
  \          - Fitting Distributions to Data\n            - Multivariate Probability:\n\
  \                subtopics:\n                    - Multiple Random Variables\n \
  \                   - Joint and Conditional Distributions\n                    -\
  \ Independence\n                    - Covariance and Correlation\n             \
  \       - Computing Conditional Probabilities in MATLAB\n            - Functions\
  \ of Many Random Variables:\n                subtopics:\n                    - Derived\
  \ distributions for multivariate problems\n                    - Moments of linear\
  \ functions of several random variables\n                    - Central Limit Theorem\n\
  \            - Populations and Samples:\n                subtopics:\n          \
  \          - Populations\n                    - Random samples\n               \
  \     - Sample statistics\n                    - Moments of the sample mean and\
  \ variance\n            - Estimation:\n                subtopics:\n            \
  \        - Estimating Distributional Properties\n                    - Assessing\
  \ Estimation Error\n                    - Comparing Alternative Estimators\n   \
  \         - Confidence Intervals:\n                subtopics:\n                \
  \    - Basic Concepts\n                    - Large Sample Confidence Intervals for\
  \ the Population Mean\n                    - Computing Large Sample Confidence Intervals\n\
  \            - Testing Hypotheses about a Single Population:\n                subtopics:\n\
  \                    - Formulating Hypothesis Testing Problems\n               \
  \     - Definitions\n                    - Large Sample Tests of Hypotheses about\
  \ a Single Population\n                    - Applications Using MATLAB\n       \
  \     - Testing Hypotheses about Two Populations:\n                subtopics:\n\
  \                    - Large Sample Tests of Hypotheses about Two Populations\n\
  \                    - Controlled Experiments\n                    - Applications\
  \ Using MATLAB\n            - Small Sample Statistics:\n                subtopics:\n\
  \                    - T, chi-squared and F statistics\n                    - Small\
  \ sample confidence intervals and hypothesis tests\n                    - Applications\
  \ using MATLAB\n            - Analysis of Variance:\n                subtopics:\n\
  \                    - Single-Factor Model\n                    - Significance Testing\n\
  \                    - Applications on MATLAB\n            - Linear Regression:\n\
  \                subtopics:\n                    - Objectives and Assumptions of\
  \ Linear Regression\n                    - Estimating Regression Coefficients\n\
  \                    - Normal Equations\n                    - Some Typical Environmental\
  \ Applications\n            - Analyzing Regression Results:\n                subtopics:\n\
  \                    - Accuracy of Regression Estimates and Predictions\n      \
  \              - Prediction Confidence Intervals\n                    - Testing\
  \ Significance\n                    - Continuation of Environmental Examples\n```\n"
"course_name": "Computing and Data Analysis for Environmental Applications"
"discipline": "engineering"
"field": "computer_science"
"resource_level": "Undergraduate"
"subfield": "data_mining"
