textbook:
  'Trace Element Analysis of Geological, Biological & Environmental Materials by Neutron Activation Analysis: An Exposure":':
    chapters:
    - '- Chapter 1: Introduction:':
        sections:
        - '- Section: 1.1 Neutron Activation Analysis Fundamental Concepts:':
            subsections:
            - 1.1a Introduction to Neutron Activation Analysis
            - 1.1b Principles of Neutron Activation Analysis
            - 1.1c Applications of Neutron Activation Analysis
    - '- Chapter 2: Gamma Detection - Instrumentation Principles:':
        sections:
        - '- Section: 2.1 Neutron Activation Analysis - Applications:':
            subsections:
            - 2.1a Trace Element Analysis of Geological Materials
            - 2.1b Trace Element Analysis of Biological Materials
            - 2.1c Trace Element Analysis of Environmental Materials
        - '- Section: 2.2 Presentation and Report Assignment:':
            subsections:
            - 2.2a Epithermal Neutron Activation Analysis
            - 2.2b Delayed Neutron Activation Analysis
            - 2.2c Prompt Gamma Neutron Activation Analysis
    - '- Chapter 3: Experimental Procedures:':
        sections:
        - '- Section: 3.1 Hands-on Experience with Sample Preparation:':
            subsections:
            - 3.1a Sample Collection Techniques
            - 3.1b Sample Preparation Methods
            - 3.1c Quality Control in Sample Preparation
        - '- Section: 3.2 Hands-on Experience with Gamma Spectrometer:':
            subsections:
            - 3.2a Gamma Spectrometer Operation
            - 3.2b Data Acquisition and Analysis
            - 3.2c Troubleshooting and Maintenance
    - "- Chapter 4: Trace Element Analysis - Student\u2019s Presentations:":
        sections:
        - '- Section: 4.1 [List of student presentations]:':
            subsections:
            - 4.1a Presentation Techniques
            - 4.1b Effective Communication in Scientific Presentations
            - 4.1c Evaluation and Feedback
