textbook:
  'Planning for Sustainable Development: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: Framing Sustainability: Global Problems and Local Actions:':
        sections:
        - '- Section: 1.1 Introduction and Overview:':
            subsections:
            - 1.1a Defining Sustainability
            - 1.1b Importance of Sustainability
            - 1.1c Global Sustainability Issues
        - '- Section: 1.2 Some Prominent Ways of Framing Sustainability:':
            subsections:
            - 1.2a Economic Perspective
            - 1.2b Environmental Perspective
            - 1.2c Social Perspective
        - '- Section: 1.3 Framing Sustainability Locally: An International Comparison:':
            subsections:
            - 1.3a Sustainability in Developed Countries
            - 1.3b Sustainability in Developing Countries
            - 1.3c Comparing Sustainability Practices
    - '- Chapter 2: Understanding and Managing Change in Organizational Settings:':
        sections:
        - '- Section: 2.1 Sustainability and Innovation:':
            subsections:
            - 2.1a Role of Innovation in Sustainability
            - 2.1b Sustainable Innovation Practices
            - 2.1c Case Studies of Sustainable Innovation
        - '- Section: 2.2 Promoting Sustainability in State and Local Government:':
            subsections:
            - 2.2a Government Policies for Sustainability
            - 2.2b Role of Local Government in Sustainability
            - 2.2c Case Studies of Government-led Sustainability Initiatives
        - '- Section: 2.3 Sustainable Action at a University:':
            subsections:
            - 2.3a Importance of Sustainability in Education
            - 2.3b Sustainability Practices in Universities
            - 2.3c Case Studies of University-led Sustainability Initiatives
    - '- Chapter 3: Preliminary Presentations and In-class Critique:':
        sections:
        - '- Section: 3.1 Building a Story about Change:':
            subsections:
            - 3.1a Understanding Change
            - 3.1b Role of Change in Sustainability
            - 3.1c Case Studies of Change for Sustainability
        - '- Section: 3.2 Working Session:':
            subsections:
            - 3.2a Planning for Sustainability
            - 3.2b Implementing Sustainability Plans
            - 3.2c Monitoring and Evaluating Sustainability Plans
        - '- Section: 3.3 Final Presentations:':
            subsections:
            - 3.3a Presenting Sustainability Plans
            - 3.3b Critiquing Sustainability Plans
            - 3.3c Improving Sustainability Plans
