textbook:
  'Environment and Society: A Comprehensive Guide":':
    chapters:
    - '- Chapter 1: Introduction to the Course:':
        sections:
        - '- Section: 1.1 Course Number':
            subsections: []
        - '- Section: 1.2 Course Name':
            subsections: []
        - '- Section: 1.3 Resource Level':
            subsections: []
    - '- Chapter 2: State of the Environment:':
        sections:
        - '- Section: 2.1 Challenges of the New Century':
            subsections: []
        - '- Section: 2.2 Anticipating Environmental ''Surprise'':':
            subsections:
            - 2.2a Climate Change and its Impacts
            - 2.2b Pollution and its Effects
    - '- Chapter 3: Readings:':
        sections:
        - '- Section: 3.1 No Readings':
            subsections: []
    - '- Chapter 4: Assignments:':
        sections:
        - '- Section: 4.1 The class will involve considerable reading each week':
            subsections: []
        - '- Section: 4.2 Class participation':
            subsections: []
        - '- Section: 4.3 Several short assignments':
            subsections: []
        - '- Section: 4.4 Term paper and presentation':
            subsections: []
        - '- Section: 4.5 Turn in bio:':
            subsections:
            - 4.5a Research and Writing Skills
            - 4.5b Presentation Techniques
    - '- Chapter 5: Projects:':
        sections:
        - '- Section: 5.1 No Readings':
            subsections: []
    - '- Chapter 6: Exams:':
        sections:
        - '- Section: 6.1 No Readings':
            subsections: []
    - '- Chapter 7: Syllabus:':
        sections:
        - '- Section: 7.1 Information':
            subsections: []
    - '- Chapter 8: Calendar:':
        sections:
        - ? '- Section: 8.1 ''Please note: Reading locations are noted below as: available
            as Books (B) at the COOP; in the Reader (R); or on the Web (W)'':'
          : subsections:
            - 8.1a Course Schedule
            - 8.1b Important Dates
    - '- Chapter 9: Environmental Policies:':
        sections:
        - '- Section: 9.1 Introduction to Environmental Policies':
            subsections: []
        - '- Section: 9.2 National Policies':
            subsections: []
        - '- Section: 9.3 International Policies':
            subsections: []
    - '- Chapter 10: Climate Change:':
        sections:
        - '- Section: 10.1 Understanding Climate Change':
            subsections: []
        - '- Section: 10.2 Impacts of Climate Change':
            subsections: []
        - '- Section: 10.3 Mitigation and Adaptation Strategies':
            subsections: []
    - '- Chapter 11: Biodiversity:':
        sections:
        - '- Section: 11.1 Importance of Biodiversity':
            subsections: []
        - '- Section: 11.2 Threats to Biodiversity':
            subsections: []
        - '- Section: 11.3 Conservation Strategies':
            subsections: []
    - '- Chapter 12: Pollution:':
        sections:
        - '- Section: 12.1 Types of Pollution':
            subsections: []
        - '- Section: 12.2 Effects of Pollution':
            subsections: []
        - '- Section: 12.3 Pollution Control and Management':
            subsections: []
    - '- Chapter 13: Natural Resources:':
        sections:
        - '- Section: 13.1 Types of Natural Resources':
            subsections: []
        - '- Section: 13.2 Sustainable Use of Resources':
            subsections: []
        - '- Section: 13.3 Resource Conservation':
            subsections: []
    - '- Chapter 14: Sustainable Development:':
        sections:
        - '- Section: 14.1 Concept of Sustainable Development':
            subsections: []
        - '- Section: 14.2 Strategies for Sustainable Development':
            subsections: []
        - '- Section: 14.3 Challenges in Implementing Sustainable Development':
            subsections: []
    - '- Chapter 15: Environmental Ethics:':
        sections:
        - '- Section: 15.1 Introduction to Environmental Ethics':
            subsections: []
        - '- Section: 15.2 Role of Ethics in Environmental Conservation':
            subsections: []
        - '- Section: 15.3 Ethical Dilemmas in Environmental Decision Making':
            subsections: []
    - '- Chapter 16: Environmental Laws and Regulations:':
        sections:
        - '- Section: 16.1 Introduction to Environmental Laws':
            subsections: []
        - '- Section: 16.2 Key Environmental Laws and Regulations':
            subsections: []
        - '- Section: 16.3 Enforcement and Compliance':
            subsections: []
    - '- Chapter 17: Environmental Education:':
        sections:
        - '- Section: 17.1 Importance of Environmental Education':
            subsections: []
        - '- Section: 17.2 Approaches to Environmental Education':
            subsections: []
        - '- Section: 17.3 Challenges in Environmental Education':
            subsections: []
    - '- Chapter 18: Environmental Activism:':
        sections:
        - '- Section: 18.1 Role of Activism in Environmental Conservation':
            subsections: []
        - '- Section: 18.2 Key Environmental Movements':
            subsections: []
        - '- Section: 18.3 Challenges in Environmental Activism':
            subsections: []
    - '- Chapter 19: Environmental Technology:':
        sections:
        - '- Section: 19.1 Role of Technology in Environmental Conservation':
            subsections: []
        - '- Section: 19.2 Emerging Environmental Technologies':
            subsections: []
        - '- Section: 19.3 Challenges in Implementing Environmental Technologies':
            subsections: []
    - '- Chapter 20: Future of the Environment:':
        sections:
        - '- Section: 20.1 Predicted Environmental Changes':
            subsections: []
        - '- Section: 20.2 Preparing for the Future':
            subsections: []
        - '- Section: 20.3 Role of Individuals in Shaping the Future':
            subsections: []
